import json
import time
from pathlib import Path
from typing import Dict, Any, Optional

class A1RosettaMapper:
    """
    Manages the A1 Rosetta mapping dictionary for System V4.
    Adheres strictly to the V3 `15_ROSETTA_AND_MINING_ARTIFACTS.md` 
    and the `rosetta.json` schema.
    
    A1 acts as Rosetta. It takes the speculative, mined 'jargon' overlays
    generated by the A2 controlled hallucinations (e.g. classical physics intuitions,
    Jungian/IGT topology overlays, continuous space math) and deterministically
    maps them to strict, mathematical, nonclassical A0 Kernel definitions
    (e.g., S_TERM_OBSERVABLE, S_TERM_KRAUS_CHANNEL).
    
    This ensures that human-readable context overlays never leak into the rigorous
    B-scanned execution layers.
    """

    def __init__(self, workspace_root: str):
        self.workspace_root = Path(workspace_root).resolve()
        self.a1_state_dir = self.workspace_root / "system_v4" / "a1_state"
        self.a2_state_dir = self.workspace_root / "system_v4" / "a2_state"  # Fallback
        self.rosetta_path = self.a1_state_dir / "rosetta.json"
        
        self.a1_state_dir.mkdir(parents=True, exist_ok=True)
        self._ensure_rosetta_exists()

    def _ensure_rosetta_exists(self) -> None:
        if not self.rosetta_path.exists():
            initial_state = {
                "schema": "A2_ROSETTA_OVERLAY_v1",
                "schema_version": 1,
                "mappings": {}
            }
            self._write_rosetta(initial_state)

    def _read_rosetta(self) -> Dict[str, Any]:
        # Fallback for transition
        target_path = self.rosetta_path
        if not target_path.exists():
            old_path = self.a2_state_dir / "rosetta.json"
            if old_path.exists():
                target_path = old_path

        with target_path.open("r", encoding="utf-8") as f:
            return json.load(f)

    def _write_rosetta(self, data: Dict[str, Any]) -> None:
        with self.rosetta_path.open("w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, sort_keys=True)

    def propose_mapping(self, 
                        overlay_term: str, 
                        kernel_spec_id: str, 
                        source_refs: list[str]) -> Dict[str, Any]:
        """
        Propose a new binding between an A2 overlay jargon term and an A0 kernel object.
        Initial state is always PROPOSED.
        """
        rosetta = self._read_rosetta()
        
        # Enforce case conventions:
        # overlay_term should be snake_case/lowercase
        # kernel_spec_id should be UPPERCASE starting with S_TERM_
        overlay_term = overlay_term.strip().lower().replace(" ", "_")
        kernel_spec_id = kernel_spec_id.strip().upper()
        if not kernel_spec_id.startswith("S_TERM_"):
            kernel_spec_id = f"S_TERM_{kernel_spec_id}"

        mapping_entry = {
            "kernel_target_id": kernel_spec_id,
            "mapping_state": "PROPOSED",
            "source_refs": source_refs,
            "updated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        }

        rosetta["mappings"][overlay_term] = mapping_entry
        self._write_rosetta(rosetta)
        return mapping_entry

    def activate_mapping(self, overlay_term: str) -> bool:
        """
        Promotes a mapping from PROPOSED to ACTIVE after verification.
        """
        rosetta = self._read_rosetta()
        overlay_term = overlay_term.strip().lower().replace(" ", "_")
        
        if overlay_term in rosetta["mappings"]:
            rosetta["mappings"][overlay_term]["mapping_state"] = "ACTIVE"
            rosetta["mappings"][overlay_term]["updated_utc"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
            self._write_rosetta(rosetta)
            return True
        return False

    def get_kernel_translation(self, overlay_term: str) -> Optional[str]:
        """
        Translates a human overlay term into the strict canonical kernel ID.
        Returns None if not found or not ACTIVE.
        """
        rosetta = self._read_rosetta()
        overlay_term = overlay_term.strip().lower().replace(" ", "_")
        
        mapping = rosetta["mappings"].get(overlay_term)
        if mapping and mapping.get("mapping_state") == "ACTIVE":
            return mapping.get("kernel_target_id")
        return None
