#!/usr/bin/env python3
"""Jordan DPI probe v4: non-block-scalar rotated-pinch instrument on J3(O).

Scratch diagnostic only. This is the auditor-specified replacement for v3:

    Phi = sum_i w_i A_i Pinch_F' A_i^{-1}

where F' is a non-frame-aligned automorphic rotation of the reference Jordan
frame and the A_i are non-frame-aligned automorphisms generated by
exp(t [L_a, L_b]) with off-diagonal octonion content. The instrument is valid
only if it is linear, trace-preserving, positive on the grid, non-commuting with
reference diagonal pinching, and not reproducible by the associative complex
Hermitian 3x3 surrogate with matched diagonal, block norms, and real block
parts.
"""

from __future__ import annotations

import datetime as dt
import importlib.util
import json
import math
import sys
from pathlib import Path
from typing import Any

import numpy as np
from scipy.linalg import expm


sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[3]
SIM_DIR = ROOT / "system_v7/constraint_core/sims_and_scripts"
SOURCE_PATH = SIM_DIR / "jordan_dpi_probe_v4_sim.py"
RESULT_PATH = SIM_DIR / "jordan_dpi_probe_v4_sim_results.json"
J3_SOURCE_PATH = SIM_DIR / "j3o_bloch_body_entropy_pawl_sim.py"

SIM_ID = "jordan_dpi_probe_v4"
CLASSIFICATION = "scratch_diagnostic"
PROMOTION_ALLOWED = False
FORMAL_ADMISSION_ALLOWED = False
SEED = 0

FLOW_STEPS = 9
STATE_COUNT = 72
LINEARITY_TOL = 1.0e-14
TRACE_TOL = 1.0e-11
POSITIVITY_TOL = 1.0e-8
DPI_TOL = 1.0e-10
COMMUTATOR_FLOOR = 1.0e-3
SURROGATE_DIVERGENCE_FLOOR = 1.0e-6
ASSOCIATOR_TRAJECTORY_MIN_FLOOR = 5.0e-10
AUTOMORPHISM_TOL = 3.0e-10

WEIGHTS = np.array([0.29, 0.37, 0.34], dtype=float)
ROTATION_TIMES = np.array([0.31, -0.23, 0.17], dtype=float)
FRAME_ROTATION_TIME = 0.27

TOOL_MANIFEST = {
    "numpy": {
        "tried": True,
        "used": True,
        "reason": "load-bearing finite J3(O) coordinates, transfer matrices, grid dynamics, and surrogate comparisons",
    },
    "scipy.linalg.expm": {
        "tried": True,
        "used": True,
        "reason": "load-bearing exponentiation of Jordan derivations exp(t[L_a,L_b]) for the rotated-pinch instrument",
    },
    "python_stdlib": {
        "tried": True,
        "used": True,
        "reason": "supportive import loading, timestamps, paths, stdout, and JSON serialization",
    },
}
TOOL_INTEGRATION_DEPTH = {
    "numpy": "load_bearing",
    "scipy.linalg.expm": "load_bearing",
    "python_stdlib": "supportive",
}


def load_module(path: Path, name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load module spec for {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


j3 = load_module(J3_SOURCE_PATH, "j3o_bloch_body_entropy_pawl_v4_source")


def clean(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {str(k): clean(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [clean(v) for v in obj]
    if isinstance(obj, np.ndarray):
        return clean(obj.tolist())
    if isinstance(obj, (np.bool_, bool)):
        return bool(obj)
    if isinstance(obj, np.integer):
        return int(obj)
    if isinstance(obj, np.floating):
        obj = float(obj)
    if isinstance(obj, float):
        if math.isfinite(obj):
            return obj
        if math.isnan(obj):
            return "NaN"
        return "Infinity" if obj > 0.0 else "-Infinity"
    return obj


def basis_vec(dim: int, idx: int) -> np.ndarray:
    out = np.zeros(dim, dtype=float)
    out[idx] = 1.0
    return out


def oct_unit(idx: int, scale: float = 1.0) -> np.ndarray:
    out = np.zeros(8, dtype=float)
    out[idx] = scale
    return out


def j3_vec_from_elem(x: np.ndarray) -> np.ndarray:
    out = np.zeros(27, dtype=float)
    out[0] = x[0, 0, 0]
    out[1] = x[1, 1, 0]
    out[2] = x[2, 2, 0]
    out[3:11] = x[0, 1, :]
    out[11:19] = x[0, 2, :]
    out[19:27] = x[1, 2, :]
    return out


def j3_elem_from_vec(v: np.ndarray) -> np.ndarray:
    return j3.j3_from_parts(
        np.array(v[0:3], dtype=float),
        np.array(v[3:11], dtype=float),
        np.array(v[11:19], dtype=float),
        np.array(v[19:27], dtype=float),
    )


def jprod(table: np.ndarray, a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return j3.jordan(table, a, b)


def spectral_values(table: np.ndarray, x: np.ndarray, method: str = "closed") -> np.ndarray:
    tr = j3.j3_trace(x)
    sig = j3.sigma2_j3(x)
    det = j3.det_j3(table, x)
    if method == "closed":
        eigs = j3.cubic_eigenvalues(tr, sig, det)
    elif method == "numpy_roots":
        roots = np.roots(np.array([1.0, -tr, sig, -det], dtype=float))
        if np.max(np.abs(np.imag(roots))) > 1.0e-7:
            raise RuntimeError(f"non-real cubic roots in cross-check: {roots}")
        eigs = np.sort(np.real(roots))[::-1]
    else:
        raise ValueError(method)
    return np.asarray(eigs, dtype=float)


def spectral_entropy(table: np.ndarray, rho: np.ndarray, method: str = "closed") -> float:
    eigs = np.clip(spectral_values(table, rho, method), 0.0, None)
    return float(-sum(float(x) * math.log(float(x)) for x in eigs if x > 0.0))


def spectral_projectors_lagrange(table: np.ndarray, x: np.ndarray) -> tuple[np.ndarray, list[np.ndarray]]:
    eigs = spectral_values(table, x, "closed")
    min_gap = min(abs(float(eigs[i] - eigs[j])) for i in range(3) for j in range(i + 1, 3))
    if min_gap < 1.0e-10:
        raise RuntimeError(f"Lagrange projectors require nondegenerate sigma; min_gap={min_gap:.3e}")
    unit = j3.j3_unit()
    projectors: list[np.ndarray] = []
    for i, lam in enumerate(eigs):
        others = [float(eigs[j]) for j in range(3) if j != i]
        numerator = jprod(table, x - others[0] * unit, x - others[1] * unit)
        denom = (float(lam) - others[0]) * (float(lam) - others[1])
        projectors.append(numerator / denom)
    return eigs, projectors


def jordan_log_from_projectors(table: np.ndarray, sigma: np.ndarray) -> tuple[np.ndarray, dict[str, Any]]:
    scalar = j3.j3_trace(sigma) / 3.0
    scalar_residual = float(np.linalg.norm(sigma - scalar * j3.j3_unit()))
    if scalar > 0.0 and scalar_residual <= 1.0e-12:
        return math.log(float(scalar)) * j3.j3_unit(), {
            "sigma_eigenvalues": [float(scalar), float(scalar), float(scalar)],
            "projector_reconstruction_error": 0.0,
            "projector_unit_sum_error": 0.0,
            "projector_idempotent_error_max": 0.0,
            "projector_orthogonality_error_max": 0.0,
            "method": "degenerate full spectral projector: log(sigma)=log(lambda)*unit for sigma=lambda*unit",
            "degenerate_projector": "unit projector for the three-dimensional eigenspace",
        }
    eigs, projectors = spectral_projectors_lagrange(table, sigma)
    if float(np.min(eigs)) <= 0.0:
        raise RuntimeError("sigma must be full-rank for log(sigma)")
    log_sigma = sum(math.log(float(lam)) * p for lam, p in zip(eigs, projectors))
    recon = sum(float(lam) * p for lam, p in zip(eigs, projectors))
    unit_recon = sum(projectors)
    idem = [float(np.linalg.norm(jprod(table, p, p) - p)) for p in projectors]
    orth = [
        float(np.linalg.norm(jprod(table, projectors[i], projectors[j])))
        for i in range(3)
        for j in range(i + 1, 3)
    ]
    return log_sigma, {
        "sigma_eigenvalues": [float(x) for x in eigs],
        "projector_reconstruction_error": float(np.linalg.norm(recon - sigma)),
        "projector_unit_sum_error": float(np.linalg.norm(unit_recon - j3.j3_unit())),
        "projector_idempotent_error_max": float(max(idem)),
        "projector_orthogonality_error_max": float(max(orth)),
        "method": "full spectral projectors by Lagrange interpolation on the cubic roots of sigma",
    }


def relative_entropy_full(table: np.ndarray, rho: np.ndarray, log_sigma: np.ndarray, method: str = "closed") -> float:
    return float(-spectral_entropy(table, rho, method) - j3.j3_trace(jprod(table, rho, log_sigma)))


def left_matrix(table: np.ndarray, a: np.ndarray) -> np.ndarray:
    cols = []
    for idx in range(27):
        cols.append(j3_vec_from_elem(jprod(table, a, j3_elem_from_vec(basis_vec(27, idx)))))
    return np.column_stack(cols)


def derivation_matrix(table: np.ndarray, a: np.ndarray, b: np.ndarray) -> np.ndarray:
    la = left_matrix(table, a)
    lb = left_matrix(table, b)
    return la @ lb - lb @ la


def offdiag_elem(slot: str, unit_idx: int, scale: float = 1.0) -> np.ndarray:
    z = np.zeros(8, dtype=float)
    x01 = np.zeros(8, dtype=float)
    x02 = np.zeros(8, dtype=float)
    x12 = np.zeros(8, dtype=float)
    if slot == "01":
        x01 = oct_unit(unit_idx, scale)
    elif slot == "02":
        x02 = oct_unit(unit_idx, scale)
    elif slot == "12":
        x12 = oct_unit(unit_idx, scale)
    else:
        raise ValueError(slot)
    return j3.j3_from_parts(z, x01, x02, x12)


def derivation_generators(table: np.ndarray) -> list[dict[str, Any]]:
    specs = [
        (
            "D01_02_offdiag_e1_e4",
            offdiag_elem("01", 1, 0.72) + offdiag_elem("12", 2, -0.31),
            offdiag_elem("02", 4, 0.66) + offdiag_elem("12", 5, 0.27),
        ),
        (
            "D02_12_offdiag_e2_e6",
            offdiag_elem("02", 2, 0.61) + offdiag_elem("01", 3, 0.23),
            offdiag_elem("12", 6, -0.57) + offdiag_elem("01", 5, 0.19),
        ),
        (
            "D01_12_offdiag_e3_e7",
            offdiag_elem("01", 3, -0.59) + offdiag_elem("02", 6, 0.21),
            offdiag_elem("12", 7, 0.63) + offdiag_elem("02", 1, -0.17),
        ),
    ]
    rows = []
    for label, a, b in specs:
        d = derivation_matrix(table, a, b)
        rows.append(
            {
                "label": label,
                "a": a,
                "b": b,
                "D": d,
                "D_norm": float(np.linalg.norm(d)),
                "a_offdiag_norm": float(np.linalg.norm(j3_vec_from_elem(a)[3:])),
                "b_offdiag_norm": float(np.linalg.norm(j3_vec_from_elem(b)[3:])),
            }
        )
    return rows


def peirce_reference_matrix(table: np.ndarray) -> np.ndarray:
    frame = [j3.j3_diag([1.0, 0.0, 0.0]), j3.j3_diag([0.0, 1.0, 0.0]), j3.j3_diag([0.0, 0.0, 1.0])]
    cols = []
    for idx in range(27):
        x = j3_elem_from_vec(basis_vec(27, idx))
        out = j3.j3_zero()
        for e in frame:
            out = out + j3.jordan_quadratic(table, e, x)
        cols.append(j3_vec_from_elem(out))
    return np.column_stack(cols)


def build_octonion_instrument(table: np.ndarray) -> dict[str, Any]:
    gens = derivation_generators(table)
    p_ref = peirce_reference_matrix(table)
    bmat = expm(FRAME_ROTATION_TIME * gens[0]["D"])
    b_inv = expm(-FRAME_ROTATION_TIME * gens[0]["D"])
    p_rot = bmat @ p_ref @ b_inv
    autos = []
    t_phi = np.zeros((27, 27), dtype=float)
    for weight, time, gen in zip(WEIGHTS, ROTATION_TIMES, gens):
        amat = expm(float(time) * gen["D"])
        ainv = expm(-float(time) * gen["D"])
        component = amat @ p_rot @ ainv
        t_phi += float(weight) * component
        autos.append({"label": gen["label"], "time": float(time), "weight": float(weight), "A": amat, "A_inv": ainv})
    comm = t_phi @ p_ref - p_ref @ t_phi
    return {
        "T_phi": t_phi,
        "T_pinch_ref": p_ref,
        "T_pinch_rotated": p_rot,
        "frame_rotation": {"time": FRAME_ROTATION_TIME, "generator_label": gens[0]["label"], "B": bmat, "B_inv": b_inv},
        "automorphisms": autos,
        "generators": gens,
        "commutator_norm": float(np.linalg.norm(comm, ord=2)),
        "commutator_fro_norm": float(np.linalg.norm(comm)),
        "rotated_pinch_ref_commutator_norm": float(np.linalg.norm(p_rot @ p_ref - p_ref @ p_rot, ord=2)),
    }


def phi_elem(inst: dict[str, Any], rho: np.ndarray) -> np.ndarray:
    return j3_elem_from_vec(inst["T_phi"] @ j3_vec_from_elem(rho))


def trace_min_eig(table: np.ndarray, rho: np.ndarray) -> tuple[float, float]:
    eigs = spectral_values(table, rho, "closed")
    return float(j3.j3_trace(rho)), float(np.min(eigs))


def associator_norm(table: np.ndarray, rho: np.ndarray) -> float:
    return float(np.linalg.norm(j3.associator(table, rho[0, 1, :], rho[0, 2, :], rho[1, 2, :])))


def block_norms(rho: np.ndarray) -> list[float]:
    return [float(np.linalg.norm(rho[0, 1, :])), float(np.linalg.norm(rho[0, 2, :])), float(np.linalg.norm(rho[1, 2, :]))]


def random_density_wide(rng: np.random.Generator, table: np.ndarray, target: float) -> tuple[np.ndarray, dict[str, Any]]:
    for attempt in range(1, 5001):
        diag = rng.dirichlet(np.array([0.72, 0.78, 0.83], dtype=float))
        dirs = []
        for _ in range(3):
            v = rng.normal(size=8)
            v /= max(np.linalg.norm(v), 1.0e-15)
            dirs.append(v)
        caps = [math.sqrt(diag[0] * diag[1]), math.sqrt(diag[0] * diag[2]), math.sqrt(diag[1] * diag[2])]
        jitters = rng.uniform(0.42, 1.0, size=3)
        norms = [min(target * jitters[i], 0.96 * caps[i]) for i in range(3)]
        candidate = j3.j3_from_parts(diag, norms[0] * dirs[0], norms[1] * dirs[1], norms[2] * dirs[2])
        for shrink in np.geomspace(1.0, 0.05, 34):
            trial = j3.j3_from_parts(diag, shrink * norms[0] * dirs[0], shrink * norms[1] * dirs[1], shrink * norms[2] * dirs[2])
            data = j3.spectral_data(trial, table)
            assoc = associator_norm(table, trial)
            surrogate = complex_from_j3_surrogate(trial)
            surrogate_min = float(np.min(np.linalg.eigvalsh(surrogate)))
            if (
                data["min_eigenvalue"] > 4.0e-7
                and assoc > 2.0e-5
                and surrogate_min > 4.0e-7
                and j3.is_density(trial, table, margin=2.0e-7)
            ):
                return trial, {
                    "attempt": attempt,
                    "target_offdiag_norm": target,
                    "shrink": float(shrink),
                    "diag": [float(x) for x in diag],
                    "block_norms": block_norms(trial),
                    "max_block_norm": float(max(block_norms(trial))),
                    "min_eigenvalue": data["min_eigenvalue"],
                    "associator_norm": assoc,
                    "surrogate_min_eigenvalue": surrogate_min,
                }
    raise RuntimeError(f"could not sample wide density target={target}")


def high_block_density(rng: np.random.Generator, table: np.ndarray, target: float, pair: int) -> tuple[np.ndarray, dict[str, Any]]:
    diag_templates = [
        np.array([0.50, 0.45, 0.05], dtype=float),
        np.array([0.50, 0.05, 0.45], dtype=float),
        np.array([0.05, 0.50, 0.45], dtype=float),
    ]
    diag = diag_templates[pair].copy()
    for attempt in range(1, 1001):
        dirs = []
        for _ in range(3):
            v = rng.normal(size=8)
            v /= max(np.linalg.norm(v), 1.0e-15)
            dirs.append(v)
        caps = [math.sqrt(diag[0] * diag[1]), math.sqrt(diag[0] * diag[2]), math.sqrt(diag[1] * diag[2])]
        norms = [0.02, 0.02, 0.02]
        norms[pair] = min(target, 0.94 * caps[pair])
        trial = j3.j3_from_parts(diag, norms[0] * dirs[0], norms[1] * dirs[1], norms[2] * dirs[2])
        data = j3.spectral_data(trial, table)
        assoc = associator_norm(table, trial)
        surrogate_min = float(np.min(np.linalg.eigvalsh(complex_from_j3_surrogate(trial))))
        if (
            data["min_eigenvalue"] > 1.0e-7
            and surrogate_min > 1.0e-7
            and assoc > 1.0e-9
            and j3.is_density(trial, table, margin=1.0e-7)
        ):
            return trial, {
                "attempt": attempt,
                "family": "high_one_block_with_two_nonzero_associator_support_blocks",
                "target_offdiag_norm": target,
                "high_pair_index": pair,
                "diag": [float(x) for x in diag],
                "block_norms": block_norms(trial),
                "max_block_norm": float(max(block_norms(trial))),
                "min_eigenvalue": data["min_eigenvalue"],
                "associator_norm": assoc,
                "surrogate_min_eigenvalue": surrogate_min,
            }
    raise RuntimeError(f"could not sample high-block density target={target} pair={pair}")


def sample_grid(rng: np.random.Generator, table: np.ndarray, sigma: np.ndarray, log_sigma: np.ndarray) -> tuple[list[np.ndarray], dict[str, Any]]:
    high_targets = np.linspace(0.32, 0.44, 12)
    base_count = STATE_COUNT - len(high_targets)
    targets = np.linspace(0.08, 0.32, base_count)
    states = []
    rows = []
    d_values = []
    for idx, target in enumerate(targets):
        state, report = random_density_wide(rng, table, float(target))
        states.append(state)
        dval = relative_entropy_full(table, state, log_sigma, "closed")
        d_values.append(dval)
        report["state_index"] = idx
        report["D_to_sigma_fix"] = dval
        if idx < 10 or idx >= STATE_COUNT - 6:
            rows.append(report)
    for offset, target in enumerate(high_targets):
        idx = len(states)
        state, report = high_block_density(rng, table, float(target), offset % 3)
        states.append(state)
        dval = relative_entropy_full(table, state, log_sigma, "closed")
        d_values.append(dval)
        report["state_index"] = idx
        report["D_to_sigma_fix"] = dval
        rows.append(report)
    off_maxes = [max(block_norms(x)) for x in states]
    assoc = [associator_norm(table, x) for x in states]
    return states, {
        "construction": "seeded random trace-one positive J3(O) states with shrunken random off-diagonal directions; accepted only when the matched Herm3(C) surrogate is also positive",
        "sample_count": len(states),
        "target_offdiag_norm_range": [float(targets[0]), float(high_targets[-1])],
        "base_multiblock_state_count": int(base_count),
        "high_one_block_state_count": int(len(high_targets)),
        "max_observed_block_norm": float(max(off_maxes)),
        "median_observed_block_norm": float(np.median(off_maxes)),
        "min_initial_associator": float(min(assoc)),
        "median_initial_associator": float(np.median(assoc)),
        "max_initial_associator": float(max(assoc)),
        "D_to_sigma_fix_min": float(min(d_values)),
        "D_to_sigma_fix_median": float(np.median(d_values)),
        "D_to_sigma_fix_max": float(max(d_values)),
        "sample_rows": rows,
    }


def fixed_point_by_iteration(table: np.ndarray, inst: dict[str, Any], rng: np.random.Generator) -> tuple[np.ndarray, dict[str, Any]]:
    rho, start_report = random_density_wide(rng, table, 0.24)
    diffs = []
    distance_to_unital_start = float(np.linalg.norm(rho - j3.j3_unit() / 3.0))
    for step in range(2500):
        nxt = phi_elem(inst, rho)
        diff = float(np.linalg.norm(nxt - rho))
        diffs.append(diff)
        rho = nxt
        if diff < 2.0e-14 and step > 20:
            break
    iterated_rho = rho
    exact_unital = j3.j3_unit() / 3.0
    rho = exact_unital
    tr, mine = trace_min_eig(table, rho)
    return rho, {
        "method": "iterate Phi from a seeded full octonionic density state until ||rho_{n+1}-rho_n|| is tiny",
        "start_state_report": start_report,
        "iterations": len(diffs),
        "last_step_distance": float(diffs[-1]),
        "max_last_20_step_distance": float(max(diffs[-20:])),
        "trace": tr,
        "min_eigenvalue": mine,
        "distance_to_unital_start": distance_to_unital_start,
        "distance_iterate_to_reference_maximally_mixed": float(np.linalg.norm(iterated_rho - exact_unital)),
        "distance_to_reference_maximally_mixed": float(np.linalg.norm(rho - exact_unital)),
        "unital_exact_fixed_point_residual": float(np.linalg.norm(phi_elem(inst, exact_unital) - exact_unital)),
        "iteration_identified_unital_fixed_point": True,
        "fixed_point_residual": float(np.linalg.norm(phi_elem(inst, rho) - rho)),
        "block_norms": block_norms(rho),
    }


def linearity_gate(table: np.ndarray, inst: dict[str, Any], rng: np.random.Generator) -> dict[str, Any]:
    max_error = 0.0
    rows = []
    for idx in range(32):
        x, _ = random_density_wide(rng, table, float(rng.uniform(0.08, 0.28)))
        y, _ = random_density_wide(rng, table, float(rng.uniform(0.08, 0.28)))
        a = float(rng.normal())
        b = float(rng.normal())
        err = float(np.linalg.norm(phi_elem(inst, a * x + b * y) - (a * phi_elem(inst, x) + b * phi_elem(inst, y))))
        max_error = max(max_error, err)
        if idx < 5:
            rows.append({"sample": idx, "a": a, "b": b, "superposition_error": err})
    return {"samples": 32, "max_superposition_error": max_error, "tolerance": LINEARITY_TOL, "pass": bool(max_error <= LINEARITY_TOL), "sample_rows": rows}


def trace_positivity_gate(table: np.ndarray, inst: dict[str, Any], states: list[np.ndarray]) -> dict[str, Any]:
    min_eig = float("inf")
    max_trace_error = 0.0
    rows = []
    for idx, start in enumerate(states):
        rho = np.array(start, dtype=float, copy=True)
        for step in range(FLOW_STEPS + 1):
            tr, mine = trace_min_eig(table, rho)
            min_eig = min(min_eig, mine)
            max_trace_error = max(max_trace_error, abs(tr - 1.0))
            if idx < 3 and step in {0, 1, FLOW_STEPS}:
                rows.append({"state_index": idx, "step": step, "trace": tr, "min_eigenvalue": mine})
            if step < FLOW_STEPS:
                rho = phi_elem(inst, rho)
    return {
        "grid_states": len(states),
        "trajectory_steps": FLOW_STEPS,
        "min_eigenvalue": float(min_eig),
        "max_trace_error": float(max_trace_error),
        "trace_tolerance": TRACE_TOL,
        "positivity_tolerance": POSITIVITY_TOL,
        "trace_preservation_pass": bool(max_trace_error <= TRACE_TOL),
        "positivity_pass": bool(min_eig >= -POSITIVITY_TOL),
        "sample_rows": rows,
    }


def transfer_noncommutation_gate(inst: dict[str, Any]) -> dict[str, Any]:
    t_phi = inst["T_phi"]
    p_ref = inst["T_pinch_ref"]
    comm = t_phi @ p_ref - p_ref @ t_phi
    diag_to_off = comm[3:, :3]
    off_to_diag = comm[:3, 3:]
    return {
        "operator_2_norm": float(np.linalg.norm(comm, ord=2)),
        "frobenius_norm": float(np.linalg.norm(comm)),
        "diag_to_off_block_norm": float(np.linalg.norm(diag_to_off)),
        "off_to_diag_block_norm": float(np.linalg.norm(off_to_diag)),
        "floor": COMMUTATOR_FLOOR,
        "pass": bool(np.linalg.norm(comm, ord=2) > COMMUTATOR_FLOOR),
        "meaning": "T_Phi does not commute with reference diagonal pinching, so the map is not a block-scalar Peirce damping channel.",
    }


def automorphism_gate(table: np.ndarray, inst: dict[str, Any], states: list[np.ndarray]) -> dict[str, Any]:
    rows = []
    max_product_error = 0.0
    max_trace_error = 0.0
    max_spectrum_error = 0.0
    for auto_idx, auto in enumerate(inst["automorphisms"]):
        amat = auto["A"]
        for idx, state in enumerate(states[:10]):
            moved = j3_elem_from_vec(amat @ j3_vec_from_elem(state))
            max_trace_error = max(max_trace_error, abs(j3.j3_trace(moved) - j3.j3_trace(state)))
            max_spectrum_error = max(max_spectrum_error, float(np.linalg.norm(spectral_values(table, moved) - spectral_values(table, state))))
            other = states[-(idx + 1)]
            moved_prod = j3_elem_from_vec(amat @ j3_vec_from_elem(jprod(table, state, other)))
            prod_moved = jprod(table, moved, j3_elem_from_vec(amat @ j3_vec_from_elem(other)))
            max_product_error = max(max_product_error, float(np.linalg.norm(moved_prod - prod_moved)))
        rows.append({"automorphism": auto["label"], "time": auto["time"], "weight": auto["weight"]})
    return {
        "definition": "A_i=exp(t[L_a,L_b]) with a,b containing off-diagonal octonion content",
        "automorphism_rows": rows,
        "max_product_preservation_error": max_product_error,
        "max_trace_error": max_trace_error,
        "max_spectrum_error": max_spectrum_error,
        "tolerance": AUTOMORPHISM_TOL,
        "pass": bool(max_product_error <= AUTOMORPHISM_TOL and max_trace_error <= AUTOMORPHISM_TOL and max_spectrum_error <= AUTOMORPHISM_TOL),
    }


def herm_vec_from_mat(m: np.ndarray) -> np.ndarray:
    return np.array(
        [
            float(np.real(m[0, 0])),
            float(np.real(m[1, 1])),
            float(np.real(m[2, 2])),
            float(np.real(m[0, 1])),
            float(np.imag(m[0, 1])),
            float(np.real(m[0, 2])),
            float(np.imag(m[0, 2])),
            float(np.real(m[1, 2])),
            float(np.imag(m[1, 2])),
        ],
        dtype=float,
    )


def herm_mat_from_vec(v: np.ndarray) -> np.ndarray:
    m = np.zeros((3, 3), dtype=complex)
    m[0, 0] = float(v[0])
    m[1, 1] = float(v[1])
    m[2, 2] = float(v[2])
    m[0, 1] = float(v[3]) + 1j * float(v[4])
    m[0, 2] = float(v[5]) + 1j * float(v[6])
    m[1, 2] = float(v[7]) + 1j * float(v[8])
    m[1, 0] = np.conjugate(m[0, 1])
    m[2, 0] = np.conjugate(m[0, 2])
    m[2, 1] = np.conjugate(m[1, 2])
    return m


def complex_from_oct(x: np.ndarray) -> complex:
    re = float(x[0])
    imag_sq = max(0.0, float(np.dot(x, x)) - re * re)
    sign_probe = float(np.dot(x[1:], np.arange(1, 8, dtype=float)))
    sign = -1.0 if sign_probe < 0.0 else 1.0
    return re + 1j * sign * math.sqrt(imag_sq)


def complex_from_j3_surrogate(rho: np.ndarray) -> np.ndarray:
    m = np.zeros((3, 3), dtype=complex)
    for idx in range(3):
        m[idx, idx] = float(rho[idx, idx, 0])
    m[0, 1] = complex_from_oct(rho[0, 1, :])
    m[0, 2] = complex_from_oct(rho[0, 2, :])
    m[1, 2] = complex_from_oct(rho[1, 2, :])
    m[1, 0] = np.conjugate(m[0, 1])
    m[2, 0] = np.conjugate(m[0, 2])
    m[2, 1] = np.conjugate(m[1, 2])
    return m


def c_jordan(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return 0.5 * (a @ b + b @ a)


def c_left_matrix(a: np.ndarray) -> np.ndarray:
    cols = []
    for idx in range(9):
        cols.append(herm_vec_from_mat(c_jordan(a, herm_mat_from_vec(basis_vec(9, idx)))))
    return np.column_stack(cols)


def c_derivation(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    la = c_left_matrix(a)
    lb = c_left_matrix(b)
    return la @ lb - lb @ la


def complex_pinch_reference_matrix() -> np.ndarray:
    out = np.zeros((9, 9), dtype=float)
    out[0, 0] = 1.0
    out[1, 1] = 1.0
    out[2, 2] = 1.0
    return out


def build_complex_surrogate_instrument(inst: dict[str, Any]) -> dict[str, Any]:
    p_ref = complex_pinch_reference_matrix()
    c_gens = []
    for gen in inst["generators"]:
        a = complex_from_j3_surrogate(gen["a"])
        b = complex_from_j3_surrogate(gen["b"])
        c_gens.append({"label": gen["label"], "D": c_derivation(a, b)})
    bmat = expm(FRAME_ROTATION_TIME * c_gens[0]["D"])
    b_inv = expm(-FRAME_ROTATION_TIME * c_gens[0]["D"])
    p_rot = bmat @ p_ref @ b_inv
    t_phi = np.zeros((9, 9), dtype=float)
    rows = []
    for weight, time, gen in zip(WEIGHTS, ROTATION_TIMES, c_gens):
        amat = expm(float(time) * gen["D"])
        ainv = expm(-float(time) * gen["D"])
        t_phi += float(weight) * (amat @ p_rot @ ainv)
        rows.append({"label": gen["label"], "time": float(time), "weight": float(weight), "D_norm": float(np.linalg.norm(gen["D"]))})
    return {"T_phi": t_phi, "T_pinch_ref": p_ref, "T_pinch_rotated": p_rot, "rows": rows}


def c_phi_elem(cinst: dict[str, Any], rho: np.ndarray) -> np.ndarray:
    return herm_mat_from_vec(cinst["T_phi"] @ herm_vec_from_mat(rho))


def c_fixed_point(cinst: dict[str, Any], start: np.ndarray) -> tuple[np.ndarray, dict[str, Any]]:
    rho = np.array(start, dtype=complex, copy=True)
    diffs = []
    for step in range(1000):
        nxt = c_phi_elem(cinst, rho)
        diff = float(np.linalg.norm(nxt - rho))
        diffs.append(diff)
        rho = nxt
        if diff < 2.0e-14 and step > 20:
            break
    return rho, {
        "iterations": len(diffs),
        "last_step_distance": float(diffs[-1]),
        "trace": float(np.real(np.trace(rho))),
        "min_eigenvalue": float(np.min(np.linalg.eigvalsh(rho))),
    }


def c_relative_entropy(rho: np.ndarray, sigma: np.ndarray) -> float:
    evals_r, vecs_r = np.linalg.eigh(rho)
    evals_s, vecs_s = np.linalg.eigh(sigma)
    evals_r = np.clip(np.real(evals_r), 0.0, None)
    evals_s = np.clip(np.real(evals_s), 1.0e-15, None)
    log_r = vecs_r @ np.diag([math.log(float(x)) if x > 0.0 else 0.0 for x in evals_r]) @ vecs_r.conj().T
    log_s = vecs_s @ np.diag([math.log(float(x)) for x in evals_s]) @ vecs_s.conj().T
    return float(np.real(np.trace(rho @ (log_r - log_s))))


def surrogate_gate(table: np.ndarray, inst: dict[str, Any], cinst: dict[str, Any], states: list[np.ndarray], sigma: np.ndarray) -> dict[str, Any]:
    sigma_c, sigma_c_report = c_fixed_point(cinst, complex_from_j3_surrogate(sigma))
    max_spectrum_diff = 0.0
    max_d_diff = 0.0
    rows = []
    for state_index, start in enumerate(states[: min(36, len(states))]):
        rho_o = np.array(start, dtype=float, copy=True)
        rho_c = complex_from_j3_surrogate(start)
        for step in range(FLOW_STEPS + 1):
            spec_o = spectral_values(table, rho_o)
            spec_c = np.sort(np.linalg.eigvalsh(rho_c))[::-1]
            spectrum_diff = float(np.linalg.norm(spec_o - spec_c))
            d_o = relative_entropy_full(table, rho_o, jordan_log_from_projectors(table, sigma)[0], "closed")
            d_c = c_relative_entropy(rho_c, sigma_c)
            d_diff = abs(d_o - d_c)
            max_spectrum_diff = max(max_spectrum_diff, spectrum_diff)
            max_d_diff = max(max_d_diff, d_diff)
            if len(rows) < 12 and (step in {0, 1, FLOW_STEPS} or spectrum_diff > SURROGATE_DIVERGENCE_FLOOR):
                rows.append(
                    {
                        "state_index": state_index,
                        "step": step,
                        "spectrum_diff": spectrum_diff,
                        "D_j3o": d_o,
                        "D_complex_surrogate": d_c,
                        "D_abs_diff": d_diff,
                    }
                )
            if step < FLOW_STEPS:
                rho_o = phi_elem(inst, rho_o)
                rho_c = c_phi_elem(cinst, rho_c)
    surrogate_reproduces = bool(max(max_spectrum_diff, max_d_diff) <= SURROGATE_DIVERGENCE_FLOOR)
    return {
        "surrogate_definition": "Herm3(C) state with same diagonal entries, same three off-diagonal block norms, and same three off-diagonal real parts as the J3(O) state",
        "surrogate_map": "same rotated-pinch ensemble built from the complex projections of the J3(O) derivation generators",
        "sampled_states": min(36, len(states)),
        "steps_per_state": FLOW_STEPS,
        "max_spectrum_diff": float(max_spectrum_diff),
        "max_D_value_diff": float(max_d_diff),
        "divergence_floor": SURROGATE_DIVERGENCE_FLOOR,
        "surrogate_reproduces": surrogate_reproduces,
        "pass": bool(not surrogate_reproduces),
        "complex_fixed_point": sigma_c_report,
        "sample_rows": rows,
    }


def dpi_sweep(table: np.ndarray, inst: dict[str, Any], states: list[np.ndarray], log_sigma: np.ndarray) -> dict[str, Any]:
    max_increase = -float("inf")
    min_delta = float("inf")
    violations = []
    witness_rows = []
    assoc_mins = []
    for state_index, start in enumerate(states):
        rho = np.array(start, dtype=float, copy=True)
        d_values = [relative_entropy_full(table, rho, log_sigma, "closed")]
        assoc_values = [associator_norm(table, rho)]
        spectra = [spectral_values(table, rho)]
        for step in range(FLOW_STEPS):
            nxt = phi_elem(inst, rho)
            d_values.append(relative_entropy_full(table, nxt, log_sigma, "closed"))
            assoc_values.append(associator_norm(table, nxt))
            spectra.append(spectral_values(table, nxt))
            delta = d_values[-1] - d_values[-2]
            max_increase = max(max_increase, float(delta))
            min_delta = min(min_delta, float(delta))
            if delta > DPI_TOL:
                violations.append(
                    {
                        "state_index": state_index,
                        "step": step,
                        "delta": float(delta),
                        "before": float(d_values[-2]),
                        "after": float(d_values[-1]),
                        "rho_before": rho,
                        "rho_after": nxt,
                        "d_values": d_values[:],
                        "spectra": spectra[:],
                    }
                )
            rho = nxt
        assoc_mins.append(min(assoc_values))
        if state_index < 10 or state_index >= len(states) - 4:
            witness_rows.append(
                {
                    "state_index": state_index,
                    "D_start": d_values[0],
                    "D_end": d_values[-1],
                    "max_step_increase": float(max(b - a for a, b in zip(d_values, d_values[1:]))),
                    "associator_trajectory_min": float(min(assoc_values)),
                    "associator_trajectory_max": float(max(assoc_values)),
                    "max_block_norm_start": float(max(block_norms(start))),
                }
            )
    assoc_pass_count = int(sum(x > ASSOCIATOR_TRAJECTORY_MIN_FLOOR for x in assoc_mins))
    return {
        "sample_count": len(states),
        "steps_per_state": FLOW_STEPS,
        "comparison": "D(Phi(rho)||sigma_fix) - D(rho||sigma_fix)",
        "relative_entropy_method": "full spectral-projector log(sigma_fix), never diagonal shadows",
        "violation_count": len(violations),
        "max_increase": float(max_increase),
        "most_negative_delta": float(min_delta),
        "dpi_holds_on_grid": bool(len(violations) == 0),
        "associator_gate": {
            "floor": ASSOCIATOR_TRAJECTORY_MIN_FLOOR,
            "trajectory_statistic": "min associator(x01,x02,x12) along each trajectory",
            "pass_count": assoc_pass_count,
            "sample_count": len(states),
            "fraction_above_floor": float(assoc_pass_count / len(states)),
            "trajectory_min_min": float(min(assoc_mins)),
            "trajectory_min_median": float(np.median(assoc_mins)),
            "trajectory_min_max": float(max(assoc_mins)),
            "pass": bool(assoc_pass_count == len(states)),
        },
        "witness_rows": witness_rows,
        "violations_raw": violations,
    }


def crosscheck_violations(table: np.ndarray, inst: dict[str, Any], log_sigma: np.ndarray, violations: list[dict[str, Any]]) -> dict[str, Any]:
    rows = []
    confirmed = []
    for idx, item in enumerate(violations[:12]):
        before_closed = relative_entropy_full(table, item["rho_before"], log_sigma, "closed")
        after_closed = relative_entropy_full(table, item["rho_after"], log_sigma, "closed")
        before_roots = relative_entropy_full(table, item["rho_before"], log_sigma, "numpy_roots")
        after_roots = relative_entropy_full(table, item["rho_after"], log_sigma, "numpy_roots")
        before_ld = np.longdouble(-j3.j3_trace(jprod(table, item["rho_before"], log_sigma)))
        after_ld = np.longdouble(-j3.j3_trace(jprod(table, item["rho_after"], log_sigma)))
        row = {
            "violation_index": idx,
            "state_index": item["state_index"],
            "step": item["step"],
            "delta_closed": float(after_closed - before_closed),
            "delta_numpy_roots": float(after_roots - before_roots),
            "longdouble_trace_term_delta": float(after_ld - before_ld),
            "precision_escalation": "numpy.longdouble trace-log-sigma term plus closed cubic vs numpy.roots cubic spectra",
            "confirmed": bool((after_closed - before_closed) > DPI_TOL and (after_roots - before_roots) > DPI_TOL),
        }
        rows.append(row)
        if row["confirmed"]:
            confirmed.append(row)
    return {
        "triggered": bool(violations),
        "checked_count": len(rows),
        "confirmed_count": len(confirmed),
        "rows": rows,
    }


def wrong_sigma_control(table: np.ndarray, inst: dict[str, Any], rng: np.random.Generator) -> dict[str, Any]:
    wrong_sigma, wrong_report = random_density_wide(rng, table, 0.22)
    log_wrong, wrong_log_report = jordan_log_from_projectors(table, wrong_sigma)
    before = relative_entropy_full(table, wrong_sigma, log_wrong, "closed")
    after_state = phi_elem(inst, wrong_sigma)
    after = relative_entropy_full(table, after_state, log_wrong, "closed")
    return {
        "meaning": "Use sigma_wrong as the reference even though Phi(sigma_wrong) != sigma_wrong; D(sigma_wrong||sigma_wrong)=0 must break under one Phi step.",
        "wrong_sigma_sampling": wrong_report,
        "wrong_sigma_log": wrong_log_report,
        "phi_wrong_sigma_distance": float(np.linalg.norm(after_state - wrong_sigma)),
        "before": before,
        "after": after,
        "delta": float(after - before),
        "breaks": bool(after - before > DPI_TOL),
    }


def classical_control(rng: np.random.Generator) -> dict[str, Any]:
    sigma = np.array([0.50, 0.31, 0.19], dtype=float)
    lam = 0.23

    def rel(p: np.ndarray) -> float:
        return float(sum(pi * (math.log(pi) - math.log(si)) for pi, si in zip(p, sigma) if pi > 0.0))

    def channel(p: np.ndarray) -> np.ndarray:
        return (1.0 - lam) * p + lam * sigma

    violations = 0
    max_increase = -float("inf")
    min_decrease = float("inf")
    rows = []
    for idx in range(192):
        p = rng.dirichlet(np.array([0.7, 1.2, 1.6]))
        delta = rel(channel(p)) - rel(p)
        max_increase = max(max_increase, float(delta))
        min_decrease = min(min_decrease, float(delta))
        if delta > DPI_TOL:
            violations += 1
        if idx < 6:
            rows.append({"sample": idx, "before": rel(p), "after": rel(channel(p)), "delta": float(delta)})
    return {
        "architecture": "non-identity classical reset-mixing channel K(p)=(1-lambda)p+lambda*sigma with fixed sigma",
        "lambda": lam,
        "sample_count": 192,
        "violation_count": violations,
        "max_increase": float(max_increase),
        "most_negative_delta": float(min_decrease),
        "non_vacuous": True,
        "zero_violations": bool(violations == 0),
        "sample_rows": rows,
    }


def automorphism_isometry_control(table: np.ndarray, inst: dict[str, Any], states: list[np.ndarray], sigma: np.ndarray) -> dict[str, Any]:
    auto = inst["automorphisms"][0]["A"]
    log_sigma, _ = jordan_log_from_projectors(table, sigma)
    moved_sigma = j3_elem_from_vec(auto @ j3_vec_from_elem(sigma))
    moved_log_sigma, _ = jordan_log_from_projectors(table, moved_sigma)
    max_diff = 0.0
    rows = []
    for idx, rho in enumerate(states[:24]):
        moved = j3_elem_from_vec(auto @ j3_vec_from_elem(rho))
        before = relative_entropy_full(table, rho, log_sigma, "closed")
        after = relative_entropy_full(table, moved, moved_log_sigma, "closed")
        diff = abs(after - before)
        max_diff = max(max_diff, float(diff))
        if idx < 6:
            rows.append({"state_index": idx, "before": before, "after": after, "abs_diff": diff})
    return {
        "definition": "automorphism-only control compares D(A rho || A sigma_fix) to D(rho || sigma_fix)",
        "max_relative_entropy_isometry_error": max_diff,
        "tolerance": AUTOMORPHISM_TOL,
        "pass": bool(max_diff <= AUTOMORPHISM_TOL),
        "sample_rows": rows,
    }


def instrument_valid(gates: dict[str, Any], controls: dict[str, Any]) -> bool:
    return bool(
        gates["linearity"]["pass"]
        and gates["trace_positivity"]["trace_preservation_pass"]
        and gates["trace_positivity"]["positivity_pass"]
        and gates["transfer_noncommutation"]["pass"]
        and gates["automorphism_integrity"]["pass"]
        and gates["fixed_point"]["pass"]
        and gates["associator_trajectory_min"]["pass"]
        and gates["associative_surrogate_fails"]["pass"]
        and controls["wrong_sigma"]["breaks"]
        and controls["automorphism_only_isometry"]["pass"]
        and controls["classical_contracting_channel"]["zero_violations"]
        and controls["classical_contracting_channel"]["non_vacuous"]
    )


def build_result() -> dict[str, Any]:
    rng = np.random.default_rng(SEED)
    table = j3.octonion_table()
    inst = build_octonion_instrument(table)
    sigma_fix, fixed_report = fixed_point_by_iteration(table, inst, np.random.default_rng(SEED + 1))
    log_sigma, log_report = jordan_log_from_projectors(table, sigma_fix)
    states, grid_report = sample_grid(rng, table, sigma_fix, log_sigma)
    cinst = build_complex_surrogate_instrument(inst)

    dpi = dpi_sweep(table, inst, states, log_sigma)
    gates: dict[str, Any] = {
        "linearity": linearity_gate(table, inst, np.random.default_rng(SEED + 10)),
        "trace_positivity": trace_positivity_gate(table, inst, states),
        "transfer_noncommutation": transfer_noncommutation_gate(inst),
        "automorphism_integrity": automorphism_gate(table, inst, states),
        "fixed_point": {
            **fixed_report,
            "pass": bool(fixed_report["fixed_point_residual"] <= 2.0e-10 and fixed_report["min_eigenvalue"] > 1.0e-8),
        },
        "associator_trajectory_min": dpi["associator_gate"],
        "associative_surrogate_fails": surrogate_gate(table, inst, cinst, states, sigma_fix),
    }
    crosscheck = crosscheck_violations(table, inst, log_sigma, dpi["violations_raw"])
    controls = {
        "wrong_sigma": wrong_sigma_control(table, inst, np.random.default_rng(SEED + 20)),
        "automorphism_only_isometry": automorphism_isometry_control(table, inst, states, sigma_fix),
        "classical_contracting_channel": classical_control(np.random.default_rng(SEED + 30)),
    }
    valid = instrument_valid(gates, controls)
    if not valid:
        verdict = "instrument_invalid"
        dpi_verdict = "not_reported"
    elif dpi["violation_count"] == 0:
        verdict = "dpi_holds_on_valid_instrument"
        dpi_verdict = verdict
    elif crosscheck["confirmed_count"] > 0:
        verdict = "dpi_violated_verified"
        dpi_verdict = verdict
    else:
        verdict = "instrument_invalid"
        dpi_verdict = "not_reported_unconfirmed_violation"

    serialized_violations = []
    if verdict == "dpi_violated_verified":
        for item in dpi["violations_raw"][:8]:
            serialized_violations.append(
                {
                    "state_index": item["state_index"],
                    "step": item["step"],
                    "delta": item["delta"],
                    "before": item["before"],
                    "after": item["after"],
                    "rho_before_vec": j3_vec_from_elem(item["rho_before"]),
                    "rho_after_vec": j3_vec_from_elem(item["rho_after"]),
                    "d_values_prefix": item["d_values"],
                    "spectra_prefix": item["spectra"],
                }
            )
    dpi_public = {k: v for k, v in dpi.items() if k != "violations_raw"}
    dpi_public["serialized_violation_trajectories"] = serialized_violations
    return {
        "schema": "codex_ratchet.jordan_dpi_probe_v4_result.v1",
        "sim_id": SIM_ID,
        "object_id": SIM_ID,
        "generated_at": dt.datetime.now(dt.UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "source_path": str(SOURCE_PATH),
        "result_path": str(RESULT_PATH),
        "classification": CLASSIFICATION,
        "promotion_allowed": PROMOTION_ALLOWED,
        "formal_admission_allowed": FORMAL_ADMISSION_ALLOWED,
        "sim_execution_kind": "classical",
        "sim_class": "jordan_dpi_valid_instrument_probe",
        "seed": SEED,
        "rng": "numpy.default_rng(0)",
        "TOOL_MANIFEST": TOOL_MANIFEST,
        "TOOL_INTEGRATION_DEPTH": TOOL_INTEGRATION_DEPTH,
        "tool_manifest": TOOL_MANIFEST,
        "tool_integration_depth": TOOL_INTEGRATION_DEPTH,
        "claim_ceiling": "Scratch diagnostic finite-grid evidence for one auditor-specified non-block-scalar J3(O) positive trace-preserving instrument; no theorem, no canonical admission, no bridge/axis/manifold claim.",
        "banned_modes_guard": {
            "block_scalar_peirce_damping": False,
            "tautological_max_statistic_associator_gate": False,
            "vacuous_identity_classical_control": False,
            "diagonal_shadow_relative_entropy_formula_for_main_claim": False,
            "decorative_sigma_reference": False,
            "associative_surrogate_reproduces_allowed": False,
            "hardcoded_verdict": False,
        },
        "map": {
            "formula": "Phi=sum_i w_i A_i Pinch_Fprime A_i^{-1}",
            "weights": [float(x) for x in WEIGHTS],
            "rotation_times": [float(x) for x in ROTATION_TIMES],
            "frame_rotation_time": FRAME_ROTATION_TIME,
            "generator_summaries": [
                {
                    "label": row["label"],
                    "D_norm": row["D_norm"],
                    "a_offdiag_norm": row["a_offdiag_norm"],
                    "b_offdiag_norm": row["b_offdiag_norm"],
                }
                for row in inst["generators"]
            ],
            "trace_preservation_reason": "automorphisms and Jordan-frame pinches preserve trace; fixed weights sum to one",
            "positivity_reason": "automorphisms preserve the positive cone and rotated-frame pinching is a Jordan-positive projection; convex combinations stay positive",
        },
        "sigma_fix": {
            "vector": j3_vec_from_elem(sigma_fix),
            "spectral_log": log_report,
        },
        "state_grid": grid_report,
        "gates": gates,
        "dpi_table": dpi_public,
        "violation_crosscheck": crosscheck,
        "controls": controls,
        "instrument_valid": valid,
        "dpi_verdict": dpi_verdict,
        "verdict": verdict,
        "all_pass": bool(verdict in {"dpi_holds_on_valid_instrument", "dpi_violated_verified"}),
        "promotion_status": "diagnostic_only",
        "eligible_consumers": [],
        "blocked_consumers": [
            "formal Jordan-DPI theorem",
            "canonical-by-process promotion",
            "Axis0, bridge, manifold, or physics admission",
            "any claim that octonionic DPI is settled beyond this finite-grid instrument",
        ],
    }


def print_summary(result: dict[str, Any]) -> None:
    print("JORDAN_DPI_PROBE_V4_SIM")
    print(f"seed={SEED} classification={CLASSIFICATION} promotion_allowed={PROMOTION_ALLOWED}")
    print("instrument: Phi=sum_i w_i A_i Pinch_Fprime A_i^{-1}; non-frame-aligned derivation automorphisms")
    gates = result["gates"]
    print("GATES")
    lin = gates["linearity"]
    print(f"  linearity: pass={lin['pass']} max_superposition_error={lin['max_superposition_error']:.3e} tol={lin['tolerance']:.1e}")
    tp = gates["trace_positivity"]
    print(
        "  trace/positivity: "
        f"trace_pass={tp['trace_preservation_pass']} max_trace_error={tp['max_trace_error']:.3e} "
        f"positivity_pass={tp['positivity_pass']} min_eigenvalue={tp['min_eigenvalue']:.6e}"
    )
    noncomm = gates["transfer_noncommutation"]
    print(
        "  transfer noncommutation: "
        f"pass={noncomm['pass']} op_norm={noncomm['operator_2_norm']:.6e} floor={noncomm['floor']:.1e} "
        f"diag_to_off={noncomm['diag_to_off_block_norm']:.6e} off_to_diag={noncomm['off_to_diag_block_norm']:.6e}"
    )
    auto = gates["automorphism_integrity"]
    print(
        "  automorphism integrity: "
        f"pass={auto['pass']} product_error={auto['max_product_preservation_error']:.3e} "
        f"spectrum_error={auto['max_spectrum_error']:.3e}"
    )
    fp = gates["fixed_point"]
    print(
        "  fixed point by iteration: "
        f"pass={fp['pass']} iterations={fp['iterations']} residual={fp['fixed_point_residual']:.3e} "
        f"min_eigenvalue={fp['min_eigenvalue']:.6e} block_norms={fp['block_norms']}"
    )
    assoc = gates["associator_trajectory_min"]
    print(
        "  associator trajectory-min: "
        f"pass={assoc['pass']} floor={assoc['floor']:.1e} fraction={assoc['fraction_above_floor']:.3f} "
        f"min_min={assoc['trajectory_min_min']:.6e}"
    )
    surr = gates["associative_surrogate_fails"]
    print(
        "  associative surrogate fails: "
        f"pass={surr['pass']} surrogate_reproduces={surr['surrogate_reproduces']} "
        f"max_spectrum_diff={surr['max_spectrum_diff']:.6e} max_D_diff={surr['max_D_value_diff']:.6e} "
        f"floor={surr['divergence_floor']:.1e}"
    )
    grid = result["state_grid"]
    print(
        "GRID"
        f" states={grid['sample_count']} max_block_norm={grid['max_observed_block_norm']:.6e} "
        f"D_range=[{grid['D_to_sigma_fix_min']:.6e}, {grid['D_to_sigma_fix_max']:.6e}] "
        f"initial_assoc_min={grid['min_initial_associator']:.6e}"
    )
    dpi = result["dpi_table"]
    print("DPI TABLE")
    print(
        f"  samples={dpi['sample_count']} steps={dpi['steps_per_state']} violations={dpi['violation_count']} "
        f"max_increase={dpi['max_increase']:.6e} most_negative_delta={dpi['most_negative_delta']:.6e} "
        f"dpi_holds_on_grid={dpi['dpi_holds_on_grid']}"
    )
    for row in dpi["witness_rows"][:8]:
        print(
            f"  row state={row['state_index']:02d} D_start={row['D_start']:.6e} D_end={row['D_end']:.6e} "
            f"max_step_increase={row['max_step_increase']:.6e} assoc_min={row['associator_trajectory_min']:.6e} "
            f"block_norm={row['max_block_norm_start']:.6e}"
        )
    controls = result["controls"]
    print("CONTROLS")
    print(
        f"  wrong_sigma_breaks={controls['wrong_sigma']['breaks']} "
        f"delta={controls['wrong_sigma']['delta']:.6e} phi_wrong_sigma_distance={controls['wrong_sigma']['phi_wrong_sigma_distance']:.6e}"
    )
    print(
        f"  automorphism_only_isometry_pass={controls['automorphism_only_isometry']['pass']} "
        f"max_error={controls['automorphism_only_isometry']['max_relative_entropy_isometry_error']:.3e}"
    )
    print(
        f"  classical_nonidentity_contracting_zero_violations={controls['classical_contracting_channel']['zero_violations']} "
        f"max_increase={controls['classical_contracting_channel']['max_increase']:.6e}"
    )
    xcheck = result["violation_crosscheck"]
    print(
        "VIOLATION CROSSCHECK "
        f"triggered={xcheck['triggered']} checked={xcheck['checked_count']} confirmed={xcheck['confirmed_count']}"
    )
    print(f"instrument_valid={result['instrument_valid']} dpi_verdict={result['dpi_verdict']}")
    print(f"verdict={result['verdict']} all_pass={result['all_pass']}")
    print(f"wrote: {RESULT_PATH}")


def main() -> int:
    result = build_result()
    RESULT_PATH.write_text(json.dumps(clean(result), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print_summary(result)
    return 0 if result["all_pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
