"""Capability names used by the visualization replay contract."""

BASE_POINT = "base_point"
FRAME = "frame"
TRANSPORT_PATH = "transport_path"
HOLONOMY = "holonomy"
S3_STATE = "s3_state"
FIBER_PHASE = "fiber_phase"
FIBER_SAMPLES = "fiber_samples"
MESH_GEOMETRY = "mesh_geometry"
CHART_PATCH = "chart_patch"
SEAM_MARKERS = "seam_markers"
CELL_GEOMETRY = "cell_geometry"
TRANSITION_META = "transition_meta"

TRANSPORT_CAPABILITIES = [BASE_POINT, FRAME, TRANSPORT_PATH, HOLONOMY]
HOPF_CAPABILITIES = [BASE_POINT, FRAME, TRANSPORT_PATH, S3_STATE, FIBER_PHASE, FIBER_SAMPLES, MESH_GEOMETRY]
ATLAS_CAPABILITIES = [BASE_POINT, FRAME, MESH_GEOMETRY, CELL_GEOMETRY, CHART_PATCH, SEAM_MARKERS, TRANSITION_META]
