name = "LeanMicroCoreV0"
defaultTargets = ["LeanMicroCoreV0"]

[[require]]
name = "mathlib"
path = "/Users/joshuaeisenhart/GitHub/physlib/.lake/packages/mathlib"

[[lean_lib]]
name = "LeanMicroCoreV0"
