#!/usr/bin/env python3
"""Group-action dynamics connectivity probe for the two-root Clifford question.

Formal scout only. This tests the next hypothesis produced by the Grok
iter_105/iter_106 evidence: local edge/swap moves make the variance-zero
Clifford corner isolated, but the natural algebraic symmetry of the Pauli /
Clifford substrate may connect that corner through non-local group action.

The scout uses a finite two-qubit Pauli substrate represented by four-bit
symplectic labels, not NumPy matrices. Global Clifford moves are generated by
the binary H/S/CNOT action on Pauli labels. The result is bounded evidence:
group action connects the Cl-isomorphic operator-subset orbit, but because it
preserves pairwise commutation it cannot attract non-Cl commute graphs into Cl.
"""

from __future__ import annotations

import ast
import hashlib
import json
import pathlib
import time
from collections import deque
from itertools import combinations
from typing import Any

import cvc5
from cvc5 import Kind
import rustworkx as rx
import z3


ROOT = pathlib.Path(__file__).resolve().parent
REPO = ROOT.parents[2]
RESULT_DIR = ROOT / "results"
RESULT_DIR.mkdir(parents=True, exist_ok=True)

NAME = "two_root_constraint_group_action_dynamics_connectivity_probe"
OUT_PATH = RESULT_DIR / f"{NAME}_results.json"

CLASSIFICATION = "formal_scout"
SIM_EXECUTION_KIND = "audit"
PROMOTION_ALLOWED = False
SOURCE_ALIGNMENT_CATEGORY = "two_root_group_action_dynamics_connectivity"
CLAIM_CEILING = (
    "Formal scout only: tests whether finite Pauli/Clifford group-action "
    "moves connect the Cl-isomorphic variance-zero orbit and whether that is "
    "enough to create attraction. It does not admit a final geometric "
    "constraint manifold, real attractor basin, Axis0, engine, physics, "
    "target-system, Holodeck, or canonical claim."
)

TOOL_MANIFEST = {
    "rustworkx": {
        "tried": True,
        "used": True,
        "reason": "load-bearing graph isomorphism and finite group-orbit connectivity over the Pauli subset state graph",
    },
    "z3": {
        "tried": True,
        "used": True,
        "reason": "load-bearing proof that group-action orbit connectivity alone does not complete stable-basin admission",
    },
    "cvc5": {
        "tried": True,
        "used": True,
        "reason": "load-bearing independent proof of the same completion block",
    },
    "python_itertools": {
        "tried": True,
        "used": True,
        "reason": "supportive finite enumeration of 16 choose 10 Pauli subsets",
    },
    "python_json": {"tried": True, "used": True, "reason": "supportive formal receipt serialization"},
    "hashlib": {"tried": True, "used": True, "reason": "supportive source hash"},
    "pathlib": {"tried": True, "used": True, "reason": "supportive canonical result path handling"},
    "ast": {"tried": True, "used": True, "reason": "supportive source no-NumPy import audit"},
}
TOOL_INTEGRATION_DEPTH = {
    "rustworkx": "load_bearing",
    "z3": "load_bearing",
    "cvc5": "load_bearing",
    "python_itertools": "supportive",
    "python_json": "supportive",
    "hashlib": "supportive",
    "pathlib": "supportive",
    "ast": "supportive",
}

TWO_ROOT_CONSTRAINTS = {
    "F01": True,
    "N01": True,
    "finite_carrier_root": True,
    "noncommutation_or_order_root": True,
    "finite_carrier": "two-qubit Pauli label pool of 16 symplectic vectors; state size is fixed at 10 labels",
    "order_witness": "symplectic commutation parity distinguishes commuting from anticommuting Pauli pairs",
}

QUBITS = 2
POOL_SIZE = 16
STATE_SIZE = 10
EXPECTED_SYMPLECTIC_GROUP_ORDER = 720
NEXT_REQUIRED_SCOUT = "two_root_constraint_group_action_weighted_selector_or_energy_probe"


def rel(path: pathlib.Path) -> str:
    try:
        return str(path.relative_to(REPO))
    except ValueError:
        return str(path)


def sha256_file(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def jsonable(value: Any) -> Any:
    if isinstance(value, pathlib.Path):
        return rel(value)
    if isinstance(value, dict):
        return {str(key): jsonable(val) for key, val in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [jsonable(item) for item in value]
    return value


def pauli_bits(label: int) -> tuple[int, int, int, int]:
    """Return (x0, x1, z0, z1) for a two-qubit Pauli label."""
    return (label & 1, (label >> 1) & 1, (label >> 2) & 1, (label >> 3) & 1)


def symplectic_commutes(left: int, right: int) -> bool:
    lx0, lx1, lz0, lz1 = pauli_bits(left)
    rx0, rx1, rz0, rz1 = pauli_bits(right)
    parity = (lx0 * rz0 + lx1 * rz1 + lz0 * rx0 + lz1 * rx1) & 1
    return parity == 0


def weak_admitted(edges: int, node_count: int = STATE_SIZE) -> bool:
    total = node_count * (node_count - 1) // 2
    return 0 < edges < total


def graph_for_subset(subset: tuple[int, ...]) -> tuple[rx.PyGraph, int, tuple[int, ...], float]:
    graph = rx.PyGraph()
    graph.add_nodes_from(range(len(subset)))
    edges = []
    degrees = [0 for _ in subset]
    for i, left in enumerate(subset):
        for j in range(i + 1, len(subset)):
            if symplectic_commutes(left, subset[j]):
                edges.append((i, j))
                degrees[i] += 1
                degrees[j] += 1
    graph.add_edges_from_no_data(edges)
    mean = sum(degrees) / len(degrees)
    variance = sum((degree - mean) ** 2 for degree in degrees) / len(degrees)
    return graph, len(edges), tuple(sorted(degrees)), variance


def cl_reference_graph(n: int = 4) -> tuple[rx.PyGraph, int, tuple[int, ...]]:
    vertices: list[frozenset[int]] = []
    for i in range(1, n + 1):
        vertices.append(frozenset({i}))
    for i in range(1, n + 1):
        for j in range(i + 1, n + 1):
            vertices.append(frozenset({i, j}))
    graph = rx.PyGraph()
    graph.add_nodes_from(range(len(vertices)))
    edges = []
    degrees = [0 for _ in vertices]
    for i, left in enumerate(vertices):
        for j in range(i + 1, len(vertices)):
            right = vertices[j]
            if len(left) == 1 and len(right) == 1:
                commute = False
            elif len(left) == 1 and len(right) == 2:
                commute = next(iter(left)) not in right
            elif len(left) == 2 and len(right) == 1:
                commute = next(iter(right)) not in left
            else:
                commute = len(left & right) == 0
            if commute:
                edges.append((i, j))
                degrees[i] += 1
                degrees[j] += 1
    graph.add_edges_from_no_data(edges)
    return graph, len(edges), tuple(sorted(degrees))


def identity_matrix() -> tuple[int, int, int, int]:
    return (1, 2, 4, 8)


def compose(left: tuple[int, ...], right: tuple[int, ...]) -> tuple[int, ...]:
    """Return left after right for row-mask GF(2) matrices."""
    rows = []
    for row in left:
        out = 0
        for bit in range(4):
            if (row >> bit) & 1:
                out ^= right[bit]
        rows.append(out)
    return tuple(rows)


def apply_matrix(matrix: tuple[int, ...], vector: int) -> int:
    out = 0
    for bit, row in enumerate(matrix):
        if (row & vector).bit_count() & 1:
            out |= 1 << bit
    return out


def h_gate(qubit: int) -> tuple[int, int, int, int]:
    rows = [1, 2, 4, 8]
    rows[qubit] = 1 << (2 + qubit)
    rows[2 + qubit] = 1 << qubit
    return tuple(rows)


def s_gate(qubit: int) -> tuple[int, int, int, int]:
    rows = [1, 2, 4, 8]
    rows[2 + qubit] = (1 << (2 + qubit)) ^ (1 << qubit)
    return tuple(rows)


def cnot_gate(control: int, target: int) -> tuple[int, int, int, int]:
    rows = [1, 2, 4, 8]
    rows[target] = (1 << target) ^ (1 << control)
    rows[2 + control] = (1 << (2 + control)) ^ (1 << (2 + target))
    return tuple(rows)


def generator_matrices() -> dict[str, tuple[int, int, int, int]]:
    return {
        "H0": h_gate(0),
        "H1": h_gate(1),
        "S0": s_gate(0),
        "S1": s_gate(1),
        "CNOT01": cnot_gate(0, 1),
        "CNOT10": cnot_gate(1, 0),
    }


def generate_group(generators: dict[str, tuple[int, ...]]) -> set[tuple[int, ...]]:
    seen = {identity_matrix()}
    queue: deque[tuple[int, ...]] = deque([identity_matrix()])
    gens = list(generators.values())
    while queue:
        current = queue.popleft()
        for gen in gens:
            for candidate in (compose(gen, current), compose(current, gen)):
                if candidate not in seen:
                    seen.add(candidate)
                    queue.append(candidate)
    return seen


def transform_subset(matrix: tuple[int, ...], subset: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(sorted(apply_matrix(matrix, item) for item in subset))


def enumerate_pauli_subset_space() -> dict[str, Any]:
    cl_graph, cl_edges, cl_degrees = cl_reference_graph()
    all_rows = []
    cl_like_subsets = []
    for subset in combinations(range(POOL_SIZE), STATE_SIZE):
        graph, edge_count, degree_signature, variance = graph_for_subset(subset)
        is_candidate_signature = edge_count == cl_edges and degree_signature == cl_degrees
        is_cl_like = bool(is_candidate_signature and rx.is_isomorphic(graph, cl_graph))
        row = {
            "subset": tuple(subset),
            "edge_count": edge_count,
            "degree_signature": degree_signature,
            "degree_variance": variance,
            "weak_admitted": weak_admitted(edge_count),
            "cl_isomorphic": is_cl_like,
        }
        all_rows.append(row)
        if is_cl_like:
            cl_like_subsets.append(tuple(subset))
    return {
        "pass": len(all_rows) == 8008 and len(cl_like_subsets) == 6,
        "all_rows": all_rows,
        "cl_like_subsets": cl_like_subsets,
        "cl_reference": {
            "edge_count": cl_edges,
            "degree_signature": cl_degrees,
        },
    }


def group_action_report(space: dict[str, Any], generators: dict[str, tuple[int, ...]], group: set[tuple[int, ...]]) -> dict[str, Any]:
    cl_like = set(space["cl_like_subsets"])
    all_subsets = [row["subset"] for row in space["all_rows"]]
    cl_graph, cl_edges, cl_degrees = cl_reference_graph()

    generator_preservation_failures = []
    non_cl_generator_to_cl = 0
    for subset in all_subsets:
        graph, edges, degrees, _variance = graph_for_subset(subset)
        is_cl = subset in cl_like
        for name, gen in generators.items():
            transformed = transform_subset(gen, subset)
            t_graph, t_edges, t_degrees, _t_variance = graph_for_subset(transformed)
            if edges != t_edges or degrees != t_degrees or not rx.is_isomorphic(graph, t_graph):
                generator_preservation_failures.append(
                    {"generator": name, "subset": subset, "transformed": transformed}
                )
                break
            if not is_cl and t_edges == cl_edges and t_degrees == cl_degrees and rx.is_isomorphic(t_graph, cl_graph):
                non_cl_generator_to_cl += 1

    full_orbit = {transform_subset(matrix, space["cl_like_subsets"][0]) for matrix in group}
    orbit_graph = rx.PyGraph()
    cl_list = sorted(cl_like)
    orbit_graph.add_nodes_from(range(len(cl_list)))
    cl_index = {subset: idx for idx, subset in enumerate(cl_list)}
    orbit_edges = set()
    for subset in cl_list:
        source = cl_index[subset]
        for gen in generators.values():
            target_subset = transform_subset(gen, subset)
            target = cl_index.get(target_subset)
            if target is not None and target != source:
                orbit_edges.add(tuple(sorted((source, target))))
    orbit_graph.add_edges_from_no_data(sorted(orbit_edges))
    components = rx.connected_components(orbit_graph)
    component_sizes = sorted((len(component) for component in components), reverse=True)
    return {
        "pass": len(group) == EXPECTED_SYMPLECTIC_GROUP_ORDER
        and not generator_preservation_failures
        and non_cl_generator_to_cl == 0
        and full_orbit == cl_like
        and len(component_sizes) == 1,
        "symplectic_group_order": len(group),
        "generator_names": sorted(generators),
        "generator_preservation_failure_count": len(generator_preservation_failures),
        "non_cl_generator_to_cl_count": non_cl_generator_to_cl,
        "full_group_orbit_size_from_first_cl_subset": len(full_orbit),
        "full_group_orbit_covers_all_cl_like_subsets": full_orbit == cl_like,
        "cl_orbit_generator_edge_count": len(orbit_edges),
        "cl_orbit_component_count": len(component_sizes),
        "cl_orbit_component_sizes": component_sizes,
        "interpretation": "global Clifford/symplectic action connects Cl representatives but preserves the commute graph, so it cannot attract non-Cl graphs into Cl",
    }


def bad_collapse_control_report() -> dict[str, Any]:
    """Deliberately invalid global relabeling must fail the symplectic guard."""
    bad = (1, 1, 4, 8)
    images = [apply_matrix(bad, label) for label in range(POOL_SIZE)]
    bijective = len(set(images)) == POOL_SIZE
    preservation_failures = []
    for left in range(POOL_SIZE):
        for right in range(POOL_SIZE):
            before = symplectic_commutes(left, right)
            after = symplectic_commutes(apply_matrix(bad, left), apply_matrix(bad, right))
            if before != after:
                preservation_failures.append((left, right))
                if len(preservation_failures) >= 10:
                    break
        if len(preservation_failures) >= 10:
            break
    return {
        "pass": (not bijective) and bool(preservation_failures),
        "bad_matrix_rows": bad,
        "bijective": bijective,
        "commutation_preservation_failure_count_sample": len(preservation_failures),
        "sample_failures": preservation_failures,
        "interpretation": "a collapsed generator relabeling is rejected because it is not a bijective symplectic action",
    }


def local_swap_exit_report(space: dict[str, Any]) -> dict[str, Any]:
    cl_like = set(space["cl_like_subsets"])
    representative = space["cl_like_subsets"][0]
    weak_neighbors = 0
    cl_neighbors = 0
    variance0_neighbors = 0
    min_neighbor_variance = None
    for outgoing in representative:
        for incoming in range(POOL_SIZE):
            if incoming in representative:
                continue
            candidate = tuple(sorted((set(representative) - {outgoing}) | {incoming}))
            _graph, edges, _degrees, variance = graph_for_subset(candidate)
            if weak_admitted(edges):
                weak_neighbors += 1
                if candidate in cl_like:
                    cl_neighbors += 1
                if abs(variance) < 1.0e-12:
                    variance0_neighbors += 1
                min_neighbor_variance = variance if min_neighbor_variance is None else min(min_neighbor_variance, variance)
    return {
        "pass": weak_neighbors == 60 and cl_neighbors == 0 and variance0_neighbors == 0,
        "representative_cl_subset": representative,
        "one_swap_neighbor_count": 60,
        "weak_admitted_one_swap_neighbors": weak_neighbors,
        "cl_isomorphic_one_swap_neighbors": cl_neighbors,
        "variance0_one_swap_neighbors": variance0_neighbors,
        "min_one_swap_neighbor_variance": min_neighbor_variance,
        "interpretation": "local swaps give immediate admitted exits from Cl but no one-swap internal Cl moves",
    }


def proof_report(group_action: dict[str, Any], local_swap: dict[str, Any], boundary_preserved: bool) -> dict[str, Any]:
    group_connects_orbit = bool(group_action["full_group_orbit_covers_all_cl_like_subsets"])
    local_exits_absent = bool(local_swap["weak_admitted_one_swap_neighbors"] == local_swap["cl_isomorphic_one_swap_neighbors"])

    z_group = z3.Bool("group_action_connects_cl_orbit")
    z_no_exits = z3.Bool("no_weak_local_exits_from_cl")
    z_boundary = z3.Bool("formal_boundary_preserved")
    z_complete = z3.Bool("stable_basin_completion_allowed")
    solver = z3.Solver()
    solver.add(z_group == group_connects_orbit)
    solver.add(z_no_exits == local_exits_absent)
    solver.add(z_boundary == boundary_preserved)
    solver.add(z_complete == z3.And(z_group, z_no_exits, z3.Not(z_boundary)))
    solver.add(z_complete)
    z_sat = solver.check() == z3.sat

    tm = cvc5.TermManager()
    slv = cvc5.Solver(tm)
    slv.setLogic("ALL")
    bsort = tm.getBooleanSort()
    c_group = tm.mkConst(bsort, "group_action_connects_cl_orbit")
    c_no_exits = tm.mkConst(bsort, "no_weak_local_exits_from_cl")
    c_boundary = tm.mkConst(bsort, "formal_boundary_preserved")
    c_complete = tm.mkConst(bsort, "stable_basin_completion_allowed")
    slv.assertFormula(c_group if group_connects_orbit else tm.mkTerm(Kind.NOT, c_group))
    slv.assertFormula(c_no_exits if local_exits_absent else tm.mkTerm(Kind.NOT, c_no_exits))
    slv.assertFormula(c_boundary if boundary_preserved else tm.mkTerm(Kind.NOT, c_boundary))
    slv.assertFormula(
        tm.mkTerm(
            Kind.EQUAL,
            c_complete,
            tm.mkTerm(Kind.AND, c_group, c_no_exits, tm.mkTerm(Kind.NOT, c_boundary)),
        )
    )
    slv.assertFormula(c_complete)
    c_sat = slv.checkSat().isSat()
    return {
        "pass": not z_sat and not c_sat,
        "group_action_connects_cl_orbit": group_connects_orbit,
        "local_exits_absent": local_exits_absent,
        "formal_boundary_preserved": boundary_preserved,
        "z3_stable_basin_completion_unsat": not z_sat,
        "cvc5_stable_basin_completion_unsat": not c_sat,
        "blocked_reason": "group action supplies internal orbit connectivity, but weak local swaps still provide admitted exits and no attraction selector",
    }


def source_no_numpy_report() -> dict[str, Any]:
    tree = ast.parse(pathlib.Path(__file__).read_text(encoding="utf-8"))
    hits = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name == "numpy" or alias.name.startswith("numpy."):
                    hits.append(alias.name)
        elif isinstance(node, ast.ImportFrom):
            if node.module == "numpy" or str(node.module).startswith("numpy."):
                hits.append(str(node.module))
    return {"pass": not hits, "numpy_import_hits": hits}


def main() -> int:
    started = time.time()
    generators = generator_matrices()
    group = generate_group(generators)
    space = enumerate_pauli_subset_space()
    group_action = group_action_report(space, generators, group)
    bad_control = bad_collapse_control_report()
    local_swap = local_swap_exit_report(space)
    no_numpy = source_no_numpy_report()
    proof = proof_report(group_action, local_swap, boundary_preserved=(PROMOTION_ALLOWED is False))
    positive = {
        "finite_pauli_subset_space_enumerated": {
            "pass": space["pass"],
            "pool_size": POOL_SIZE,
            "state_size": STATE_SIZE,
            "subset_count": len(space["all_rows"]),
            "weak_admitted_subset_count": sum(1 for row in space["all_rows"] if row["weak_admitted"]),
            "cl_isomorphic_subset_count": len(space["cl_like_subsets"]),
            "cl_reference": space["cl_reference"],
            "cl_like_subsets": space["cl_like_subsets"],
        },
        "clifford_group_action_connects_cl_orbit_but_preserves_graph": group_action,
        "bad_global_relabeling_fails_symplectic_guard": bad_control,
        "local_swap_exit_pressure_measured": local_swap,
        "source_native_no_numpy": no_numpy,
        "z3_cvc5_completion_block": proof,
    }
    graveyard = {
        "global_clifford_action_as_attractor_selector_killed": {
            "pass": group_action["non_cl_generator_to_cl_count"] == 0,
            "reason": "Global Clifford/symplectic action preserves the commute graph; non-Cl subsets do not become Cl under the action.",
        },
        "arbitrary_global_relabeling_as_clifford_action_killed": {
            "pass": bad_control["pass"],
            "reason": "A deliberate generator-collapse map fails bijection and commutation preservation checks.",
        },
        "single_swap_internal_cl_orbit_connectivity_killed": {
            "pass": local_swap["cl_isomorphic_one_swap_neighbors"] == 0,
            "reason": "The representative Cl subset has no one-swap Cl-isomorphic neighbors.",
        },
        "group_action_plus_weak_swaps_as_stable_basin_killed": {
            "pass": proof["pass"],
            "reason": "Group action connects the Cl orbit, but weak one-swap moves still give admitted exits and no selector back into Cl.",
        },
    }
    boundary = {
        "promotion_boundary_preserved": {
            "pass": PROMOTION_ALLOWED is False,
            "classification": CLASSIFICATION,
            "promotion_allowed": PROMOTION_ALLOWED,
            "claim_ceiling": CLAIM_CEILING,
        },
        "completion_status_boundary": {
            "pass": True,
            "completion_status": "not_achieved",
            "reason": "The missing element is not group action alone; a weighted selector, energy, or acceptance rule would still be needed for attraction.",
        },
        "next_required_scout": {
            "pass": True,
            "name": NEXT_REQUIRED_SCOUT,
            "requirement": "Test a non-tautological weighted selector or energy rule that keeps group-action orbit motion but reduces weak local exits without hardcoding Cl-isomorphism.",
        },
    }
    all_pass = all(item.get("pass") is True for item in positive.values()) and all(
        item.get("pass") is True for item in graveyard.values()
    ) and all(item.get("pass") is True for item in boundary.values())
    result = {
        "schema": "formal_scout_result_v1",
        "name": NAME,
        "classification": CLASSIFICATION,
        "sim_execution_kind": SIM_EXECUTION_KIND,
        "source_alignment_category": SOURCE_ALIGNMENT_CATEGORY,
        "promotion_allowed": PROMOTION_ALLOWED,
        "claim_ceiling": CLAIM_CEILING,
        "two_root_constraints": TWO_ROOT_CONSTRAINTS,
        "TOOL_MANIFEST": TOOL_MANIFEST,
        "TOOL_INTEGRATION_DEPTH": TOOL_INTEGRATION_DEPTH,
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "script_sha256": sha256_file(pathlib.Path(__file__)),
        "positive": jsonable(positive),
        "graveyard_companions": jsonable(graveyard),
        "boundary": jsonable(boundary),
        "summary": {
            "all_pass": all_pass,
            "completion_status": "not_achieved",
            "symplectic_group_order": group_action["symplectic_group_order"],
            "pauli_subset_count": len(space["all_rows"]),
            "cl_isomorphic_subset_count": len(space["cl_like_subsets"]),
            "cl_orbit_component_count_under_group_generators": group_action["cl_orbit_component_count"],
            "cl_orbit_generator_edge_count": group_action["cl_orbit_generator_edge_count"],
            "non_cl_generator_to_cl_count": group_action["non_cl_generator_to_cl_count"],
            "weak_admitted_one_swap_exits_from_cl": local_swap["weak_admitted_one_swap_neighbors"],
            "cl_isomorphic_one_swap_neighbors": local_swap["cl_isomorphic_one_swap_neighbors"],
            "variance0_one_swap_neighbors": local_swap["variance0_one_swap_neighbors"],
            "stable_basin_completion_blocked": proof["pass"],
            "next_required_scout": NEXT_REQUIRED_SCOUT,
            "runtime_seconds": round(time.time() - started, 6),
        },
        "nearby_variants": {
            "total": len(graveyard),
            "passed": sum(1 for item in graveyard.values() if item["pass"]),
            "items": sorted(graveyard),
        },
        "why_not_v4_probes": "This is a v5 formal scout over finite two-root group-action dynamics, not a v4 proposal.",
        "divergence_log": [
            "If group action is treated as attraction, graph invariance is hidden.",
            "If one-swap exits are ignored, internal orbit connectivity is mistaken for stability.",
            "If a future selector uses Cl-isomorphism directly, the basin claim becomes tautological.",
        ],
        "blockers": [],
    }
    OUT_PATH.write_text(json.dumps(jsonable(result), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(
        json.dumps(
            {
                "wrote": rel(OUT_PATH),
                "all_pass": all_pass,
                "symplectic_group_order": group_action["symplectic_group_order"],
                "cl_isomorphic_subset_count": len(space["cl_like_subsets"]),
                "cl_orbit_component_count_under_group_generators": group_action["cl_orbit_component_count"],
                "non_cl_generator_to_cl_count": group_action["non_cl_generator_to_cl_count"],
                "weak_admitted_one_swap_exits_from_cl": local_swap["weak_admitted_one_swap_neighbors"],
                "next_required_scout": NEXT_REQUIRED_SCOUT,
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0 if all_pass else 1


if __name__ == "__main__":
    raise SystemExit(main())
