"""phase_34_classifier_robustness.py — does classify_state generalize?

Phase 33 showed 100% in-distribution accuracy. That's near-tautological — the
test states were small perturbations of points already on the reference paths.
Phase 34 stress-tests three real questions:

1. PATH THICKNESS. At perturbation scale 0.05, 0.20, 0.50, what's the accuracy
   curve? If paths are geometrically real, accuracy should degrade gracefully
   (stay > 70% at 0.20, > 55% at 0.50). If paths are razor-thin lines,
   accuracy will crash to ~50% by 0.20.

2. UNBIASEDNESS ON OOD STATES. On 60 Haar-random density matrices (states
   generated by a process the architecture didn't see), the A/B split should
   be roughly balanced (40/20 ≤ split ≤ 30/30 — i.e., neither label dominates
   beyond 67%). A biased classifier just labels everything one way.

3. PERTURBATION CONSISTENCY. For 10 Haar-random states, perturb each 8 ways
   at scale 0.05. The classifier should give the same label across perturbations
   ≥ 75% of the time (otherwise it's reading noise, not state structure).

This is the genuine generalization test that Phase 33 deferred.
"""
import numpy as np


def _to_arr(obj):
    if hasattr(obj, "full"):
        return np.asarray(obj.full())
    if hasattr(obj, "numpy"):
        return obj.detach().cpu().numpy() if hasattr(obj, "detach") else obj.numpy()
    return np.asarray(obj)


def _haar_random_density(rng, n=16):
    """Generate a Haar-random pure-state density matrix on a 16-dim Hilbert."""
    psi = rng.normal(size=n) + 1j * rng.normal(size=n)
    psi /= np.linalg.norm(psi)
    return np.outer(psi, psi.conj())


def _perturb(rho_arr, rng, scale):
    A = rng.normal(scale=scale, size=rho_arr.shape) + 1j * rng.normal(scale=scale, size=rho_arr.shape)
    H = (A + A.conj().T) / 2.0
    from scipy.linalg import expm
    U = expm(-1j * scale * H)
    out = U @ rho_arr @ U.conj().T
    out /= np.trace(out).real
    return out


def run(candidate):
    failures = []
    metrics = {}

    if not hasattr(candidate, "classify_state") or not hasattr(candidate, "engine_stage"):
        return {"pass": False,
                "failures": [{"check": "prerequisites", "msg": "needs classify_state + engine_stage"}],
                "metrics": metrics}

    try:
        import qutip as qt
        QDIMS = [[2, 2, 2, 2], [2, 2, 2, 2]]
        psi_anchor = qt.tensor(
            (qt.basis(2, 0) + 0.6 * qt.basis(2, 1)).unit(),
            (qt.basis(2, 0) + 0.4j * qt.basis(2, 1)).unit(),
            qt.basis(2, 0), qt.basis(2, 0))
        rho_anchor = qt.ket2dm(psi_anchor)
    except Exception as e:
        return {"pass": False, "failures": [{"check": "setup", "msg": str(e)[:160]}], "metrics": metrics}

    rng = np.random.default_rng(20260514)

    # ===== Test 1: path thickness via perturbation scale =====
    thickness_results = {}
    for pert_scale in (0.05, 0.20, 0.50):
        correct = 0
        total = 0
        for engine in ("A", "B"):
            for trial in range(10):
                s = trial % 8
                sub = trial % 4
                try:
                    r = candidate.engine_stage(engine, s, sub, rho_anchor)
                    out = r.get("output_rho_qt") if isinstance(r, dict) else r
                    path_arr = _to_arr(out)
                except Exception:
                    continue
                perturbed = _perturb(path_arr, rng, pert_scale)
                rho_test = qt.Qobj(perturbed, dims=QDIMS)
                try:
                    res = candidate.classify_state(rho_test)
                    if res.get("engine_label") == engine:
                        correct += 1
                    total += 1
                except Exception as e:
                    failures.append({"check": f"thickness_{pert_scale}", "msg": str(e)[:120]})
        if total > 0:
            thickness_results[pert_scale] = correct / total
    metrics["thickness_accuracy_by_scale"] = thickness_results

    # Thresholds chosen to require graceful degradation, not crash
    threshold_map = {0.05: 0.90, 0.20: 0.70, 0.50: 0.55}
    for scale, threshold in threshold_map.items():
        if scale in thickness_results and thickness_results[scale] < threshold:
            failures.append({
                "check": f"thickness_at_{scale}",
                "msg": f"accuracy at perturbation scale {scale} = {thickness_results[scale]:.2%} < "
                       f"{threshold:.0%} threshold. Trajectory paths too thin — classifier reads "
                       f"noise once perturbation exceeds {scale}.",
            })

    # ===== Test 2: unbiasedness on OOD Haar-random states =====
    haar_labels = []
    for _ in range(60):
        rho_arr = _haar_random_density(rng)
        rho_q = qt.Qobj(rho_arr, dims=QDIMS)
        try:
            res = candidate.classify_state(rho_q)
            haar_labels.append(res.get("engine_label"))
        except Exception as e:
            failures.append({"check": "haar_call", "msg": str(e)[:120]})
    a_count = haar_labels.count("A")
    b_count = haar_labels.count("B")
    metrics["haar_split"] = {"A": a_count, "B": b_count, "n": len(haar_labels)}
    metrics["haar_dominant_fraction"] = max(a_count, b_count) / max(len(haar_labels), 1)
    if max(a_count, b_count) / max(len(haar_labels), 1) > 0.85:
        failures.append({
            "check": "haar_unbiased",
            "msg": f"Haar split: A={a_count}/{len(haar_labels)}, B={b_count}/{len(haar_labels)}. "
                   f"Dominant fraction {max(a_count,b_count)/max(len(haar_labels),1):.1%} > 85% — "
                   f"classifier is biased toward one engine, not actually distinguishing.",
        })

    # ===== Test 3: perturbation consistency on Haar states =====
    consistency_scores = []
    for _ in range(10):
        rho_arr = _haar_random_density(rng)
        labels_for_this_state = []
        for _ in range(8):
            perturbed = _perturb(rho_arr, rng, 0.05)
            rho_q = qt.Qobj(perturbed, dims=QDIMS)
            try:
                res = candidate.classify_state(rho_q)
                labels_for_this_state.append(res.get("engine_label"))
            except Exception:
                continue
        if labels_for_this_state:
            majority = max(set(labels_for_this_state), key=labels_for_this_state.count)
            consistency = labels_for_this_state.count(majority) / len(labels_for_this_state)
            consistency_scores.append(consistency)
    avg_consistency = sum(consistency_scores) / max(len(consistency_scores), 1)
    metrics["avg_perturbation_consistency"] = avg_consistency
    if avg_consistency < 0.75:
        failures.append({
            "check": "perturbation_consistency",
            "msg": f"on 10 Haar states perturbed 8 ways each, avg same-label fraction = "
                   f"{avg_consistency:.2%} < 75%. Classifier is reading noise on novel states.",
        })

    return {
        "pass": len(failures) == 0,
        "failures": failures,
        "metrics": metrics,
        "graveyard_companions": [
            "razor-thin paths — accuracy crashes at pert=0.20",
            "always-A classifier — fails haar_unbiased",
            "noise classifier — fails perturbation_consistency",
        ],
        "baseline_variants": [
            "random classifier — fails consistency AND would barely pass unbiasedness",
            "fixed-label classifier — passes consistency but fails unbiasedness",
        ],
    }
