"""phase_46_constraint_manifold_foundation.py — manifold must exist as substrate.

ARCHITECTURAL: the geometric constraint manifold is built FIRST. The 7 axes are
DoFs WITHIN this manifold (not external operations). Flux is part of the manifold's
geometry, NOT a separate axis. Axis 3 is outer-vs-inner loop traversal.

This phase verifies the foundation. If `build_constraint_manifold()` is wrong, every
downstream phase (axes, terrain, stages, primes) is unsupported.

Required API: `build_constraint_manifold() -> dict`
  Returns:
    {
      "carrier_dim": 16,                 # 4-qubit Hilbert dimension
      "pauli_basis": list[qt.Qobj],      # Pauli operators spanning the manifold
      "flux_connection_qt": qt.Qobj,     # U(1) connection — encodes gauge flux
      "manifold_dim": int,               # ≤ 7 (the 7 axes are max DoFs)
      "axis_dof_map": dict[str, dict],   # Ax0..Ax6 → tangent generators; NO flux axis
      "is_constraint_satisfied": callable, # (rho_qt) -> bool — verifier
    }

Test:
  1. Function callable. Returns the documented dict shape.
  2. `carrier_dim` == 16; `manifold_dim` in [3, 7].
  3. `pauli_basis` is non-empty; all entries are 16x16 Qobjs with
     `dims=[[2,2,2,2],[2,2,2,2]]`.
  4. `axis_dof_map` has exactly 7 entries keyed Ax0..Ax6. None is named "flux"
     or otherwise overrides axis 3 with flux. Ax3's description must mention
     "outer" and "inner" loop, NOT "flux" as the discriminator.
  5. `flux_connection_qt` produces NONTRIVIAL holonomy (consistent with
     `flux_holonomy()` if both are exported).
  6. `is_constraint_satisfied(rho)` returns True on the initial reference state
     rho0 and on rho generated by `axis_transform(i, rho0)` for i in 0..6
     (states produced by axis primitives must stay on the manifold).
"""
import numpy as np


def _to_arr(obj):
    if hasattr(obj, "full"): return np.asarray(obj.full())
    if hasattr(obj, "numpy"): return obj.detach().cpu().numpy() if hasattr(obj, "detach") else obj.numpy()
    return np.asarray(obj)


def run(candidate):
    failures = []
    metrics = {}

    if not hasattr(candidate, "build_constraint_manifold"):
        return {"pass": False, "failures": [{
            "check": "build_constraint_manifold_exists",
            "msg": "Required FOUNDATION function `build_constraint_manifold() -> dict` not "
                   "exported. This is the manifold every other primitive operates within — "
                   "without it, axes/terrains/stages have no substrate. Build from Pauli "
                   "matrices on the 4-qubit carrier with flux as part of the geometry. The "
                   "7 axes are DoFs IN the manifold (not separate operations). Ax3 is "
                   "outer-vs-inner loop, NOT flux.",
        }], "metrics": metrics}

    try:
        m = candidate.build_constraint_manifold()
    except Exception as e:
        return {"pass": False, "failures": [{"check": "build_call",
                "msg": f"{type(e).__name__}: {str(e)[:200]}"}], "metrics": metrics}

    if not isinstance(m, dict):
        return {"pass": False, "failures": [{"check": "build_returns_dict",
                "msg": f"got {type(m).__name__}"}], "metrics": metrics}

    for k in ("carrier_dim", "pauli_basis", "flux_connection_qt",
              "manifold_dim", "axis_dof_map", "is_constraint_satisfied"):
        if k not in m:
            failures.append({"check": f"manifold_missing_{k}", "msg": f"missing key `{k}`"})
    if failures:
        return {"pass": False, "failures": failures, "metrics": metrics}

    metrics["carrier_dim"] = m["carrier_dim"]
    metrics["manifold_dim"] = m["manifold_dim"]
    metrics["pauli_basis_size"] = len(m["pauli_basis"]) if hasattr(m["pauli_basis"], "__len__") else None
    metrics["axis_dof_keys"] = sorted(m.get("axis_dof_map", {}).keys())

    if m["carrier_dim"] != 16:
        failures.append({"check": "carrier_dim",
                         "msg": f"carrier_dim={m['carrier_dim']}, expected 16"})

    md = m["manifold_dim"]
    if not (isinstance(md, int) and 3 <= md <= 7):
        failures.append({"check": "manifold_dim_range",
                         "msg": f"manifold_dim={md} not in [3, 7]"})

    # axis_dof_map: exactly 7 entries, Ax0..Ax6, none named flux
    dof = m["axis_dof_map"]
    expected = {f"Ax{i}" for i in range(7)}
    if set(dof.keys()) != expected:
        failures.append({"check": "axis_dof_keys",
                         "msg": f"axis_dof_map keys = {sorted(dof.keys())}, expected Ax0..Ax6"})
    for k, v in dof.items():
        name = (v.get("name", "") or "").lower() if isinstance(v, dict) else ""
        desc = (v.get("description", "") or "").lower() if isinstance(v, dict) else ""
        if "flux" in name or "flux" in desc:
            failures.append({"check": f"axis_{k}_not_flux",
                             "msg": f"{k} is named/described as flux; flux is part of the "
                                    f"manifold's geometry, NOT a separate axis"})
        if k == "Ax3":
            if "outer" not in desc or "inner" not in desc:
                failures.append({"check": "axis_3_outer_inner",
                                 "msg": f"Ax3 description must mention outer-vs-inner loop "
                                        f"traversal (got: {desc[:100]})"})

    # flux_connection produces nontrivial holonomy if the candidate also exports flux_holonomy
    if hasattr(candidate, "flux_holonomy"):
        try:
            fh = float(candidate.flux_holonomy())
            metrics["flux_holonomy"] = fh
            if abs(fh) < 1e-6:
                failures.append({"check": "flux_nontrivial",
                                 "msg": f"flux_holonomy() = {fh}; manifold flux must be nontrivial"})
        except Exception:
            pass

    # is_constraint_satisfied on rho0 (initial state) — must return True
    icf = m["is_constraint_satisfied"]
    if not callable(icf):
        failures.append({"check": "is_constraint_callable",
                         "msg": "is_constraint_satisfied is not callable"})
    else:
        try:
            import qutip as qt
            psi0 = qt.tensor(*[qt.basis(2, 0)] * 4)
            rho0 = qt.ket2dm(psi0)
            ok = bool(icf(rho0))
            metrics["icf_on_rho0"] = ok
            if not ok:
                failures.append({"check": "icf_on_rho0",
                                 "msg": "is_constraint_satisfied(rho0) returned False — "
                                        "the initial state must lie on the manifold"})
            # Now check: states produced by axis_transform stay on manifold
            if hasattr(candidate, "axis_transform"):
                off_manifold = 0
                for i in range(7):
                    try:
                        r = candidate.axis_transform(i, rho0)
                        out = r.get("output_rho_qt") if isinstance(r, dict) else r
                        if not bool(icf(out)):
                            off_manifold += 1
                    except Exception:
                        pass
                metrics["axis_transforms_off_manifold"] = off_manifold
                if off_manifold > 0:
                    failures.append({"check": "axis_transforms_stay_on_manifold",
                                     "msg": f"{off_manifold}/7 axis_transforms produced states "
                                            f"OFF the manifold. Axes are DoFs IN the manifold; "
                                            f"they cannot take you off it."})
        except Exception as e:
            failures.append({"check": "icf_invocation", "msg": str(e)[:160]})

    return {
        "pass": len(failures) == 0,
        "failures": failures,
        "metrics": metrics,
        "graveyard_companions": [
            "axes as external operations — wrong; axes ARE the DoFs of the manifold",
            "flux as axis 3 — wrong; flux is geometry, Ax3 is outer-vs-inner loop",
            "manifold_dim > 7 — wrong; can't have more DoFs than named axes",
            "axis_transforms produce off-manifold states — wrong; axes are tangent DoFs",
        ],
        "baseline_variants": [
            "stub returning empty dict — fails all key checks",
            "manifold with 8th flux axis — fails axis_Ax*_not_flux",
        ],
    }
