#!/usr/bin/env julia
# object_id: foundation_foundation_r5_weyl_chirality_pair_julia
# classification: scratch_diagnostic
# promotion_allowed: false
# formal_admission_allowed: false
# reads_peer_result: true

using Dates
using JSON
using LinearAlgebra
using QuantumOptics
using CliffordAlgebras
using Z3

const RUNG_ID = "foundation_r5_weyl_chirality_pair"
const OBJECT_ID = "foundation_foundation_r5_weyl_chirality_pair_julia"
const ROOT = "/Users/joshuaeisenhart/Codex-Ratchet"
const SOURCE_PATH = joinpath(ROOT, "system_v5/julia_carrier/foundation_foundation_r5_weyl_chirality_pair_julia.jl")
const RESULT_PATH = joinpath(ROOT, "system_v5/julia_carrier/results/foundation_foundation_r5_weyl_chirality_pair_julia_results.json")
const R3_RESULT_PATH = joinpath(ROOT, "system_v5/julia_carrier/results/foundation_r3_octonion_cl6_link_xhigh_julia_results.json")
const CLASSIFICATION = "scratch_diagnostic"
const PROMOTION_ALLOWED = false
const FORMAL_ADMISSION_ALLOWED = false
const READS_PEER_RESULT = true
const TOL = 1.0e-10

function z3_add(args::Vector{Z3.Expr})
    ctx = args[1].ctx
    Z3.Expr(ctx, Z3.Libz3.Z3_mk_add(Z3.ctx_ref(args[1]), length(args), map(Z3.as_ast, args)))
end

function z3_sub(left::Z3.Expr, right::Z3.Expr)
    ctx = left.ctx
    Z3.Expr(ctx, Z3.Libz3.Z3_mk_sub(Z3.ctx_ref(left), 2, map(Z3.as_ast, [left, right])))
end

function spin_basis_ops()
    b = SpinBasis(1//2)
    Dict(
        "I" => identityoperator(b),
        "X" => sigmax(b),
        "Y" => sigmay(b),
        "Z" => sigmaz(b),
    )
end

function tensor_matrix(a, b, c)
    Matrix(tensor(a, b, c).data)
end

function quantumoptics_gamma_matrices()
    ops = spin_basis_ops()
    i2 = ops["I"]
    x = ops["X"]
    y = ops["Y"]
    z = ops["Z"]
    [
        tensor_matrix(x, i2, i2),
        tensor_matrix(y, i2, i2),
        tensor_matrix(z, x, i2),
        tensor_matrix(z, y, i2),
        tensor_matrix(z, z, x),
        tensor_matrix(z, z, y),
    ]
end

function load_r3_peer_result()
    isfile(R3_RESULT_PATH) || error("R5 Weyl chirality-pair sim requires R3 peer result at $(R3_RESULT_PATH); none found.")
    JSON.parsefile(R3_RESULT_PATH)
end

# Same generated-rank technique R3 uses on its octonion left-multiplication
# matrices (foundation_r3_octonion_cl6_link_xhigh_julia.jl): the rank of the
# matrix algebra generated by all 2^k products of k anticommuting generators.
# Applied here to this rung's own 6 QuantumOptics gamma matrices so the
# independently-built 3-qubit Cl(6)-type carrier is cross-checked against
# R3's admitted Cl(0,6) octonion-linked rank/spinor-dimension, not just
# judged consistent by code inspection.
function generated_rank(mats::Vector{Matrix{ComplexF64}}, generator_count::Int)
    dim = size(mats[1], 1)
    cols = Vector{ComplexF64}[]
    for mask in 0:(2^generator_count - 1)
        acc = Matrix{ComplexF64}(LinearAlgebra.I, dim, dim)
        for idx in 1:generator_count
            if ((mask >> (idx - 1)) & 1) == 1
                acc = acc * mats[idx]
            end
        end
        push!(cols, vec(acc))
    end
    mat = hcat(cols...)
    singular = svdvals(mat)
    max_s = isempty(singular) ? 0.0 : maximum(singular)
    tol = max(size(mat)...) * eps(Float64) * max_s * 100.0
    count(>(tol), singular)
end

function r3_provenance_check(r3::AbstractDict, gammas::Vector{Matrix{ComplexF64}})
    r3_summary = r3["summary"]
    local_rank = generated_rank(gammas, 6)
    Dict{String,Any}(
        "r3_result_path" => R3_RESULT_PATH,
        "r3_object_id" => get(r3, "object_id", nothing),
        "r3_source_sha256" => get(r3, "source_sha256", nothing),
        "r3_octonion_cl6_rank" => r3_summary["octonion_cl6_rank"],
        "r3_octonion_spinor_dim" => r3_summary["octonion_spinor_dim"],
        "local_spinor_dim" => size(gammas[1], 1),
        "local_generated_rank_from_6_quantumoptics_gammas" => local_rank,
        "matches_r3_rank" => local_rank == r3_summary["octonion_cl6_rank"],
        "matches_r3_spinor_dim" => size(gammas[1], 1) == r3_summary["octonion_spinor_dim"],
    )
end

function matrix_anticommutation_report(gammas)
    dim = size(gammas[1], 1)
    ident = Matrix{ComplexF64}(LinearAlgebra.I, dim, dim)
    max_residual = 0.0
    failures = Any[]
    for i in eachindex(gammas), j in eachindex(gammas)
        target = i == j ? 2.0 .* ident : zeros(ComplexF64, dim, dim)
        residual = norm(gammas[i] * gammas[j] + gammas[j] * gammas[i] - target)
        max_residual = max(max_residual, Float64(residual))
        if residual > TOL
            push!(failures, Dict{String,Any}("i" => i, "j" => j, "residual" => Float64(residual)))
        end
    end
    Dict{String,Any}("max_residual" => max_residual, "failures" => failures, "pass" => isempty(failures))
end

function cliffordalgebras_report()
    cl6 = CliffordAlgebra(6, 0)
    gens = [getproperty(cl6, Symbol("e$i")) for i in 1:6]
    unit = one(gens[1])
    raw_ps = reduce(*, gens)
    anticommutation_failures = Any[]
    max_residual = 0.0
    for i in 1:6, j in 1:6
        lhs = gens[i] * gens[j] + gens[j] * gens[i]
        rhs = (i == j ? 2 : 0) * unit
        residual = Float64(CliffordAlgebras.norm(lhs - rhs))
        max_residual = max(max_residual, residual)
        if residual > TOL
            push!(anticommutation_failures, Dict{String,Any}("i" => i, "j" => j, "residual" => residual))
        end
    end
    raw_square_residual = Float64(CliffordAlgebras.norm(raw_ps * raw_ps + unit))
    Dict{String,Any}(
        "package" => "CliffordAlgebras",
        "signature" => "Cl(6,0)",
        "generator_count" => length(gens),
        "raw_pseudoscalar" => string(raw_ps),
        "raw_pseudoscalar_square" => string(raw_ps * raw_ps),
        "raw_pseudoscalar_square_minus_negative_unit_residual" => raw_square_residual,
        "anticommutation" => Dict{String,Any}(
            "max_residual" => max_residual,
            "failures" => anticommutation_failures,
            "pass" => isempty(anticommutation_failures),
        ),
    )
end

function z3_projector_dim_proof(trace_gamma7::Int, control_trace::Int)
    main = Z3.Solver()
    p = Z3.IntVar("plus_dim")
    m = Z3.IntVar("minus_dim")
    Z3.add(main, z3_add(Z3.Expr[p, m]) == Z3.IntVal(8))
    Z3.add(main, z3_sub(p, m) == Z3.IntVal(trace_gamma7))
    Z3.add(main, Z3.Or(Z3.Expr[Z3.Not(p == Z3.IntVal(4)), Z3.Not(m == Z3.IntVal(4))]))
    main_status = string(Z3.check(main))

    control = Z3.Solver()
    cp = Z3.IntVar("control_plus_dim")
    cm = Z3.IntVar("control_minus_dim")
    Z3.add(control, z3_add(Z3.Expr[cp, cm]) == Z3.IntVal(8))
    Z3.add(control, z3_sub(cp, cm) == Z3.IntVal(control_trace))
    Z3.add(control, Z3.Or(Z3.Expr[Z3.Not(cp == Z3.IntVal(4)), Z3.Not(cm == Z3.IntVal(4))]))
    control_status = string(Z3.check(control))

    Dict{String,Any}(
        "encoding" => "Int plus/minus dimensions satisfy plus+minus=8 and plus-minus=Tr(gamma7); assert not 4/4.",
        "main_not_4_4_verdict" => main_status,
        "control_identity_not_4_4_verdict" => control_status,
        "main_proved_4_4" => main_status == "unsat",
        "identity_control_flips" => control_status == "sat",
    )
end

function class_partition(signatures::Vector{Float64}, prefix::String)
    groups = Dict{String,Vector{String}}()
    for (idx, sig) in enumerate(signatures)
        key = string(round(sig; digits=12))
        if !haskey(groups, key)
            groups[key] = String[]
        end
        push!(groups[key], "basis_$(idx - 1)")
    end
    classes = Any[]
    for (class_idx, key) in enumerate(sort(collect(keys(groups))))
        push!(classes, Dict{String,Any}(
            "class_id" => "$(prefix)_q$(class_idx - 1)",
            "signature" => [parse(Float64, key)],
            "members" => sort(groups[key]),
        ))
    end
    classes
end

function constraints_report(dim::Int)
    details = Any[]
    for idx in 1:dim
        v = zeros(ComplexF64, dim)
        v[idx] = 1.0 + 0.0im
        rho = v * v'
        eigs = eigvals(Hermitian((rho + rho') / 2))
        push!(details, Dict{String,Any}(
            "id" => "basis_$(idx - 1)",
            "trace_residual" => abs(real(tr(rho)) - 1.0),
            "hermitian_residual" => norm(rho - rho'),
            "min_eigenvalue" => minimum(real.(eigs)),
            "normalization_residual" => abs(real(v' * v) - 1.0),
            "psd" => minimum(real.(eigs)) >= -TOL,
        ))
    end
    Dict{String,Any}(
        "trace_one" => all(row["trace_residual"] <= TOL for row in details),
        "hermitian" => all(row["hermitian_residual"] <= TOL for row in details),
        "psd" => all(row["psd"] for row in details),
        "normalized" => all(row["normalization_residual"] <= TOL for row in details),
        "details" => details,
    )
end

function build_result()
    started = time()
    gammas = quantumoptics_gamma_matrices()
    dim = size(gammas[1], 1)
    ident = Matrix{ComplexF64}(LinearAlgebra.I, dim, dim)
    raw_product = reduce(*, gammas)
    chirality_phase = (-1im)^3
    gamma7 = chirality_phase .* raw_product
    gamma7_square_residual = Float64(norm(gamma7 * gamma7 - ident))
    gamma7_hermitian_residual = Float64(norm(gamma7 - gamma7'))
    gamma7_trace = real(tr(gamma7))
    gamma7_trace_int = Int(round(gamma7_trace))
    gamma7_diag = [Float64(round(real(gamma7[i, i]); digits=12)) for i in 1:dim]
    eigenvalues = sort(real.(eigvals(Hermitian((gamma7 + gamma7') / 2))))
    plus_dim = count(value -> abs(value - 1.0) <= TOL, eigenvalues)
    minus_dim = count(value -> abs(value + 1.0) <= TOL, eigenvalues)
    p_plus = (ident + gamma7) ./ 2.0
    p_minus = (ident - gamma7) ./ 2.0
    projector_report = Dict{String,Any}(
        "P_plus_trace" => Float64(real(tr(p_plus))),
        "P_minus_trace" => Float64(real(tr(p_minus))),
        "P_plus_idempotency_residual" => Float64(norm(p_plus * p_plus - p_plus)),
        "P_minus_idempotency_residual" => Float64(norm(p_minus * p_minus - p_minus)),
        "P_plus_P_minus_residual" => Float64(norm(p_plus * p_minus)),
    )

    matrix_cl6 = matrix_anticommutation_report(gammas)
    algebra_cl6 = cliffordalgebras_report()
    constraints = constraints_report(dim)
    active_classes = class_partition(gamma7_diag, "gamma7")
    drop_classes = [Dict{String,Any}(
        "class_id" => "drop_M_q0",
        "signature" => Any[],
        "members" => ["basis_$(idx)" for idx in 0:(dim - 1)],
    )]
    identity_control_diag = ones(Float64, dim)
    identity_control_classes = class_partition(identity_control_diag, "identity_gamma7")
    z3_report = z3_projector_dim_proof(gamma7_trace_int, dim)
    r3_peer = load_r3_peer_result()
    r3_check = r3_provenance_check(r3_peer, gammas)
    all_pass = (
        dim == 8 &&
        matrix_cl6["pass"] &&
        algebra_cl6["anticommutation"]["pass"] &&
        algebra_cl6["raw_pseudoscalar_square_minus_negative_unit_residual"] <= TOL &&
        gamma7_square_residual <= TOL &&
        gamma7_hermitian_residual <= TOL &&
        plus_dim == 4 &&
        minus_dim == 4 &&
        length(active_classes) == 2 &&
        length(drop_classes) == 1 &&
        length(identity_control_classes) == 1 &&
        constraints["trace_one"] &&
        constraints["hermitian"] &&
        constraints["psd"] &&
        constraints["normalized"] &&
        z3_report["main_proved_4_4"] &&
        z3_report["identity_control_flips"] &&
        r3_check["matches_r3_rank"] &&
        r3_check["matches_r3_spinor_dim"]
    )

    Dict{String,Any}(
        "schema_version" => "engine_leg_result_v1",
        "rung_id" => RUNG_ID,
        "object_id" => OBJECT_ID,
        "engine" => "julia",
        "classification" => CLASSIFICATION,
        "promotion_allowed" => PROMOTION_ALLOWED,
        "formal_admission_allowed" => FORMAL_ADMISSION_ALLOWED,
        "reads_peer_result" => READS_PEER_RESULT,
        "r3_peer_provenance_check" => r3_check,
        "generated_at" => Dates.format(now(UTC), dateformat"yyyy-mm-ddTHH:MM:SSZ"),
        "source_path" => SOURCE_PATH,
        "result_path" => RESULT_PATH,
        "active_project" => Base.active_project(),
        "julia_version" => string(VERSION),
        "packages_used" => ["QuantumOptics", "CliffordAlgebras", "Z3", "LinearAlgebra", "JSON", "Dates"],
        "aligned_packages_load_bearing" => ["QuantumOptics", "CliffordAlgebras", "Z3"],
        "claim_ceiling" => "Scratch foundation R5 Weyl chirality-pair construction on installed 3-qubit/Cl(6) carrier only. No forced-vs-installed reopening, no SM claim, no formal admission, no promotion.",
        "M" => Dict{String,Any}(
            "explicit_probe_family" => ["gamma7_chirality_probe"],
            "gamma7_definition" => "gamma7 = (-i)^3 * gamma1*...*gamma6; the raw Euclidean Cl(6) pseudoscalar squares to -I and the normalized chirality probe squares to +I.",
        ),
        "C" => Dict{String,Any}(
            "state_constraints" => ["trace=1", "PSD", "Hermitian", "normalization"],
            "rung_specific_constraint" => "six QuantumOptics tensor gamma matrices satisfy Cl(6) anticommutation; gamma7 is the normalized product chirality probe.",
            "constraints_hold" => constraints,
            "cliffordalgebras" => algebra_cl6,
            "quantumoptics_matrix_cl6" => matrix_cl6,
        ),
        "S" => Dict{String,Any}(
            "carrier" => "8-dimensional three-qubit spinor basis",
            "basis_state_count" => dim,
            "basis_ids" => ["basis_$(idx)" for idx in 0:(dim - 1)],
        ),
        "S_quotient" => Dict{String,Any}(
            "definition" => "basis spinors are equivalent when gamma7 expectation values match",
            "classes" => active_classes,
            "class_count" => length(active_classes),
            "left_right_dims" => Dict{String,Any}("plus" => plus_dim, "minus" => minus_dim),
        ),
        "chirality" => Dict{String,Any}(
            "chirality_phase" => string(chirality_phase),
            "raw_product_square_residual_to_minus_I" => Float64(norm(raw_product * raw_product + ident)),
            "gamma7_square_residual_to_plus_I" => gamma7_square_residual,
            "gamma7_hermitian_residual" => gamma7_hermitian_residual,
            "gamma7_trace" => Float64(gamma7_trace),
            "gamma7_diagonal" => gamma7_diag,
            "eigenvalues" => [Float64(round(v; digits=12)) for v in eigenvalues],
            "plus_dim" => plus_dim,
            "minus_dim" => minus_dim,
            "projectors" => projector_report,
        ),
        "negative_control_flip" => Dict{String,Any}(
            "drop_M_class_count" => length(drop_classes),
            "active_M_class_count" => length(active_classes),
            "drop_M_changed_quotient" => length(drop_classes) != length(active_classes),
            "identity_gamma7_plus_dim" => 8,
            "identity_gamma7_minus_dim" => 0,
            "identity_gamma7_class_count" => length(identity_control_classes),
            "identity_control_no_split" => length(identity_control_classes) == 1,
            "z3_main_not_4_4_verdict" => z3_report["main_not_4_4_verdict"],
            "z3_identity_control_not_4_4_verdict" => z3_report["control_identity_not_4_4_verdict"],
            "sat_unsat_flip" => "main not-4/4=$(z3_report["main_not_4_4_verdict"]); identity-control not-4/4=$(z3_report["control_identity_not_4_4_verdict"])",
        ),
        "julia_z3" => z3_report,
        "values" => Dict{String,Any}(
            "spinor_dim" => dim,
            "gamma7_square_residual" => gamma7_square_residual,
            "plus_dim" => plus_dim,
            "minus_dim" => minus_dim,
            "active_M_class_count" => length(active_classes),
            "drop_M_class_count" => length(drop_classes),
            "identity_control_plus_dim" => 8,
            "identity_control_minus_dim" => 0,
        ),
        "TOOL_MANIFEST" => Dict{String,Any}(
            "QuantumOptics" => Dict{String,Any}("tried" => true, "used" => true, "reason" => "load-bearing tensor-product Pauli/SpinBasis operator construction for the 3-qubit Cl(6) gamma matrices"),
            "CliffordAlgebras" => Dict{String,Any}("tried" => true, "used" => true, "reason" => "load-bearing Cl(6,0) generator and raw pseudoscalar structure check; confirms raw Euclidean pseudoscalar squares to -1 before chirality normalization"),
            "Z3" => Dict{String,Any}("tried" => true, "used" => true, "reason" => "load-bearing Julia-side dimension proof from Tr(gamma7): not-4/4 is UNSAT for the constructed probe and SAT for identity-control erasure"),
            "LinearAlgebra" => Dict{String,Any}("tried" => true, "used" => true, "reason" => "supportive eigenvalue, trace, and residual computation; not the carrier source"),
            "JSON" => Dict{String,Any}("tried" => true, "used" => true, "reason" => "load-bearing read of R3's persisted result JSON (foundation_r3_octonion_cl6_link_xhigh_julia_results.json) for peer-dependency provenance, plus supportive result serialization"),
            "Dates" => Dict{String,Any}("tried" => true, "used" => true, "reason" => "supportive UTC timestamp"),
        ),
        "TOOL_INTEGRATION_DEPTH" => Dict{String,Any}(
            "QuantumOptics" => "load_bearing",
            "CliffordAlgebras" => "load_bearing",
            "Z3" => "load_bearing",
            "LinearAlgebra" => "supportive",
            "JSON" => "load_bearing",
            "Dates" => "supportive",
        ),
        "all_pass" => all_pass,
        "runtime_seconds" => round(time() - started; digits=6),
    )
end

function main()
    result = build_result()
    mkpath(dirname(RESULT_PATH))
    open(RESULT_PATH, "w") do io
        JSON.print(io, result, 2)
        write(io, "\n")
    end
    values = result["values"]
    println(
        "FOUNDATION_R5_JULIA_DONE " *
        "all_pass=$(result["all_pass"]) " *
        "gamma7_square_residual=$(values["gamma7_square_residual"]) " *
        "dims=$(values["plus_dim"])/$(values["minus_dim"]) " *
        "classes=$(values["active_M_class_count"]) " *
        "drop_M=$(values["drop_M_class_count"]) " *
        "r3_matches_rank=$(result["r3_peer_provenance_check"]["matches_r3_rank"]) " *
        "r3_matches_spinor_dim=$(result["r3_peer_provenance_check"]["matches_r3_spinor_dim"])"
    )
    return result["all_pass"] ? 0 : 1
end

if abspath(PROGRAM_FILE) == @__FILE__
    exit(main())
end
