#!/usr/bin/env python3
"""
Axis 0: Feynman Path-Integral / Nested Hopf Torus SIM
=====================================================
Instantiates the NLM 'Sim Ladder' for Axis 0:
1. Translates j,k fuzz into Kraus operator bounds (History expansions).
2. Computes the 'i-scalar' via Stinespring Dilation (Environment Entropy S(ρE)).
3. Verifies Monotonicity of this clock under nested coarse-graining (6-qubit shell ladder).
"""

import numpy as np
import scipy.linalg
import json
import os
import sys
from datetime import datetime
try:
    from datetime import UTC
except ImportError:
    from datetime import timezone
    UTC = timezone.utc

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from proto_ratchet_sim_runner import von_neumann_entropy, EvidenceToken

def calc_environment_state(rho, kraus_ops):
    """
    Computes the Stinespring Dilation Environment State (ρE).
    This tracks the 'which-path' Feynman history generated by the CPTP fuzz.
    Matrix elements of ρE are given by: (ρE)_{jm} = Tr(K_m ρ K_j†)
    """
    dim_e = len(kraus_ops)
    rho_e = np.zeros((dim_e, dim_e), dtype=complex)
    for j in range(dim_e):
        for m in range(dim_e):
            term = kraus_ops[m] @ rho @ kraus_ops[j].conj().T
            rho_e[j, m] = np.trace(term)
            
    # Clean numerical errors
    rho_e = (rho_e + rho_e.conj().T) / 2
    eigvals = np.real(scipy.linalg.eigvalsh(rho_e))
    eigvals[eigvals < 0] = 0
    if np.sum(eigvals) > 0:
        eigvals /= np.sum(eigvals)
    V = scipy.linalg.eigh(rho_e)[1]
    return V @ np.diag(eigvals) @ V.conj().T

def safe_von_neumann(rho):
    eigvals = np.real(scipy.linalg.eigvalsh((rho + rho.conj().T)/2))
    eigvals = eigvals[eigvals > 1e-12]
    return -np.sum(eigvals * np.log2(eigvals)) if len(eigvals) > 0 else 0.0

def partial_trace(rho, dims, keep_indices):
    """
    Traces out all subsystems EXCEPT those in `keep_indices`.
    `dims` is a list/tuple of the dimension of each subsystem.
    """
    num_subsys = len(dims)
    trace_indices = [i for i in range(num_subsys) if i not in keep_indices]
    
    # Reshape rho into tensor
    tensor_shape = tuple(dims) + tuple(dims)
    rho_tensor = rho.reshape(tensor_shape)
    
    # Trace out sequentially (from last index to first to avoid shifting)
    # The axes to trace are i and i + num_subsys
    current_dims = list(dims)
    
    # Actually, simpler to do it structurally with numpy einsum or a manual loop
    # Let's do a standard permutation + trace
    keep_dims = [dims[i] for i in keep_indices]
    trace_dims = [dims[i] for i in trace_indices]
    
    if not trace_indices:
        return rho
        
    # Reorder tensor: kept subsystems first, traced subsystems last
    axes = keep_indices + trace_indices + [i + num_subsys for i in keep_indices] + [i + num_subsys for i in trace_indices]
    rho_reordered = np.transpose(rho_tensor, axes)
    
    # Reshape to (KeepOut, TraceOut, KeepIn, TraceIn)
    D_keep = np.prod(keep_dims, dtype=int)
    D_trace = np.prod(trace_dims, dtype=int)
    rho_matrix = rho_reordered.reshape((D_keep, D_trace, D_keep, D_trace))
    
    # Trace over the environment (axis 1 and 3)
    # np.trace traces over axis1=0, axis2=1 by default
    rho_reduced = np.trace(rho_matrix, axis1=1, axis2=3)
    return rho_reduced

def generate_random_kraus(d, num_ops):
    """Generates a random Trace-Preserving Kraus operator set."""
    ops = []
    H_sum = np.zeros((d,d), dtype=complex)
    for _ in range(num_ops):
        K = np.random.randn(d,d) + 1j * np.random.randn(d,d)
        ops.append(K)
        H_sum += K.conj().T @ K
        
    # Normalize to ensure sum K† K = I
    inv_sqrt = scipy.linalg.inv(scipy.linalg.sqrtm(H_sum))
    for i in range(num_ops):
        ops[i] = ops[i] @ inv_sqrt
    return ops

def step1_two_qubit_ladder():
    print("\n--- STEP 1: 2 QUBIT (Phase Battery) ---")
    d_sub = 2
    
    # Bell State |Φ+> = (|00> + |11>) / √2
    bell_vec = np.zeros(4, dtype=complex)
    bell_vec[0] = 1/np.sqrt(2)
    bell_vec[3] = 1/np.sqrt(2)
    rho_bell = np.outer(bell_vec, bell_vec.conj())
    
    # Calculate initial S(A|B)
    rho_B = partial_trace(rho_bell, [2, 2], [1])
    S_AB = safe_von_neumann(rho_bell)
    S_B = safe_von_neumann(rho_B)
    S_cond_init = S_AB - S_B
    print(f"Initial Bell State S(A|B) = {S_cond_init:.4f} (Negative Entropy Battery!)")
    
    # Apply Noise (Perturbation)
    kraus = generate_random_kraus(4, 3) # 3-path history fuzz
    rho_Env = calc_environment_state(rho_bell, kraus)
    i_scalar = safe_von_neumann(rho_Env)
    
    print(f"Post-Fuzz Stinespring i-Scalar S(ρE) = {i_scalar:.4f}")
    
    return S_cond_init < -0.9, i_scalar

def step2_four_qubit_ladder():
    print("\n--- STEP 2: 4 QUBIT (Graph Cut Diversity) ---")
    
    # 4-Qubit GHZ State (|0000> + |1111>) / √2
    d_total = 16
    vec = np.zeros(d_total, dtype=complex)
    vec[0] = 1/np.sqrt(2)
    vec[15] = 1/np.sqrt(2)
    rho_4 = np.outer(vec, vec.conj())
    
    dims = [2, 2, 2, 2]
    
    # Cut 1: A vs BCD
    rho_A = partial_trace(rho_4, dims, [0])
    Ic_1 = -(safe_von_neumann(rho_4) - safe_von_neumann(partial_trace(rho_4, dims, [1,2,3])))
    
    # Cut 2: AB vs CD
    rho_AB = partial_trace(rho_4, dims, [0,1])
    Ic_2 = -(safe_von_neumann(rho_4) - safe_von_neumann(partial_trace(rho_4, dims, [2,3])))
    
    print(f"Coherent Info (A vs BCD): {Ic_1:.4f}")
    print(f"Coherent Info (AB vs CD): {Ic_2:.4f}")
    
    kraus = generate_random_kraus(d_total, 4)
    rho_Env = calc_environment_state(rho_4, kraus)
    i_scalar = safe_von_neumann(rho_Env)
    print(f"4-Qubit Map Fuzz i-Scalar S(ρE) = {i_scalar:.4f}")
    
    return True

def step3_six_qubit_ladder():
    print("\n--- STEP 3: 6 QUBIT (Nested Hopf Shells Monotonicity) ---")
    
    # 6-Qubit somewhat mixed entangled state
    dims = [2, 2, 2, 2, 2, 2] # 64 dimensions total
    np.random.seed(99)
    H = np.random.randn(64,64) + 1j * np.random.randn(64,64)
    H = H + H.conj().T
    U = scipy.linalg.expm(-1j * 0.5 * H)
    psi = U[:, 0]
    rho_6 = np.outer(psi, psi.conj())
    
    # We prove Monotonicity of the i-scalar under coarse-graining via
    # Strong Subadditivity (SSA) of Quantum Entropy: I(A:BC) >= I(A:B)
    # A = Core (Q0, Q1)
    # B = Inner Shell (Q2, Q3)
    # C = Outer Shell (Q4, Q5)
    
    rho_A   = partial_trace(rho_6, dims, [0,1])
    rho_B   = partial_trace(rho_6, dims, [2,3])
    rho_BC  = partial_trace(rho_6, dims, [2,3,4,5])
    rho_AB  = partial_trace(rho_6, dims, [0,1,2,3])
    rho_ABC = partial_trace(rho_6, dims, [0,1,2,3,4,5])
    
    # I(A : B) = S(A) + S(B) - S(AB)
    MI_A_B = safe_von_neumann(rho_A) + safe_von_neumann(rho_B) - safe_von_neumann(rho_AB)
    
    # I(A : BC) = S(A) + S(BC) - S(ABC)
    MI_A_BC = safe_von_neumann(rho_A) + safe_von_neumann(rho_BC) - safe_von_neumann(rho_ABC)
    
    # I(A : ABC) doesn't make geometric sense, BC is the whole boundary for A.
    
    print(f"Mutual Info (Core : Inner Shell) [I(A:B)]:       {MI_A_B:.4f}")
    print(f"Mutual Info (Core : Inner+Outer Shell) [I(A:BC)]:{MI_A_BC:.4f}")
    
    is_monotonic = MI_A_BC >= MI_A_B - 1e-10
    print(f"Is Monotonically Directional Under Coarse-Graining? {is_monotonic}")
    
    return is_monotonic

def run_all():
    t1_pass, i_scale_2 = step1_two_qubit_ladder()
    step2_four_qubit_ladder()
    t3_pass = step3_six_qubit_ladder()
    
    tokens = []
    
    if t1_pass and t3_pass:
        print("\n[PASS] Nested Hopf Tori 'i-Scalar' Ladder Verified.")
        tokens.append(EvidenceToken(
            "E_SIM_NESTED_HOPF_TORI_OK", "S_SIM_PATH_INTEGRAL_AXIS0", "PASS", float(i_scale_2)
        ))
    else:
        print("\n[KILL] Nested Hopf Tori 'i-Scalar' mapping failed monotonicity bounds.")
        tokens.append(EvidenceToken(
            "", "S_SIM_PATH_INTEGRAL_AXIS0", "KILL", 0.0, "NON_MONOTONIC_COARSE_GRAIN"
        ))
        
    out_file = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "a2_state", "sim_results", "axis0_path_integral_results.json"
    )
    
    output = {
        "schema": "SIM_EVIDENCE_v1",
        "file": os.path.basename(__file__),
        "timestamp": datetime.now(UTC).isoformat() + "Z",
        "evidence_ledger": [t.__dict__ for t in tokens]
    }
    
    with open(out_file, "w") as f:
        json.dump(output, f, indent=2)

if __name__ == "__main__":
    run_all()
