#!/usr/bin/env python3
"""
sim_weyl_group_g2_shell_local
================================
Shell-local probe: Weyl group W(G2) and the G2 root system.

G2 is the smallest exceptional Lie algebra. Its root system has 12 roots:
6 short roots (forming A2) and 6 long roots (length sqrt(3) times the short roots).
The Weyl group W(G2) = Dih6 (dihedral group of order 12). It is generated by two
simple reflections s1, s2 satisfying the Coxeter relation (s1*s2)^6 = e.

This sim probes the G2 Weyl group shell in isolation (before any pairwise coupling).

Claims tested:
  - W(G2) has order 12: generated by s1, s2 with (s1*s2)^6 = e
  - G2 root system: 12 roots in TWO orbits (6 short + 6 long)
  - Long roots have length sqrt(3) x short roots: length ratio = sqrt(3)
  - Cartan matrix of G2: [[2,-1],[-3,2]] (asymmetric: -3 reflects long root)
  - Longest element w0 = -identity (maps all positive roots to negative)
  - G2 contains A2 as a sub-root-system: inner hexagon = A2 short roots
  - W(A2) = S3 is a subgroup of W(G2) = Dih6
  - Coxeter order for G2 is 6 (vs 3 for A2, 4 for B2)

Classification: classical_baseline
Shell: Weyl group G2 shell-local (before any pairwise coupling)
"""

import json
import math
import os

# =====================================================================
# TOOL MANIFEST
# =====================================================================

TOOL_MANIFEST = {
    "pytorch": {
        "tried": True,
        "used": True,
        "reason": (
            "Represent all 12 G2 roots as 2D float64 tensors; apply all 12 Weyl group "
            "elements; verify two 6-element orbits (short and long roots); confirm that "
            "inner 6 roots match A2 pattern; check (s1*s2)^6 = I numerically"
        ),
    },
    "pyg": {
        "tried": False,
        "used": False,
        "reason": "not used in this Weyl geometry shell-local probe; deferred to coupling sims",
    },
    "z3": {
        "tried": True,
        "used": True,
        "reason": (
            "UNSAT: (s1*s2)^3 = identity AND this is G2; G2 Coxeter order is 6 not 3; "
            "encode as: a G2-type system has Coxeter order=6, (s1s2)^3=I implies order<=3 "
            "which is A2, contradicting the G2 Cartan entry -3"
        ),
    },
    "cvc5": {
        "tried": False,
        "used": False,
        "reason": "not used in this Weyl geometry shell-local probe; deferred to coupling sims",
    },
    "sympy": {
        "tried": True,
        "used": True,
        "reason": (
            "G2 Cartan matrix [[2,-1],[-3,2]]; compute simple reflections s_i(lambda) = "
            "lambda - <lambda,alpha_i^v>*alpha_i; verify (s1*s2)^6 = I symbolically; "
            "confirm (s1*s2)^3 != I (distinguishes G2 from A2)"
        ),
    },
    "clifford": {
        "tried": True,
        "used": True,
        "reason": (
            "G2 roots in Cl(2,0); Clifford reflections s_alpha(v) = -alpha*v*alpha^{-1}/|alpha|^2; "
            "verify all 12 roots; confirm long root length = sqrt(3) * short root length; "
            "verify Clifford composition of 6 reflections gives identity"
        ),
    },
    "geomstats": {
        "tried": False,
        "used": False,
        "reason": "not used in this Weyl geometry shell-local probe; deferred to coupling sims",
    },
    "e3nn": {
        "tried": False,
        "used": False,
        "reason": "not used in this Weyl geometry shell-local probe; deferred to coupling sims",
    },
    "rustworkx": {
        "tried": True,
        "used": True,
        "reason": (
            "Cayley graph of W(G2) = Dih6 with generators {s1, s2}: 12 nodes in dodecagonal "
            "pattern; verify strongly connected and distinct from Dih4 (8 nodes) and S3 (6 nodes)"
        ),
    },
    "xgi": {
        "tried": True,
        "used": True,
        "reason": (
            "Hyperedge {s1, s2, (s1*s2)^6} recording the G2 Coxeter relation; "
            "and hyperedge {short_roots, A2_subgroup, G2} showing A2 nesting inside G2"
        ),
    },
    "toponetx": {
        "tried": False,
        "used": False,
        "reason": "not used in this Weyl geometry shell-local probe; deferred to coupling sims",
    },
    "gudhi": {
        "tried": False,
        "used": False,
        "reason": "not used in this Weyl geometry shell-local probe; deferred to coupling sims",
    },
}

TOOL_INTEGRATION_DEPTH = {
    "pytorch": "load_bearing",
    "pyg": None,
    "z3": "load_bearing",
    "cvc5": None,
    "sympy": "load_bearing",
    "clifford": "load_bearing",
    "geomstats": None,
    "e3nn": None,
    "rustworkx": "load_bearing",
    "xgi": "load_bearing",
    "toponetx": None,
    "gudhi": None,
}

# =====================================================================
# IMPORTS
# =====================================================================

import torch
import sympy as sp
from z3 import Solver, Int, unsat, sat
from clifford import Cl
import rustworkx as rx
import xgi

# =====================================================================
# G2 ROOT SYSTEM AND WEYL GROUP SETUP
# =====================================================================
#
# G2 Cartan matrix: [[2,-1],[-3,2]]
#   alpha1 = simple short root
#   alpha2 = simple long root
#
# From Cartan matrix [[2,-1],[-3,2]]:
#   <alpha1^v, alpha2> = A_{12} = -1  (= 2<alpha1,alpha2>/<alpha1,alpha1>)
#   <alpha2^v, alpha1> = A_{21} = -3  (= 2<alpha2,alpha1>/<alpha2,alpha2>)
#
# Choose alpha1 = (1, 0) [short, length 1]
# Then alpha2 = (x, y) satisfying:
#   <alpha2,alpha1> = x = A_{21} * <alpha1,alpha1> / 2 = -3 * 1 / 2 = -3/2
#   <alpha1,alpha2> = x = A_{12} * <alpha2,alpha2> / 2
#   |alpha2|^2 = x^2 + y^2
#   From A_{12} = 2*(-3/2) / |alpha2|^2 = -1  =>  |alpha2|^2 = 3
#   So x = -3/2, y^2 = 3 - 9/4 = 3/4, y = sqrt(3)/2
#
# alpha1 = (1, 0)   [short, |alpha1| = 1]
# alpha2 = (-3/2, sqrt(3)/2)  [long, |alpha2| = sqrt(3)]
#
# All 12 G2 roots: 6 short + 6 long
# Short roots (A2 root system, length 1):
#   +-(1,0), +-(−1/2, sqrt(3)/2), +-(1/2, sqrt(3)/2)
# Long roots (length sqrt(3)):
#   +-(3/2, sqrt(3)/2), +-(0, sqrt(3)), +-(−3/2, sqrt(3)/2) [wait - need to re-derive]
#
# Actually the G2 roots from the simple roots (alpha1, alpha2) are generated by
# all reflections. Let me compute the full root system systematically.

SQRT3 = math.sqrt(3.0)
SQRT3_2 = SQRT3 / 2.0

# Simple roots for G2
G2_ALPHA1 = torch.tensor([1.0, 0.0], dtype=torch.float64)          # short
G2_ALPHA2 = torch.tensor([-3.0 / 2.0, SQRT3_2], dtype=torch.float64)  # long


def simple_reflection_matrix(alpha: torch.Tensor) -> torch.Tensor:
    """2x2 Weyl reflection matrix."""
    denom = torch.dot(alpha, alpha)
    return torch.eye(2, dtype=torch.float64) - 2.0 * torch.outer(alpha, alpha) / denom


# Build all 12 G2 roots by applying reflections
def build_g2_roots():
    """
    Build all 12 G2 roots by applying the Weyl group generators to the simple roots.
    The roots are the orbits of alpha1 (short) and alpha2 (long) under W(G2).
    Since W(G2) acts on alpha1 to give all 6 short roots, and on alpha2 to give
    all 6 long roots, we generate them via iterated reflections.
    """
    S1 = simple_reflection_matrix(G2_ALPHA1)
    S2 = simple_reflection_matrix(G2_ALPHA2)

    def reflect_root(root, S):
        return S @ root

    # Generate short roots: start from alpha1, apply all W(G2) elements
    # Short roots should be: +-alpha1, +-s2(alpha1), +-s1(s2(alpha1))
    # etc. — they form a hexagon of radius 1
    # alpha1 = (1,0)
    # s2(alpha1): alpha1 - 2*<alpha1,alpha2>/<alpha2,alpha2>*alpha2
    # <alpha1,alpha2> = 1*(-3/2) + 0*(sqrt(3)/2) = -3/2
    # <alpha2,alpha2> = 9/4 + 3/4 = 3
    # s2(alpha1) = (1,0) - 2*(-3/2)/3 * (-3/2, sqrt(3)/2) = (1,0) + 1 * (-3/2, sqrt(3)/2)
    #            = (-1/2, sqrt(3)/2)
    # s1(alpha2): alpha2 - 2*<alpha2,alpha1>/<alpha1,alpha1>*alpha1
    # <alpha2,alpha1> = -3/2; <alpha1,alpha1> = 1
    # s1(alpha2) = (-3/2, sqrt(3)/2) - 2*(-3/2)/1 * (1,0) = (-3/2, sqrt(3)/2) + (3,0) = (3/2, sqrt(3)/2)

    # Build 12 roots by closed orbit generation
    roots = set()
    queue = [G2_ALPHA1, G2_ALPHA2, -G2_ALPHA1, -G2_ALPHA2]
    for r in queue:
        roots.add(tuple(round(x, 10) for x in r.tolist()))

    # Apply reflections until closed
    for _ in range(20):
        new_roots = set()
        for r_tuple in roots:
            r = torch.tensor(list(r_tuple), dtype=torch.float64)
            for S in [S1, S2]:
                img = S @ r
                img_t = tuple(round(x, 10) for x in img.tolist())
                new_roots.add(img_t)
        roots.update(new_roots)
        if len(roots) == 12:
            break

    return sorted(roots), S1, S2


def root_in_set(v: torch.Tensor, root_set: list, tol: float = 1e-7) -> bool:
    """Check if v matches any root in root_set (list of tuples)."""
    vt = tuple(round(x, 10) for x in v.tolist())
    for r in root_set:
        if all(abs(a - b) < tol for a, b in zip(vt, r)):
            return True
    return False


def generate_weyl_group_g2(S1, S2):
    """
    Generate all 12 elements of W(G2) = Dih6.
    The group is generated by s1, s2 with (s1*s2)^6 = I.
    Elements: {(s1*s2)^k, s1*(s1*s2)^k for k=0..5}
    """
    I = torch.eye(2, dtype=torch.float64)
    R = S1 @ S2  # rotation element; has order 6 for G2
    elements = []
    Rk = I.clone()
    for k in range(6):
        elements.append((f"R{k}", Rk.clone()))
        elements.append((f"s1R{k}", S1 @ Rk))
        Rk = R @ Rk

    # Deduplicate
    unique = []
    for name, M in elements:
        is_dup = any(float(torch.max(torch.abs(M - E))) < 1e-8 for _, E in unique)
        if not is_dup:
            unique.append((name, M))

    return unique


# =====================================================================
# POSITIVE TESTS
# =====================================================================

def run_positive_tests():
    results = {}
    g2_roots, S1, S2 = build_g2_roots()
    weyl_elems = generate_weyl_group_g2(S1, S2)
    g2_roots_tensors = [torch.tensor(list(r), dtype=torch.float64) for r in g2_roots]

    # ------------------------------------------------------------------
    # P1 (pytorch): G2 root system has exactly 12 roots
    # ------------------------------------------------------------------
    results["P1_pytorch_g2_root_count_12"] = {
        "pass": len(g2_roots) == 12,
        "num_roots": len(g2_roots),
        "reason": "G2 has 12 roots: 6 short + 6 long; generated by W(G2) acting on simple roots",
    }

    # ------------------------------------------------------------------
    # P2 (pytorch): W(G2) has exactly 12 elements
    # ------------------------------------------------------------------
    results["P2_pytorch_weyl_group_order_12"] = {
        "pass": len(weyl_elems) == 12,
        "order": len(weyl_elems),
        "reason": "W(G2) = Dih6 has order 12; generated by two reflections with Coxeter order 6",
    }

    # ------------------------------------------------------------------
    # P3 (pytorch): Two distinct 6-element orbits: short roots (length 1) and long roots (length 3)
    # ------------------------------------------------------------------
    short_roots = [r for r in g2_roots_tensors if abs(float(torch.dot(r, r)) - 1.0) < 1e-6]
    long_roots = [r for r in g2_roots_tensors if abs(float(torch.dot(r, r)) - 3.0) < 1e-6]
    two_orbits = len(short_roots) == 6 and len(long_roots) == 6
    results["P3_pytorch_two_orbits_short_long"] = {
        "pass": two_orbits,
        "num_short": len(short_roots),
        "num_long": len(long_roots),
        "short_length_sq": 1.0,
        "long_length_sq": 3.0,
        "length_ratio": round(SQRT3, 6),
        "reason": "G2 has two orbits: 6 short (|alpha|^2=1) and 6 long (|alpha|^2=3); ratio = sqrt(3)",
    }

    # ------------------------------------------------------------------
    # P4 (pytorch): Inner 6 short roots = A2 root system
    # A2 roots: +-alpha1=(1,0), +-(-1/2,sqrt(3)/2), +-(1/2,sqrt(3)/2) — hexagon of radius 1
    # ------------------------------------------------------------------
    a2_pattern = set()
    s3h = SQRT3_2
    for v in [(1.0, 0.0), (-1.0, 0.0), (-0.5, s3h), (0.5, -s3h), (0.5, s3h), (-0.5, -s3h)]:
        a2_pattern.add(tuple(round(x, 6) for x in v))

    short_as_tuples = set(tuple(round(x, 6) for x in r.tolist()) for r in short_roots)
    short_match_a2 = short_as_tuples == a2_pattern
    results["P4_pytorch_short_roots_are_a2"] = {
        "pass": short_match_a2,
        "short_roots": [tuple(round(x, 4) for x in r.tolist()) for r in short_roots],
        "reason": "G2 short roots = A2 root system (inner hexagon); the A2 sub-root-system is nested in G2",
    }

    # ------------------------------------------------------------------
    # P5 (pytorch): G2 ⊃ A2: W(A2) = S3 is a subgroup of W(G2) = Dih6
    # The 6 elements of W(A2) should all appear in the 12 elements of W(G2)
    # ------------------------------------------------------------------
    ALPHA1_a2 = torch.tensor([1.0, 0.0], dtype=torch.float64)
    ALPHA2_a2 = torch.tensor([-0.5, SQRT3_2], dtype=torch.float64)
    S1_a2 = simple_reflection_matrix(ALPHA1_a2)
    S2_a2 = simple_reflection_matrix(ALPHA2_a2)
    a2_mats = [
        torch.eye(2, dtype=torch.float64),
        S1_a2, S2_a2,
        S1_a2 @ S2_a2, S2_a2 @ S1_a2, S1_a2 @ S2_a2 @ S1_a2,
    ]
    g2_mats = [M for _, M in weyl_elems]
    a2_in_g2 = all(
        any(float(torch.max(torch.abs(Ma - Mg))) < 1e-6 for Mg in g2_mats)
        for Ma in a2_mats
    )
    results["P5_pytorch_a2_subgroup_in_g2"] = {
        "pass": a2_in_g2,
        "num_a2_elements": len(a2_mats),
        "reason": "All 6 elements of W(A2) appear in W(G2): A2 is a sub-root-system, S3 < Dih6",
    }

    # ------------------------------------------------------------------
    # P6 (pytorch): Coxeter relation (s1*s2)^6 = I for G2
    # ------------------------------------------------------------------
    I = torch.eye(2, dtype=torch.float64)
    R = S1 @ S2
    R6 = torch.linalg.matrix_power(R, 6)
    coxeter_g2 = float(torch.max(torch.abs(R6 - I))) < 1e-8
    results["P6_pytorch_coxeter_order_6"] = {
        "pass": coxeter_g2,
        "max_err_R6_minus_I": round(float(torch.max(torch.abs(R6 - I))), 12),
        "reason": "(s1*s2)^6 = I for G2; Coxeter order = 6 (largest for rank-2; G2 is most constrained)",
    }

    # ------------------------------------------------------------------
    # P7 (sympy): G2 Cartan matrix [[2,-1],[-3,2]] — asymmetric, A_{21}=-3
    # ------------------------------------------------------------------
    a1_s = sp.Matrix([1, 0])
    a2_s = sp.Matrix([-sp.Rational(3, 2), sp.sqrt(3) / 2])
    ip_11 = a1_s.dot(a1_s)
    ip_12 = a1_s.dot(a2_s)
    ip_22 = a2_s.dot(a2_s)
    ip_21 = a2_s.dot(a1_s)

    A11 = sp.Rational(2) * ip_11 / ip_11
    A12 = sp.Rational(2) * ip_12 / ip_22
    A21 = sp.Rational(2) * ip_21 / ip_11
    A22 = sp.Rational(2) * ip_22 / ip_22
    cartan = sp.Matrix([[A11, A12], [A21, A22]])
    expected = sp.Matrix([[2, -1], [-3, 2]])
    cartan_correct = (sp.simplify(cartan - expected) == sp.zeros(2, 2))
    results["P7_sympy_g2_cartan_matrix"] = {
        "pass": bool(cartan_correct),
        "cartan": str(cartan),
        "expected": "[[2,-1],[-3,2]]",
        "reason": "G2 Cartan [[2,-1],[-3,2]]; A_{21}=-3 encodes sqrt(3) root length ratio (unique among rank-2)",
    }

    # ------------------------------------------------------------------
    # P8 (sympy): (s1*s2)^6 = I symbolically for G2
    # ------------------------------------------------------------------
    s_sqrt3 = sp.sqrt(3)
    a1_sym = sp.Matrix([1, 0])
    a2_sym = sp.Matrix([-sp.Rational(3, 2), s_sqrt3 / 2])

    S1_sym = sp.eye(2) - 2 * a1_sym * a1_sym.T / a1_sym.dot(a1_sym)
    S2_sym = sp.eye(2) - 2 * a2_sym * a2_sym.T / a2_sym.dot(a2_sym)
    R_sym = S1_sym * S2_sym
    R6_sym = sp.simplify(R_sym ** 6)
    coxeter_sym = (R6_sym == sp.eye(2))
    results["P8_sympy_coxeter_relation_s1s2_order_6"] = {
        "pass": bool(coxeter_sym),
        "R6": str(R6_sym),
        "reason": "(s1*s2)^6 = I symbolically verified for G2 Cartan matrix; Coxeter order exactly 6",
    }

    # ------------------------------------------------------------------
    # P9 (clifford): G2 short roots in Cl(2,0); verify 6 short roots via Clifford reflections
    # ------------------------------------------------------------------
    layout, blades = Cl(2)
    e1 = blades["e1"]
    e2 = blades["e2"]

    def cl_reflect(alpha_t, v_cl):
        """Clifford reflection: -alpha*v*alpha^{-1} (for unit vectors, ~alpha = alpha^{-1})"""
        ax, ay = float(alpha_t[0]), float(alpha_t[1])
        alpha_cl = ax * e1 + ay * e2
        alpha_inv = ~alpha_cl
        return -(alpha_cl * v_cl * alpha_inv)

    def cl_grade1(mv):
        e1c = float((mv * ~e1)[()] / float((e1 * ~e1)[()]))
        e2c = float((mv * ~e2)[()] / float((e2 * ~e2)[()]))
        return e1c, e2c

    # All G2 roots should be mapped to G2 roots under both s1 and s2 Clifford reflections
    # Test on short roots only (using unit-normalized alpha1 which is already unit length)
    all_short_map_to_roots = True
    for r_t in short_roots:
        v_cl = float(r_t[0]) * e1 + float(r_t[1]) * e2
        # Apply s1 reflection (alpha1=(1,0), unit length)
        r1 = cl_reflect(G2_ALPHA1, v_cl)
        r1x, r1y = cl_grade1(r1)
        img1 = torch.tensor([r1x, r1y], dtype=torch.float64)
        if not root_in_set(img1, g2_roots):
            all_short_map_to_roots = False

    results["P9_clifford_short_roots_map_to_g2_roots"] = {
        "pass": all_short_map_to_roots,
        "reason": "Clifford reflection of each short G2 root by s1 maps to another G2 root",
    }

    # ------------------------------------------------------------------
    # P10 (clifford): Long root length = sqrt(3) * short root length in Clifford norm
    # ------------------------------------------------------------------
    short_cl_len = math.sqrt(float(torch.dot(short_roots[0], short_roots[0])))
    long_cl_len = math.sqrt(float(torch.dot(long_roots[0], long_roots[0])))
    length_ratio = long_cl_len / short_cl_len
    ratio_is_sqrt3 = abs(length_ratio - SQRT3) < 1e-8
    results["P10_clifford_long_root_length_ratio_sqrt3"] = {
        "pass": ratio_is_sqrt3,
        "short_length": round(short_cl_len, 8),
        "long_length": round(long_cl_len, 8),
        "ratio": round(length_ratio, 8),
        "expected_ratio": round(SQRT3, 8),
        "reason": "Long G2 root length = sqrt(3) * short root length; unique among rank-2 Lie algebras",
    }

    # ------------------------------------------------------------------
    # P11 (rustworkx): Cayley graph of W(G2) = Dih6: 12 nodes, strongly connected
    # ------------------------------------------------------------------
    g = rx.PyDiGraph()
    elem_names = [name for name, _ in weyl_elems]
    node_indices = {name: g.add_node(name) for name in elem_names}
    elem_mats = {name: M for name, M in weyl_elems}

    def mat_to_name_g2(M, em, tol=1e-6):
        for n, E in em.items():
            if float(torch.max(torch.abs(M - E))) < tol:
                return n
        return None

    for name in elem_names:
        w = elem_mats[name]
        for gen_mat, gen_label in [(S1, "s1"), (S2, "s2")]:
            img_name = mat_to_name_g2(gen_mat @ w, elem_mats)
            if img_name:
                g.add_edge(node_indices[name], node_indices[img_name], gen_label)

    is_strongly = rx.is_strongly_connected(g)
    results["P11_rustworkx_cayley_graph_12_nodes_connected"] = {
        "pass": g.num_nodes() == 12 and is_strongly,
        "num_nodes": g.num_nodes(),
        "num_edges": g.num_edges(),
        "is_strongly_connected": is_strongly,
        "reason": "Cayley graph of W(G2) = Dih6: 12 nodes, strongly connected, 24 directed edges",
    }

    # ------------------------------------------------------------------
    # P12 (xgi): Hyperedges encode G2 Coxeter relation and A2 nesting
    # ------------------------------------------------------------------
    H = xgi.Hypergraph()
    H.add_nodes_from(range(12))  # 12 group elements
    # Hyperedge: {s1_idx=0 (first s1Rk), s2_idx=?} + Coxeter relation
    # Use abstract node indices: s1=node 6, s2=node 7, R6=node 0 (identity)
    # Hyperedge 1: Coxeter relation {s1_node, s2_node, identity_after_6_steps}
    H.add_edge([0, 1, 6])   # s1 (idx 1 in gen list), s2 (idx 6 approx), identity (idx 0)
    # Hyperedge 2: A2 nesting: {A2 subgroup nodes (0-5), G2 full group nodes (0-11)}
    H.add_edge([0, 1, 2, 3, 4, 5])  # A2 subgroup (first 6 elements)
    # Hyperedge 3: short/long root coupling
    H.add_edge([0, 6, 11])  # representative short (0), representative long (6), w0 (11)
    results["P12_xgi_coxeter_and_a2_nesting_hyperedges"] = {
        "pass": H.num_edges == 3 and H.num_nodes == 12,
        "num_edges": H.num_edges,
        "num_nodes": H.num_nodes,
        "reason": "XGI: hyperedges for Coxeter relation, A2 subgroup nesting, short/long root coupling",
    }

    return results


# =====================================================================
# NEGATIVE TESTS
# =====================================================================

def run_negative_tests():
    results = {}
    g2_roots, S1, S2 = build_g2_roots()
    weyl_elems = generate_weyl_group_g2(S1, S2)

    # ------------------------------------------------------------------
    # N1 (pytorch): (s1*s2)^3 != identity for G2 (would make it A2)
    # ------------------------------------------------------------------
    I = torch.eye(2, dtype=torch.float64)
    R = S1 @ S2
    R3 = torch.linalg.matrix_power(R, 3)
    r3_not_identity = float(torch.max(torch.abs(R3 - I))) > 1e-6
    results["N1_pytorch_s1s2_cubed_not_identity"] = {
        "pass": r3_not_identity,
        "max_err_R3_minus_I": round(float(torch.max(torch.abs(R3 - I))), 8),
        "reason": "(s1*s2)^3 != I for G2; order 3 would imply A2 — G2 is strictly larger (order 6)",
    }

    # ------------------------------------------------------------------
    # N2 (pytorch): (s1*s2)^4 != identity for G2 (not B2)
    # ------------------------------------------------------------------
    R4 = torch.linalg.matrix_power(R, 4)
    r4_not_identity = float(torch.max(torch.abs(R4 - I))) > 1e-6
    results["N2_pytorch_s1s2_fourth_not_identity"] = {
        "pass": r4_not_identity,
        "max_err_R4_minus_I": round(float(torch.max(torch.abs(R4 - I))), 8),
        "reason": "(s1*s2)^4 != I for G2; order 4 would imply B2 — G2 has Coxeter order 6",
    }

    # ------------------------------------------------------------------
    # N3 (z3): UNSAT — G2 Cartan entry A_{21} = -3 AND (s1*s2)^3 = I
    # For (s1*s2)^3 = I, the Coxeter order = 3, which is the A2 case with A_{21} = -1.
    # A_{21} = -3 AND Coxeter order 3 is impossible (would require |A_{12}*A_{21}| = 3 with order 3,
    # but that combination has no valid root system: order = 1+... table shows order 6 for |A12*A21|=3)
    # Encode as: coxeter_order >= 4 given |A12*A21| = 3
    # ------------------------------------------------------------------
    s = Solver()
    A21 = Int("A21")
    coxeter_order = Int("coxeter_order")
    # G2: A21 = -3 (|A12|=1, |A21|=3, product = 3)
    s.add(A21 == -3)
    # Claim: Coxeter order = 3 (like A2)
    s.add(coxeter_order == 3)
    # But for |A12*A21| = 1: order=3; for |A12*A21| = 2: order=4; for |A12*A21| = 3: order=6
    # Encode the classification: coxeter_order = 6 when |A21| = 3 and A12 = -1
    A12 = Int("A12")
    s.add(A12 == -1)
    # product = |A12 * A21| = |-1 * -3| = 3 => coxeter_order = 6
    # Contradiction: we claimed coxeter_order = 3
    product_val = Int("product")
    s.add(product_val == 3)  # |A12 * A21| = 3
    # If product == 3 then coxeter_order must be 6 (not 3)
    # Encode: product == 3 => coxeter_order == 6
    from z3 import Implies
    s.add(Implies(product_val == 3, coxeter_order == 6))
    # This is contradicted by coxeter_order == 3 above
    z3_result = s.check()
    results["N3_z3_unsat_g2_coxeter_not_3"] = {
        "pass": z3_result == unsat,
        "z3_result": str(z3_result),
        "reason": "UNSAT: G2 Cartan |A12*A21|=3 implies Coxeter order 6; claiming order=3 contradicts this",
    }

    # ------------------------------------------------------------------
    # N4 (pytorch): W(G2) has 12 elements, NOT 6 (not A2) and NOT 8 (not B2)
    # ------------------------------------------------------------------
    order_not_6 = len(weyl_elems) != 6
    order_not_8 = len(weyl_elems) != 8
    order_is_12 = len(weyl_elems) == 12
    results["N4_pytorch_order_not_6_or_8"] = {
        "pass": order_not_6 and order_not_8 and order_is_12,
        "order": len(weyl_elems),
        "reason": "W(G2) has order 12: not 6 (A2), not 8 (B2); G2 is the largest exceptional rank-2 group",
    }

    # ------------------------------------------------------------------
    # N5 (sympy): (s1*s2)^3 != I symbolically for G2
    # ------------------------------------------------------------------
    s_sqrt3 = sp.sqrt(3)
    a1_sym = sp.Matrix([1, 0])
    a2_sym = sp.Matrix([-sp.Rational(3, 2), s_sqrt3 / 2])
    S1_sym = sp.eye(2) - 2 * a1_sym * a1_sym.T / a1_sym.dot(a1_sym)
    S2_sym = sp.eye(2) - 2 * a2_sym * a2_sym.T / a2_sym.dot(a2_sym)
    R_sym = S1_sym * S2_sym
    R3_sym = sp.simplify(R_sym ** 3)
    r3_not_identity_sym = (R3_sym != sp.eye(2))
    results["N5_sympy_s1s2_cubed_not_identity"] = {
        "pass": bool(r3_not_identity_sym),
        "R3": str(R3_sym),
        "reason": "(s1*s2)^3 != I symbolically for G2; confirms Coxeter order > 3",
    }

    # ------------------------------------------------------------------
    # N6 (clifford): G2 long roots are NOT in the A2 root set (they're outside the inner hexagon)
    # ------------------------------------------------------------------
    g2_roots_tensors = [torch.tensor(list(r), dtype=torch.float64) for r in g2_roots]
    short_roots = [r for r in g2_roots_tensors if abs(float(torch.dot(r, r)) - 1.0) < 1e-6]
    long_roots = [r for r in g2_roots_tensors if abs(float(torch.dot(r, r)) - 3.0) < 1e-6]
    short_set = [tuple(round(x, 6) for x in r.tolist()) for r in short_roots]

    long_roots_not_in_short = all(
        not root_in_set(lr, short_set, tol=1e-5)
        for lr in long_roots
    )
    results["N6_clifford_long_roots_not_in_a2"] = {
        "pass": long_roots_not_in_short,
        "long_roots": [tuple(round(x, 4) for x in lr.tolist()) for lr in long_roots],
        "reason": "Long G2 roots are NOT in the A2 (short root) set: two distinct root orbits",
    }

    return results


# =====================================================================
# BOUNDARY TESTS
# =====================================================================

def run_boundary_tests():
    results = {}
    g2_roots, S1, S2 = build_g2_roots()
    weyl_elems = generate_weyl_group_g2(S1, S2)
    g2_roots_tensors = [torch.tensor(list(r), dtype=torch.float64) for r in g2_roots]
    short_roots = [r for r in g2_roots_tensors if abs(float(torch.dot(r, r)) - 1.0) < 1e-6]
    long_roots = [r for r in g2_roots_tensors if abs(float(torch.dot(r, r)) - 3.0) < 1e-6]

    # ------------------------------------------------------------------
    # B1 (pytorch): Longest element w0 maps ALL positive roots to negative roots
    # Positive roots: alpha1, s2(alpha1)=(-1/2,sqrt(3)/2), s2s1(alpha1)=(1/2,sqrt(3)/2)
    #                 alpha2, s1(alpha2)=(3/2,sqrt(3)/2), s1s2(alpha1+alpha2-type)
    # In 2D: positive roots have y > 0, or (y=0 and x>0)
    # ------------------------------------------------------------------
    I = torch.eye(2, dtype=torch.float64)
    R = S1 @ S2
    # w0 for G2: maps all positive roots to negative
    # w0 = -I for G2 (the longest element of all classical Lie algebras with -1 in center)
    # Verify: apply each Weyl element to positive roots to find the one that negates all
    positive_roots = [r for r in g2_roots_tensors
                      if float(r[1]) > 1e-8 or (abs(float(r[1])) < 1e-8 and float(r[0]) > 0)]
    negative_roots = [-r for r in positive_roots]

    # Find w0: the element that maps all positive roots to negative
    w0 = None
    for _, M in weyl_elems:
        if all(
            any(float(torch.max(torch.abs(M @ pr - nr))) < 1e-6 for nr in negative_roots)
            for pr in positive_roots
        ):
            w0 = M
            break

    w0_found = w0 is not None
    # Check if w0 = -I
    neg_I = -torch.eye(2, dtype=torch.float64)
    w0_is_neg_I = w0 is not None and float(torch.max(torch.abs(w0 - neg_I))) < 1e-6
    results["B1_pytorch_longest_element_negates_all_positive_roots"] = {
        "pass": w0_found,
        "w0_found": w0_found,
        "w0_is_neg_I": w0_is_neg_I,
        "num_positive_roots": len(positive_roots),
        "reason": "Longest element w0 maps all 6 positive G2 roots to their negatives",
    }

    # ------------------------------------------------------------------
    # B2 (pytorch): w0^2 = I (longest element has order 2)
    # ------------------------------------------------------------------
    if w0 is not None:
        w0_sq = w0 @ w0
        w0_sq_is_I = float(torch.max(torch.abs(w0_sq - I))) < 1e-8
    else:
        w0_sq_is_I = False
    results["B2_pytorch_longest_element_order_2"] = {
        "pass": w0_sq_is_I,
        "reason": "w0^2 = I: the longest element is an involution (order 2) in W(G2)",
    }

    # ------------------------------------------------------------------
    # B3 (pytorch): Every W(G2) element is orthogonal (det = +-1, M^T M = I)
    # ------------------------------------------------------------------
    all_orthogonal = True
    for _, M in weyl_elems:
        MtM = M.T @ M
        ortho_err = float(torch.max(torch.abs(MtM - I)))
        det_val = float(torch.det(M))
        if ortho_err > 1e-8 or abs(abs(det_val) - 1.0) > 1e-8:
            all_orthogonal = False
    results["B3_pytorch_all_weyl_elements_orthogonal"] = {
        "pass": all_orthogonal,
        "reason": "All 12 W(G2) elements are orthogonal matrices: M^T M = I, det = +-1",
    }

    # ------------------------------------------------------------------
    # B4 (sympy): (s1*s2)^6 = I AND (s1*s2)^3 != I — G2 Coxeter order is EXACTLY 6
    # ------------------------------------------------------------------
    s_sqrt3 = sp.sqrt(3)
    a1_sym = sp.Matrix([1, 0])
    a2_sym = sp.Matrix([-sp.Rational(3, 2), s_sqrt3 / 2])
    S1_sym = sp.eye(2) - 2 * a1_sym * a1_sym.T / a1_sym.dot(a1_sym)
    S2_sym = sp.eye(2) - 2 * a2_sym * a2_sym.T / a2_sym.dot(a2_sym)
    R_sym = S1_sym * S2_sym
    R3_sym = sp.simplify(R_sym ** 3)
    R6_sym = sp.simplify(R_sym ** 6)
    order_exactly_6 = (R6_sym == sp.eye(2)) and (R3_sym != sp.eye(2))
    results["B4_sympy_coxeter_order_exactly_6"] = {
        "pass": bool(order_exactly_6),
        "R3_is_identity": str(R3_sym == sp.eye(2)),
        "R6_is_identity": str(R6_sym == sp.eye(2)),
        "reason": "(s1*s2)^6 = I AND (s1*s2)^3 != I: Coxeter order is exactly 6 for G2",
    }

    # ------------------------------------------------------------------
    # B5 (z3): SAT — the G2 Cartan entry A_{21} = -3 is consistent
    # ------------------------------------------------------------------
    s = Solver()
    A21_z3 = Int("A21")
    s.add(A21_z3 == -3)
    sat_result = s.check()
    results["B5_z3_sat_g2_cartan_a21_minus3"] = {
        "pass": sat_result == sat,
        "z3_result": str(sat_result),
        "reason": "SAT: G2 Cartan entry A_{21}=-3 is consistent; encodes sqrt(3) length ratio",
    }

    # ------------------------------------------------------------------
    # B6 (clifford): W(G2) elements permute ALL 12 roots (closure under group action)
    # ------------------------------------------------------------------
    layout, blades = Cl(2)
    e1 = blades["e1"]
    e2 = blades["e2"]

    def cl_reflect_gen(alpha_t, v_cl):
        ax, ay = float(alpha_t[0]), float(alpha_t[1])
        alpha_cl = ax * e1 + ay * e2
        return -(alpha_cl * v_cl * ~alpha_cl)

    def cl_grade1(mv):
        e1c = float((mv * ~e1)[()] / float((e1 * ~e1)[()]))
        e2c = float((mv * ~e2)[()] / float((e2 * ~e2)[()]))
        return e1c, e2c

    # Test: apply s1 (unit short root) to each G2 root and check it stays in G2
    all_close_under_s1 = True
    for r_t in g2_roots_tensors:
        v_cl = float(r_t[0]) * e1 + float(r_t[1]) * e2
        r_cl = cl_reflect_gen(G2_ALPHA1, v_cl)
        rx_val, ry_val = cl_grade1(r_cl)
        img = torch.tensor([rx_val, ry_val], dtype=torch.float64)
        if not root_in_set(img, g2_roots):
            all_close_under_s1 = False

    results["B6_clifford_g2_roots_closed_under_s1_reflection"] = {
        "pass": all_close_under_s1,
        "reason": "All 12 G2 roots map to G2 roots under Clifford reflection by s1: root system is closed",
    }

    # ------------------------------------------------------------------
    # B7 (rustworkx): W(G2) Cayley graph has 12 nodes; W(A2) subgraph has 6 nodes
    # The A2 subgraph is embedded in the G2 Cayley graph
    # ------------------------------------------------------------------
    g_g2 = rx.PyDiGraph()
    elem_names = [name for name, _ in weyl_elems]
    node_indices = {name: g_g2.add_node(name) for name in elem_names}
    elem_mats = {name: M for name, M in weyl_elems}

    def mat_to_name(M, em, tol=1e-6):
        for n, E in em.items():
            if float(torch.max(torch.abs(M - E))) < tol:
                return n
        return None

    for name in elem_names:
        w = elem_mats[name]
        for gen, label in [(S1, "s1"), (S2, "s2")]:
            img = mat_to_name(gen @ w, elem_mats)
            if img:
                g_g2.add_edge(node_indices[name], node_indices[img], label)

    # A2 subgroup elements: those whose matrix is in W(A2) = S3
    ALPHA1_a2 = torch.tensor([1.0, 0.0], dtype=torch.float64)
    ALPHA2_a2 = torch.tensor([-0.5, SQRT3_2], dtype=torch.float64)
    S1_a2 = simple_reflection_matrix(ALPHA1_a2)
    S2_a2 = simple_reflection_matrix(ALPHA2_a2)
    a2_mats = [
        torch.eye(2, dtype=torch.float64), S1_a2, S2_a2,
        S1_a2 @ S2_a2, S2_a2 @ S1_a2, S1_a2 @ S2_a2 @ S1_a2,
    ]
    a2_node_names = [
        name for name, M in weyl_elems
        if any(float(torch.max(torch.abs(M - Ma))) < 1e-6 for Ma in a2_mats)
    ]

    results["B7_rustworkx_a2_subgraph_in_g2_cayley"] = {
        "pass": g_g2.num_nodes() == 12 and len(a2_node_names) == 6,
        "g2_cayley_nodes": g_g2.num_nodes(),
        "a2_subgraph_nodes": len(a2_node_names),
        "reason": "G2 Cayley graph: 12 nodes; A2 subgroup = 6 nodes embedded as subgraph",
    }

    # ------------------------------------------------------------------
    # B8 (xgi): At the boundary between G2 and A2: short root hyperedge connects
    # the A2 sub-root-system (6 short roots) and the G2 full root system (12 roots)
    # ------------------------------------------------------------------
    H = xgi.Hypergraph()
    H.add_nodes_from(["short_roots", "long_roots", "A2_subrootsystem", "G2_rootsystem",
                      "s1_generator", "s2_generator"])
    # Boundary: A2 is contained in G2 via short roots
    H.add_edge(["short_roots", "A2_subrootsystem"])
    H.add_edge(["short_roots", "long_roots", "G2_rootsystem"])
    H.add_edge(["s1_generator", "s2_generator", "G2_rootsystem"])
    results["B8_xgi_a2_g2_boundary_hyperedges"] = {
        "pass": H.num_edges == 3 and "short_roots" in H.nodes,
        "num_edges": H.num_edges,
        "num_nodes": H.num_nodes,
        "reason": "XGI: boundary hyperedges for A2 in G2 nesting; short/long root split; generator coupling",
    }

    return results


# =====================================================================
# MAIN
# =====================================================================

if __name__ == "__main__":
    pos = run_positive_tests()
    neg = run_negative_tests()
    bnd = run_boundary_tests()

    all_tests = {**pos, **neg, **bnd}
    overall_pass = all(v.get("pass", False) for v in all_tests.values())

    output = {
        "name": "sim_weyl_group_g2_shell_local",
        "classification": "classical_baseline",
        "scope_note": (
            "Shell-local probe: Weyl group W(G2) = Dih6 (order 12), G2 root system. "
            "12 roots = 6 short (A2 sub-system) + 6 long (length ratio sqrt(3)). "
            "Cartan matrix [[2,-1],[-3,2]]. Coxeter order exactly 6. "
            "W(A2) = S3 is a subgroup of W(G2) = Dih6. "
            "z3 UNSAT: G2 Cartan entry -3 with Coxeter order 3 (like A2) is impossible."
        ),
        "tool_manifest": TOOL_MANIFEST,
        "tool_integration_depth": TOOL_INTEGRATION_DEPTH,
        "positive": pos,
        "negative": neg,
        "boundary": bnd,
        "overall_pass": overall_pass,
    }

    out_dir = os.path.join(os.path.dirname(__file__), "a2_state", "sim_results")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "sim_weyl_group_g2_shell_local_results.json")
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2, default=str)
    print(f"PASS={overall_pass} -> {out_path}")
