#!/usr/bin/env python3
"""
Layer 1 Validation SIM — Two Loop Families
============================================
Pure topology. No operators. No dynamics.

From the source doc:
  "On S³, there are two inequivalent 1-cycle families
   that exist independently of dynamics."

Loop A — Hopf fiber loop (vertical/inner):
  ψ → e^{iθ}ψ
  - Closes after 360°
  - Does NOT change Bloch vector
  - Pure circulation, no transport
  - Generated by center of SU(2)

Loop B — Lifted base loop (horizontal/outer):
  - Loop on S² lifted into S³
  - 360° does NOT close in SU(2)
  - Requires 720° for closure
  - Changes the Bloch vector
  - Carries Berry phase / holonomy

These two loop families are:
  - topologically distinct
  - not deformable into one another
  - both unavoidable features of S³

Token: E_LOOP_FAMILIES_VALID
"""

import numpy as np
import os
import sys
import json
from datetime import datetime, UTC
classification = "classical_baseline"  # auto-backfill

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from hopf_manifold import (
    random_s3_point, is_on_s3,
    hopf_map,
    fiber_action, sample_fiber,
    lift_base_point, base_loop_point, lifted_base_loop,
    berry_phase,
    coherent_state_density, density_to_bloch,
)
from proto_ratchet_sim_runner import EvidenceToken


def run_L1_validation():
    print("=" * 72)
    print("LAYER 1: TWO LOOP FAMILIES VALIDATION")
    print("  'Two inequivalent 1-cycle families on S³'")
    print("=" * 72)

    rng = np.random.default_rng(42)
    all_pass = True
    results = {}

    # ── Test 1: Fiber loop is pure circulation (no Bloch change) ──
    print("\n  [T1] Fiber loop: pure circulation...")
    fiber_pure = True
    max_bloch_dev = 0.0
    n_trials = 50
    for _ in range(n_trials):
        q = random_s3_point(rng)
        p_base = hopf_map(q)
        fiber = sample_fiber(q, 64)
        for q_f in fiber:
            p_f = hopf_map(q_f)
            dev = np.linalg.norm(p_base - p_f)
            max_bloch_dev = max(max_bloch_dev, dev)
            if dev > 1e-10:
                fiber_pure = False
    results["fiber_no_bloch_change"] = bool(fiber_pure)
    results["fiber_max_bloch_dev"] = float(max_bloch_dev)
    print(f"    {'✓' if fiber_pure else '✗'} Bloch vector unchanged along fiber")
    print(f"      Max deviation: {max_bloch_dev:.2e}")
    all_pass = all_pass and fiber_pure

    # ── Test 2: Fiber loop has zero Berry phase ──────────────────
    print("\n  [T2] Fiber loop: zero Berry phase...")
    q0 = random_s3_point(rng)
    fiber_loop = sample_fiber(q0, 256)
    fiber_bp = berry_phase(fiber_loop)
    fiber_bp_zero = abs(fiber_bp) < 0.1
    results["fiber_berry_phase"] = float(fiber_bp)
    results["fiber_bp_zero"] = bool(fiber_bp_zero)
    print(f"    {'✓' if fiber_bp_zero else '✗'} Berry phase = {fiber_bp:.4f} rad (expected ≈ 0)")
    all_pass = all_pass and fiber_bp_zero

    # ── Test 3: Fiber loop closes after exactly 360° ─────────────
    print("\n  [T3] Fiber loop: 360° closure...")
    closure_ok = True
    for _ in range(50):
        q = random_s3_point(rng)
        # After 360°
        q_360 = fiber_action(q, 2 * np.pi)
        if np.linalg.norm(q - q_360) > 1e-10:
            closure_ok = False
        # After 180° — should NOT be back
        q_180 = fiber_action(q, np.pi)
        if np.linalg.norm(q - q_180) < 0.1:
            # Unless q was at a fixed point (which shouldn't exist)
            pass
    results["fiber_closes_360"] = bool(closure_ok)
    print(f"    {'✓' if closure_ok else '✗'} Fiber loop closes at θ = 2π")
    all_pass = all_pass and closure_ok

    # ── Test 4: Base loop changes Bloch vector ───────────────────
    print("\n  [T4] Base loop: changes Bloch vector...")
    # Generate a smooth great circle on S² via SU(2) σ_y rotation
    n_pts = 256
    base_loop_pts = []
    for i in range(n_pts):
        alpha = 2 * np.pi * i / n_pts
        ca = np.cos(alpha / 2)
        sa = np.sin(alpha / 2)
        q_rot = np.array([ca, 0.0, sa, 0.0])
        base_loop_pts.append(q_rot)
    base_loop_pts = np.array(base_loop_pts)

    bloch_vectors = np.array([hopf_map(q) for q in base_loop_pts])
    # Check that Bloch vectors actually move
    bloch_var = np.var(bloch_vectors, axis=0)
    bloch_changes = np.sum(bloch_var) > 0.1
    results["base_loop_bloch_changes"] = bool(bloch_changes)
    results["base_loop_bloch_variance"] = float(np.sum(bloch_var))
    print(f"    {'✓' if bloch_changes else '✗'} Bloch vector varies along base loop")
    print(f"      Variance: {np.sum(bloch_var):.4f}")
    all_pass = all_pass and bloch_changes

    # ── Test 5: Base loop 360° does NOT close in SU(2) ───────────
    print("\n  [T5] Base loop: 360° spinor non-closure (720° required)...")
    # After σ_y rotation by α = 2π:
    # exp(-iπσ_y) = [[-1, 0], [0, -1]] → quaternion (−1,0,0,0) = −|0⟩
    q_start = base_loop_pts[0]  # (1, 0, 0, 0)
    # The point at α just before 2π
    alpha_full = 2 * np.pi
    ca_full = np.cos(alpha_full / 2)  # cos(π) = -1
    sa_full = np.sin(alpha_full / 2)  # sin(π) = 0
    q_360 = np.array([ca_full, 0.0, sa_full, 0.0])  # (-1, 0, 0, 0)

    dist_same = np.linalg.norm(q_start - q_360)
    dist_neg = np.linalg.norm(q_start + q_360)
    sign_flip = dist_neg < dist_same  # True if q_360 ≈ -q_start

    # Verify: the same base point on S² but opposite spinor sign
    p_start = hopf_map(q_start)
    p_360 = hopf_map(q_360)
    base_same = np.linalg.norm(p_start - p_360) < 1e-10

    results["spinor_360_sign_flip"] = bool(sign_flip)
    results["base_360_same_point"] = bool(base_same)
    print(f"    {'✓' if sign_flip else '✗'} q(2π) ≈ −q(0): dist_same={dist_same:.4f}, dist_neg={dist_neg:.4f}")
    print(f"    {'✓' if base_same else '✗'} π(q(2π)) = π(q(0)): base point unchanged on S²")
    spinor_test_ok = sign_flip and base_same
    all_pass = all_pass and spinor_test_ok

    # ── Test 6: Base loop closes at 720° ─────────────────────────
    print("\n  [T6] Base loop: 720° closure...")
    alpha_720 = 4 * np.pi
    ca_720 = np.cos(alpha_720 / 2)  # cos(2π) = 1
    sa_720 = np.sin(alpha_720 / 2)  # sin(2π) = 0
    q_720 = np.array([ca_720, 0.0, sa_720, 0.0])  # (1, 0, 0, 0)
    dist_720 = np.linalg.norm(q_start - q_720)
    closes_720 = dist_720 < 1e-10
    results["spinor_closes_720"] = bool(closes_720)
    print(f"    {'✓' if closes_720 else '✗'} q(4π) = q(0): dist = {dist_720:.2e}")
    all_pass = all_pass and closes_720

    # ── Test 7: Base loop has non-zero Berry phase ───────────────
    print("\n  [T7] Base loop: non-zero Berry phase...")
    bp = berry_phase(base_loop_pts)
    bp_nonzero = abs(bp) > 0.1
    results["base_berry_phase"] = float(bp)
    results["base_bp_nonzero"] = bool(bp_nonzero)
    print(f"    {'✓' if bp_nonzero else '✗'} Berry phase = {bp:.4f} rad")
    print(f"      Great circle solid angle = 2π → expected |Berry| ≈ π")
    all_pass = all_pass and bp_nonzero

    # ── Test 8: Two loop families are topologically distinct ──────
    print("\n  [T8] Topological inequivalence...")
    # Key distinction: fiber loop Berry phase = 0, base loop Berry phase ≠ 0
    # This is the topological invariant that separates them
    distinct = fiber_bp_zero and bp_nonzero
    results["loops_topologically_distinct"] = bool(distinct)
    print(f"    {'✓' if distinct else '✗'} Fiber Berry = {fiber_bp:.4f}, Base Berry = {bp:.4f}")
    print(f"      Topological invariant (Berry phase) distinguishes loop families")

    # Also: fiber loop has trivial winding around S², base loop has non-trivial
    # Count winding by checking S² trajectory
    fiber_bloch = np.array([hopf_map(q) for q in fiber_loop])
    fiber_span = np.max(fiber_bloch, axis=0) - np.min(fiber_bloch, axis=0)
    base_bloch = bloch_vectors
    base_span = np.max(base_bloch, axis=0) - np.min(base_bloch, axis=0)

    fiber_trivial = np.max(fiber_span) < 1e-8  # Fiber: no S² motion
    base_nontrivial = np.max(base_span) > 0.5  # Base: substantial S² motion
    winding_distinct = fiber_trivial and base_nontrivial
    results["fiber_s2_trivial"] = bool(fiber_trivial)
    results["base_s2_nontrivial"] = bool(base_nontrivial)
    print(f"    {'✓' if winding_distinct else '✗'} Fiber S² span: {np.max(fiber_span):.2e}, Base S² span: {np.max(base_span):.4f}")
    all_pass = all_pass and distinct and winding_distinct

    # ── Verdict ───────────────────────────────────────────────────
    print(f"\n{'=' * 72}")
    print(f"  LAYER 1 VERDICT: {'PASS ✓' if all_pass else 'KILL ✗'}")
    print(f"{'=' * 72}")

    tokens = []
    if all_pass:
        tokens.append(EvidenceToken(
            "E_LOOP_FAMILIES_VALID", "S_L1_LOOP_FAMILIES",
            "PASS", 1.0
        ))
    else:
        failed = [k for k, v in results.items() if v is False]
        tokens.append(EvidenceToken(
            "", "S_L1_LOOP_FAMILIES", "KILL", 0.0,
            f"FAILED: {', '.join(failed)}"
        ))

    # Save
    base_dir = os.path.dirname(os.path.abspath(__file__))
    results_dir = os.path.join(base_dir, "a2_state", "sim_results")
    os.makedirs(results_dir, exist_ok=True)
    outpath = os.path.join(results_dir, "L1_loop_families_results.json")
    with open(outpath, "w") as f:
        json.dump({
            "timestamp": datetime.now(UTC).isoformat(),
            "layer": 1,
            "name": "Two_Loop_Families_Validation",
            "results": results,
            "evidence_ledger": [t.__dict__ for t in tokens],
        }, f, indent=2, default=str)
    print(f"  Results saved: {outpath}")
    return tokens


if __name__ == "__main__":
    run_L1_validation()
