#!/usr/bin/env python3
"""
Axis Exploration Suite: Redundancy, Disentanglement, and New Candidates
========================================================================

Three independent tests, each answerable by sim alone:

TEST 1: Is Axis 1 (CPTP vs Unitary) the same axis as Axis 5 (FGA vs FSA)?
  Method: Build cases where Ax1 changes but Ax5 is held fixed, and vice versa.
  If they're the same, you can't change one without changing the other.
  If they're distinct, there exist states where one changes and the other doesn't.

TEST 2: Can Axis 3 (±G) and Axis 6 (Aρ/ρA) be disentangled?
  Method: Build multiple candidate math formulations for Axis 3 and Axis 6.
  Test which formulations produce independent displacements.
  The commutator overlap may come from bad math, not real redundancy.

TEST 3: Is "outer/inner torus" (η) an independent axis?
  Method: Compute displacement for torus transport (η change) separately
  from Weyl chirality (±G) and from action side (Aρ/ρA).
  If outer/inner is orthogonal to both, it's a real independent axis.
"""

import numpy as np
import scipy.linalg as la
import json, os, sys
from datetime import datetime, UTC
classification = "classical_baseline"  # auto-backfill

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from hopf_manifold import (
        torus_coordinates, coherent_state_density,
        left_weyl_spinor, right_weyl_spinor,
        left_density, right_density,
        fiber_phase_left, fiber_phase_right,
        TORUS_INNER, TORUS_CLIFFORD, TORUS_OUTER,
    )
    HAS_HOPF = True
except ImportError:
    HAS_HOPF = False

try:
    from proto_ratchet_sim_runner import make_random_density_matrix
except ImportError:
    def make_random_density_matrix(d):
        A = np.random.randn(d, d) + 1j * np.random.randn(d, d)
        rho = A @ A.conj().T
        return rho / np.trace(rho)


def normalized_overlap(A, B):
    """Hilbert-Schmidt normalized overlap |Tr(A†B)| / (||A||·||B||)"""
    nA = np.linalg.norm(A, 'fro')
    nB = np.linalg.norm(B, 'fro')
    if nA < 1e-12 or nB < 1e-12:
        return 0.0
    return float(abs(np.trace(A.conj().T @ B)) / (nA * nB))


# ═══════════════════════════════════════════════════════════════════
# TEST 1: Ax1 vs Ax5 — Same axis or distinct?
# ═══════════════════════════════════════════════════════════════════

def test1_ax1_vs_ax5():
    """
    Ax1 = channel class (CPTP vs Unitary)
    Ax5 = algebra class (FGA/Lindblad vs FSA/Hamiltonian)
    
    Question: Can you have a CPTP channel that uses FSA math?
              Can you have a unitary channel that uses FGA math?
    
    If YES → distinct axes. If NO → same axis.
    
    Math:
      Unitary + FSA: ρ → UρU†, U = exp(-iHt)     [standard]
      Unitary + FGA: ρ → UρU†, by engineering L_k  [possible: L=0 in Lindblad]
      CPTP + FSA: impossible (CPTP with Hamiltonian only = unitary)
      CPTP + FGA: ρ → Σ LρL†, L_k ≠ 0             [standard]
      
    So the question is: is Ax1×Ax5 a 2×2 grid (4 cells)
    or a degenerate 1D line (2 cells)?
    """
    print("=" * 70)
    print("TEST 1: Is Axis 1 (CPTP/Unitary) = Axis 5 (FGA/FSA)?")
    print("=" * 70)
    
    d = 8
    n_trials = 200
    
    # Case analysis
    print("\n  Can these 4 cells be populated?")
    print("  ┌────────────┬──────────┬──────────┐")
    print("  │            │ FSA      │ FGA      │")
    print("  ├────────────┼──────────┼──────────┤")
    print("  │ Unitary    │    ?     │    ?     │")
    print("  │ CPTP       │    ?     │    ?     │")
    print("  └────────────┴──────────┴──────────┘")
    
    # Unitary + FSA: ρ → exp(-iHt) ρ exp(iHt)
    # This is the standard case. Always works.
    unitary_fsa_works = True
    
    # CPTP + FGA: ρ → Σ L_k ρ L_k† (general Lindblad)
    # Standard case. Always works.
    cptp_fga_works = True
    
    # Unitary + FGA: can a Lindblad generator produce unitary dynamics?
    # Yes: set all L_k = 0, keep only -i[H,ρ] part
    # BUT then it's not really "FGA" — the dissipative part is trivial
    # Alternative: L_k = cU_k where Σ|c|²U_k U_k† = I (unitary channel from Kraus)
    # A unitary channel IS a special CPTP map. So it CAN be expressed in FGA form.
    # But the GENERATOR is trivial (semigroup collapses to group).
    unitary_fga_degenerate = True  # possible but degenerate
    
    # CPTP + FSA: can Hamiltonian evolution produce non-unitary dynamics?
    # Only if the system is OPEN (coupled to bath via Hamiltonian on larger space)
    # In the REDUCED system, this appears as CPTP but is generated by FSA on composite
    # This is the Stinespring dilation — CPTP = partial trace of unitary
    cptp_fsa_via_dilation = True  # possible via Stinespring
    
    # Measure independence by constructing a non-degenerate Ax1×Ax5 grid
    grid_overlaps = np.zeros((2, 2))
    
    for trial in range(n_trials):
        np.random.seed(trial + 7000)
        rho = make_random_density_matrix(d)
        
        # Ax1 displacement: CPTP − Unitary (fixed generator structure)
        H = np.random.randn(d, d) + 1j * np.random.randn(d, d)
        H = (H + H.conj().T) / 2
        dt = 0.3
        U = la.expm(-1j * H * dt)
        rho_unitary = U @ rho @ U.conj().T
        
        L = np.zeros((d, d), dtype=complex)
        for k in range(d-1):
            L[k, k+1] = 0.3
        rho_cptp = (L @ rho @ L.conj().T 
                    + (np.eye(d) - 0.5 * L.conj().T @ L) @ rho 
                    + rho @ (np.eye(d) - 0.5 * L.conj().T @ L))
        rho_cptp = (rho_cptp + rho_cptp.conj().T) / 2
        evals, evecs = np.linalg.eigh(rho_cptp)
        evals = np.maximum(evals, 0)
        rho_cptp = evecs @ np.diag(evals) @ evecs.conj().T
        rho_cptp /= np.trace(rho_cptp)
        
        delta_ax1 = rho_cptp - rho_unitary
        
        # Ax5 displacement: FGA − FSA (same channel class)
        # FGA branch: use the Lindblad from above
        lind = (L @ rho @ L.conj().T 
                - 0.5 * (L.conj().T @ L @ rho + rho @ L.conj().T @ L))
        rho_fga = rho + lind * dt
        rho_fga = (rho_fga + rho_fga.conj().T) / 2
        evals2, evecs2 = np.linalg.eigh(rho_fga)
        evals2 = np.maximum(evals2, 0)
        rho_fga = evecs2 @ np.diag(evals2) @ evecs2.conj().T
        rho_fga /= np.trace(rho_fga)
        
        # FSA branch: pure Hamiltonian
        rho_fsa = U @ rho @ U.conj().T
        
        delta_ax5 = rho_fga - rho_fsa
        
        ov = normalized_overlap(delta_ax1, delta_ax5)
        grid_overlaps[0, 0] += ov  # direct overlap
    
    avg_overlap = grid_overlaps[0, 0] / n_trials
    
    print(f"\n  Direct Ax1/Ax5 displacement overlap: {avg_overlap:.4f}")
    
    # The theoretical answer
    print(f"\n  THEORETICAL ANALYSIS:")
    print(f"    Unitary + FSA:   ✅ standard (exp(-iHt)ρexp(iHt))")
    print(f"    CPTP + FGA:      ✅ standard (Lindblad)")
    print(f"    Unitary + FGA:   ⚠️  degenerate (L_k=0 → trivial FGA)")
    print(f"    CPTP + FSA:      ⚠️  via Stinespring dilation only")
    print(f"")
    
    if avg_overlap > 0.8:
        verdict = "LIKELY SAME AXIS (or near-degenerate)"
    elif avg_overlap > 0.4:
        verdict = "PARTIALLY OVERLAPPING (may share a component)"
    else:
        verdict = "DISTINCT AXES"
    
    print(f"  Measured overlap: {avg_overlap:.4f}")
    print(f"  VERDICT: {verdict}")
    print(f"")
    print(f"  WHY overlap is high: changing CPTP↔Unitary and FGA↔FSA")
    print(f"  produce nearly identical displacements because:")
    print(f"  'adding dissipation' (Ax1) ≈ 'adding Lindblad terms' (Ax5)")
    print(f"  They may be the same degree of freedom described twice.")
    
    return avg_overlap


# ═══════════════════════════════════════════════════════════════════
# TEST 2: Axis 3×6 Disentanglement — Better math formulations
# ═══════════════════════════════════════════════════════════════════

def test2_ax3_ax6_disentangle():
    """
    Problem: Axis 3 (±G) and Axis 6 (Aρ/ρA) both produce commutator
    structure, leading to 0.71 overlap.
    
    Hypothesis: The overlap comes from bad math choices, not real redundancy.
    
    Test 3 alternative formulations for Axis 3:
      (A) ±G via generator sign (current — conflates)
      (B) ±G via conjugate representation: U vs U* (Weyl-grounded)
      (C) ±G via Hopf fiber orientation: e^{+iθ} vs e^{-iθ}
    
    And 2 for Axis 6:
      (X) Aρ vs ρA (current — conflates)
      (Y) O(ρ) vs O†(ρ) (adjoint action, no commutator)
    
    Test all 3×2 = 6 combinations. Pick the one with lowest overlap.
    """
    print("\n" + "=" * 70)
    print("TEST 2: Axis 3×6 Disentanglement — Finding Better Math")
    print("=" * 70)
    
    d = 8
    n_trials = 200
    
    def ax3_A(rho, d_val):
        """Current: ±G sign flip → 2G(ρ)dt"""
        H = np.random.randn(d_val, d_val) + 1j * np.random.randn(d_val, d_val)
        H = (H + H.conj().T) / 2
        L = np.zeros((d_val, d_val), dtype=complex)
        for k in range(d_val - 1):
            L[k, k+1] = 0.3
        ham = -1j * (H @ rho - rho @ H)
        lind = L @ rho @ L.conj().T - 0.5 * (L.conj().T @ L @ rho + rho @ L.conj().T @ L)
        G = ham + lind
        dt = 0.2
        r_plus = rho + G * dt
        r_minus = rho - G * dt
        for r in [r_plus, r_minus]:
            r[:] = (r + r.conj().T) / 2
            ev, evx = np.linalg.eigh(r)
            ev = np.maximum(ev, 0)
            r[:] = evx @ np.diag(ev) @ evx.conj().T
            r /= np.trace(r)
        return r_plus - r_minus
    
    def ax3_B(rho, d_val):
        """Conjugate representation: UρU† vs U*ρU†*"""
        H = np.random.randn(d_val, d_val) + 1j * np.random.randn(d_val, d_val)
        H = (H + H.conj().T) / 2
        U = la.expm(-1j * H * 0.3)
        rho_L = U @ rho @ U.conj().T              # left Weyl: U
        rho_R = np.conj(U) @ rho @ np.conj(U).T   # right Weyl: U*
        return rho_L - rho_R
    
    def ax3_C(rho, d_val):
        """Hopf fiber: e^{+iθ} vs e^{-iθ} phase rotation"""
        theta = 0.4
        phase_plus = np.exp(1j * theta) * np.eye(d_val)
        phase_minus = np.exp(-1j * theta) * np.eye(d_val)
        rho_plus = phase_plus @ rho @ phase_plus.conj().T
        rho_minus = phase_minus @ rho @ phase_minus.conj().T
        return rho_plus - rho_minus
    
    def ax6_X(rho, d_val):
        """Current: Aρ − ρA (commutator)"""
        A = np.random.randn(d_val, d_val) + 1j * np.random.randn(d_val, d_val)
        A /= np.linalg.norm(A)
        return A @ rho - rho @ A
    
    def ax6_Y(rho, d_val):
        """Adjoint action: O(ρ) vs O†(ρ)"""
        H = np.random.randn(d_val, d_val) + 1j * np.random.randn(d_val, d_val)
        H = (H + H.conj().T) / 2
        U = la.expm(-1j * H * 0.3)
        # O(ρ) = UρU†
        rho_O = U @ rho @ U.conj().T
        # O†(ρ) = U†ρU
        rho_Odag = U.conj().T @ rho @ U
        return rho_O - rho_Odag
    
    ax3_options = [
        ("A: ±G sign", ax3_A),
        ("B: U vs U* (Weyl)", ax3_B),
        ("C: e^{±iθ} (fiber)", ax3_C),
    ]
    ax6_options = [
        ("X: Aρ − ρA (commutator)", ax6_X),
        ("Y: O vs O† (adjoint)", ax6_Y),
    ]
    
    print(f"\n  Testing {len(ax3_options)}×{len(ax6_options)} = {len(ax3_options)*len(ax6_options)} combinations at d={d}:")
    print(f"  {'':30s} {'X: [A,ρ]':>15s}  {'Y: O vs O†':>15s}")
    
    results = {}
    best_pair = None
    best_overlap = 1.0
    
    for ax3_name, ax3_fn in ax3_options:
        row = f"  {ax3_name:30s}"
        for ax6_name, ax6_fn in ax6_options:
            total = 0.0
            for trial in range(n_trials):
                np.random.seed(trial + 8000)
                rho = make_random_density_matrix(d)
                np.random.seed(trial + 8000)
                d3 = ax3_fn(rho, d)
                np.random.seed(trial + 8000)
                d6 = ax6_fn(rho, d)
                total += normalized_overlap(d3, d6)
            avg = total / n_trials
            results[f"{ax3_name} × {ax6_name}"] = avg
            marker = "✅" if avg < 0.1 else ("⚠️" if avg < 0.3 else "❌")
            row += f"  {avg:8.4f} {marker}"
            if avg < best_overlap:
                best_overlap = avg
                best_pair = (ax3_name, ax6_name)
        print(row)
    
    print(f"\n  BEST PAIR: {best_pair[0]} × {best_pair[1]} → overlap = {best_overlap:.4f}")
    if best_overlap < 0.1:
        print(f"  ✅ ORTHOGONAL: These formulations make Ax3 and Ax6 genuinely distinct.")
    elif best_overlap < 0.3:
        print(f"  ⚠️  MARGINAL: Better but still some shared structure.")
    else:
        print(f"  ❌ STILL CONFLATING: May need fundamentally different math or merge.")
    
    return results, best_pair, best_overlap


# ═══════════════════════════════════════════════════════════════════
# TEST 3: Outer/Inner Torus as Independent Axis Candidate
# ═══════════════════════════════════════════════════════════════════

def test3_outer_inner_axis():
    """
    Candidate new axis: outer/inner torus nesting (η parameter).
    
    η controls the relative size of the two S¹ circles in the torus T²(η):
      η = π/8:  inner torus (R_major ≈ 0.92, R_minor ≈ 0.38)
      η = π/4:  Clifford torus (R_major = R_minor ≈ 0.71)
      η = 3π/8: outer torus (R_major ≈ 0.38, R_minor ≈ 0.92)
    
    Question: Is "move between tori" (change η) independent of:
      - Chirality (Axis 3, ±G)
      - Action side (Axis 6, Aρ/ρA)
      - Channel class (Axis 1, CPTP/Unitary)
    
    If yes → it IS a new independent axis.
    """
    print("\n" + "=" * 70)
    print("TEST 3: Is Outer/Inner Torus (η) an Independent Axis?")
    print("=" * 70)
    
    if not HAS_HOPF:
        print("  ⚠️  hopf_manifold.py not importable. Using fallback geometry.")
    
    d = 2  # d=2 for Hopf/Weyl geometry (spinor space)
    n_trials = 200
    
    def torus_displace(rho, d_val):
        """Displacement from changing torus nesting η."""
        # Inner torus state
        eta_inner = np.pi / 8
        t1, t2 = np.random.rand() * 2 * np.pi, np.random.rand() * 2 * np.pi
        
        if HAS_HOPF:
            q_inner = torus_coordinates(eta_inner, t1, t2)
            q_outer = torus_coordinates(3 * np.pi / 8, t1, t2)
            rho_inner = coherent_state_density(q_inner)
            rho_outer = coherent_state_density(q_outer)
        else:
            # Fallback: model η change as mixing parameter
            rho_inner = rho  # as given (pure-ish)
            rho_outer = 0.3 * rho + 0.7 * np.eye(d_val) / d_val  # more mixed
        
        return rho_outer - rho_inner
    
    def chirality_displace(rho, d_val):
        """Axis 3: Weyl L vs R (using U vs U* formulation)."""
        H = np.random.randn(d_val, d_val) + 1j * np.random.randn(d_val, d_val)
        H = (H + H.conj().T) / 2
        U = la.expm(-1j * H * 0.5)
        rho_L = U @ rho @ U.conj().T
        rho_R = np.conj(U) @ rho @ np.conj(U).T
        return rho_L - rho_R
    
    def action_displace(rho, d_val):
        """Axis 6: Aρ vs ρA."""
        A = np.random.randn(d_val, d_val) + 1j * np.random.randn(d_val, d_val)
        A /= np.linalg.norm(A)
        return A @ rho - rho @ A
    
    def channel_displace(rho, d_val):
        """Axis 1: CPTP vs Unitary."""
        H = np.random.randn(d_val, d_val) + 1j * np.random.randn(d_val, d_val)
        H = (H + H.conj().T) / 2
        U = la.expm(-1j * H * 0.3)
        rho_uni = U @ rho @ U.conj().T
        gamma = 0.3
        K0 = np.diag([1.0, np.sqrt(1-gamma)]).astype(complex)
        K1 = np.array([[0, np.sqrt(gamma)], [0, 0]], dtype=complex)
        rho_cptp = K0 @ rho @ K0.conj().T + K1 @ rho @ K1.conj().T
        rho_cptp /= np.trace(rho_cptp)
        return rho_cptp - rho_uni
    
    axes = [
        ("Torus η (outer/inner)", torus_displace),
        ("Ax3 chirality (U/U*)", chirality_displace),
        ("Ax6 action (Aρ/ρA)", action_displace),
        ("Ax1 channel (CPTP/U)", channel_displace),
    ]
    
    n_axes = len(axes)
    overlap_matrix = np.zeros((n_axes, n_axes))
    
    for trial in range(n_trials):
        np.random.seed(trial + 9000)
        rho = make_random_density_matrix(d)
        disps = []
        for _, fn in axes:
            np.random.seed(trial + 9000)
            disps.append(fn(rho, d))
        
        for i in range(n_axes):
            for j in range(i+1, n_axes):
                ov = normalized_overlap(disps[i], disps[j])
                overlap_matrix[i, j] += ov
                overlap_matrix[j, i] += ov
    
    overlap_matrix /= n_trials
    
    print(f"\n  Overlap matrix (d={d}, {n_trials} trials):")
    for i in range(n_axes):
        row = f"    {axes[i][0]:25s}"
        for j in range(n_axes):
            if i == j:
                row += "    ---  "
            else:
                v = overlap_matrix[i, j]
                m = "✅" if v < 0.1 else ("⚠️" if v < 0.3 else "❌")
                row += f"  {v:.3f}{m}"
        print(row)
    
    # Check if torus η is independent
    torus_row = overlap_matrix[0, :]
    max_ov = max(torus_row[1:])
    
    print(f"\n  Torus η max overlap with other axes: {max_ov:.4f}")
    if max_ov < 0.1:
        print(f"  ✅ INDEPENDENT: Outer/inner IS a genuinely new axis")
    elif max_ov < 0.3:
        print(f"  ⚠️  MARGINAL: Partially independent, needs better construction")
    else:
        print(f"  ❌ DEPENDENT: Outer/inner is NOT independent of existing axes")
    
    return overlap_matrix


# ═══════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    all_results = {}
    
    # Test 1
    ov1 = test1_ax1_vs_ax5()
    all_results["test1_ax1_ax5_overlap"] = ov1
    
    # Test 2
    r2, best_pair, best_ov = test2_ax3_ax6_disentangle()
    all_results["test2_best_pair"] = f"{best_pair[0]} × {best_pair[1]}"
    all_results["test2_best_overlap"] = best_ov
    all_results["test2_all"] = r2
    
    # Test 3
    m3 = test3_outer_inner_axis()
    all_results["test3_torus_overlaps"] = m3.tolist()
    
    # Summary
    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print(f"  Ax1 vs Ax5 overlap:        {ov1:.4f}  {'SAME?' if ov1 > 0.8 else 'DISTINCT' if ov1 < 0.4 else 'PARTIAL'}")
    print(f"  Best Ax3×Ax6 separation:   {best_ov:.4f}  using {best_pair[0]} × {best_pair[1]}")
    print(f"  Torus η independence:      max={max(m3[0,1:]):.4f}")
    
    # Save
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "..", "a2_state", "sim_results")
    os.makedirs(out_dir, exist_ok=True)
    out_file = os.path.join(out_dir, "axis_exploration_suite_results.json")
    with open(out_file, "w") as f:
        json.dump(all_results, f, indent=2, default=str)
    print(f"\nResults written to {out_file}")
