#!/usr/bin/env python3
"""Classical Bregman divergence on the probability simplex.

Lane B classical_baseline: Bregman divergence D_phi(p||q) generated by a
strictly convex phi on the open simplex.
"""
import json
import os
from typing import Literal, Optional
import numpy as np

classification: Literal["classical_baseline", "canonical"] = "classical_baseline"
divergence_log: Optional[str] = (
    "Classical Bregman divergence D_phi(p||q) = phi(p) - phi(q) - <grad phi(q), p-q> "
    "is defined on a commutative simplex using a scalar potential phi. Quantum "
    "Bregman divergence requires an operator-convex trace functional and honors "
    "noncommutativity of rho, sigma via symmetric logarithmic derivatives. The "
    "classical substrate cannot distinguish states that share eigenvalues but "
    "differ in eigenbasis: quantum coherence between eigenbases is invisible here."
)

TOOL_MANIFEST = {
    "pytorch": {"tried": False, "used": False, "reason": "not_attempted"},
    "pyg": {"tried": False, "used": False, "reason": "not_attempted"},
    "z3": {"tried": False, "used": False, "reason": "not_attempted"},
    "cvc5": {"tried": False, "used": False, "reason": "not_attempted"},
    "sympy": {"tried": False, "used": False, "reason": "not_attempted"},
    "clifford": {"tried": False, "used": False, "reason": "not_attempted"},
    "geomstats": {"tried": False, "used": False, "reason": "not_attempted"},
    "e3nn": {"tried": False, "used": False, "reason": "not_attempted"},
    "rustworkx": {"tried": False, "used": False, "reason": "not_attempted"},
    "xgi": {"tried": False, "used": False, "reason": "not_attempted"},
    "toponetx": {"tried": False, "used": False, "reason": "not_attempted"},
    "gudhi": {"tried": False, "used": False, "reason": "not_attempted"},
}
try:
    import torch
    TOOL_MANIFEST["pytorch"]["tried"] = True
    TOOL_MANIFEST["pytorch"]["used"] = True
    TOOL_MANIFEST["pytorch"]["reason"] = "torch autograd cross-check of grad(phi)"
except ImportError:
    TOOL_MANIFEST["pytorch"]["reason"] = "not installed"

TOOL_INTEGRATION_DEPTH = {
    "pytorch": "supportive",
    "pyg": None, "z3": None, "cvc5": None, "sympy": None,
    "clifford": None, "geomstats": None, "e3nn": None,
    "rustworkx": None, "xgi": None, "toponetx": None, "gudhi": None,
}
_VALID_CLASSIFICATIONS = {"classical_baseline", "canonical"}
_VALID_DEPTHS = {"load_bearing", "supportive", "decorative", None}
assert classification in _VALID_CLASSIFICATIONS
assert isinstance(divergence_log, str) and divergence_log.strip()
for _e in TOOL_MANIFEST.values():
    assert isinstance(_e["reason"], str) and _e["reason"].strip()
for _d in TOOL_INTEGRATION_DEPTH.values():
    assert _d in _VALID_DEPTHS

EPS = 1e-12

def phi_negent(p):
    p = np.clip(p, EPS, 1.0)
    return float(np.sum(p * np.log(p)))

def grad_phi_negent(p):
    p = np.clip(p, EPS, 1.0)
    return np.log(p) + 1.0

def bregman(p, q, phi=phi_negent, grad=grad_phi_negent):
    p = np.asarray(p, float); q = np.asarray(q, float)
    return float(phi(p) - phi(q) - np.dot(grad(q), p - q))


def run_positive_tests():
    r = {}
    rng = np.random.default_rng(0)
    # negentropy Bregman reduces to KL on simplex
    for _ in range(8):
        p = rng.dirichlet(np.ones(5)); q = rng.dirichlet(np.ones(5))
        b = bregman(p, q)
        kl = float(np.sum(p * (np.log(np.clip(p, EPS, 1)) - np.log(np.clip(q, EPS, 1)))))
        assert abs(b - kl) < 1e-8, (b, kl)
    r["negentropy_equals_kl"] = True
    # non-negativity
    r["nonnegativity"] = all(
        bregman(rng.dirichlet(np.ones(6)), rng.dirichlet(np.ones(6))) >= -1e-9
        for _ in range(20)
    )
    # D(p||p) = 0
    p = rng.dirichlet(np.ones(7))
    r["zero_at_equal"] = abs(bregman(p, p)) < 1e-10
    return r


def run_negative_tests():
    r = {}
    rng = np.random.default_rng(1)
    # Bregman is generally NOT symmetric
    p = rng.dirichlet(np.ones(4)); q = rng.dirichlet(np.ones(4))
    r["asymmetric"] = abs(bregman(p, q) - bregman(q, p)) > 1e-6
    # not a true metric: triangle inequality can fail
    tri_fail = False
    for _ in range(50):
        a = rng.dirichlet(np.ones(5)); b = rng.dirichlet(np.ones(5)); c = rng.dirichlet(np.ones(5))
        if bregman(a, c) > bregman(a, b) + bregman(b, c) + 1e-6:
            tri_fail = True; break
    r["triangle_inequality_can_fail"] = tri_fail
    return r


def run_boundary_tests():
    r = {}
    # near a boundary of the simplex
    p = np.array([1 - 1e-6, 5e-7, 5e-7])
    q = np.array([1/3, 1/3, 1/3])
    b = bregman(p, q)
    r["near_boundary_finite"] = np.isfinite(b) and b > 0
    # tiny perturbation: quadratic scaling
    p = np.array([0.5, 0.5]); eps = 1e-3
    q = np.array([0.5 + eps, 0.5 - eps])
    b = bregman(p, q)
    # expected ~ eps^2 / (2 * p) summed
    r["quadratic_small_regime"] = abs(b - (eps**2)) < 1e-5
    return r


if __name__ == "__main__":
    pos = run_positive_tests(); neg = run_negative_tests(); bnd = run_boundary_tests()
    all_pass = all(pos.values()) and all(neg.values()) and all(bnd.values())
    results = {
        "name": "bregman_divergence_simplex_classical",
        "classification": classification,
        "divergence_log": divergence_log,
        "tool_manifest": TOOL_MANIFEST,
        "tool_integration_depth": TOOL_INTEGRATION_DEPTH,
        "positive": pos, "negative": neg, "boundary": bnd,
        "all_pass": all_pass,
        "summary": {"all_pass": all_pass},
    }
    out_dir = os.path.join(os.path.dirname(__file__), "a2_state", "sim_results")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "bregman_divergence_simplex_classical_results.json")
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2, default=str)
    print(f"all_pass={all_pass} -> {out_path}")
    assert all_pass, results
