#!/usr/bin/env julia
# =====================================================================================
# deflation_order_null.jl
#   classification = deflation_ordernull_poc ; promotion_allowed = false
# -------------------------------------------------------------------------------------
# Apply Grok's deflation control to the ORDER-NULL / order-sensitivity claim.
#
# GENUINE construction:
#   Reuse the exact density-operator channel definitions from order_null_killtest.jl:
#   Ti, Fi, WeylL, Te, Fe, WeylR composed forward vs reversed on the same random rho set.
#
# DEFLATED construction:
#   Fix one Hopf base H0. Vary only spin^c / connection-lift choices on that base.
#   No channel type changes, no layer stack, no distinct terrain/Weyl/pinch/rotation
#   composition. The admissible lift family is generated by one base Hamiltonian H0 and
#   same-base dephasing/connection variants. If that single-base lift family reproduces
#   the genuine fwd-vs-rev gap and order-discriminating irreversibility, ORDER-NULL
#   deflates. If it cannot, the order gap survives as a genuine multi-channel order DOF.
#
# CLAIM CEILING:
#   This is a bounded deflation POC only. It does NOT assert layer completion, manifold
#   admission, bridge/Xi/Phi0/Axis0, flux, FEP, physics, or ratchet-edge admission.
#   promotion_allowed=false.
# =====================================================================================

using LinearAlgebra
using Random
using Statistics
import JSON
import Z3

const RESULT_PATH = joinpath(@__DIR__, "deflation_order_null_results.json")
const SEED = 20260602
const N_RHO = 20

# ---------- single-qubit operators (density-operator world only; no Bloch r-vector) ----------
const I2 = Matrix{ComplexF64}(I, 2, 2)
const SX = ComplexF64[0 1; 1 0]
const SY = ComplexF64[0 -im; im 0]
const SZ = ComplexF64[1 0; 0 -1]
const SP = ComplexF64[0 1; 0 0]
const SM = ComplexF64[0 0; 1 0]
const P0 = (I2 + SZ) / 2
const P1 = (I2 - SZ) / 2
const Qp = (I2 + SX) / 2
const Qm = (I2 - SX) / 2

hs(A) = sqrt(real(tr(A' * A)))
trace_norm(M) = sum(svdvals(M))

# =====================================================================================
# GENUINE CHANNELS (verbatim formulas from order_null_killtest.jl)
# =====================================================================================
Phi_Ti(rho, q)  = (1 - q) * rho + q * (P0 * rho * P0 + P1 * rho * P1)
Phi_Te(rho, q)  = (1 - q) * rho + q * (Qp * rho * Qp + Qm * rho * Qm)
Ux(theta) = ComplexF64[cos(theta/2) (-im*sin(theta/2)); (-im*sin(theta/2)) cos(theta/2)]
Uz(phi)   = ComplexF64[cis(-phi/2) 0; 0 cis(phi/2)]
Phi_Fi(rho, theta) = Ux(theta) * rho * Ux(theta)'
Phi_Fe(rho, phi)   = Uz(phi)   * rho * Uz(phi)'

dissipator(L, rho) = L*rho*L' - 0.5*((L'*L)*rho + rho*(L'*L))
commutator_flow(H, rho) = -im * (H*rho - rho*H)
function gksl_step_evolve(rho0, H, L; gamma=1.0, eps=1.0, T=4.0, steps=400)
    dt = T/steps
    r = rho0
    for _ in 1:steps
        r = r + dt*(gamma*dissipator(L, r) + eps*commutator_flow(H, r))
        r = (r + r') / 2
        tr_r = real(tr(r))
        abs(tr_r) > 1e-12 && (r = r / tr_r)
    end
    return r
end

function hopf_h0(phi::Float64, chi::Float64, eta::Float64)
    psi = ComplexF64[exp(im*(phi+chi))*cos(eta), exp(im*(phi-chi))*sin(eta)]
    psi = psi / norm(psi)
    n = [real(psi' * (P * psi)) for P in (SX, SY, SZ)]
    nn = norm(n)
    nhat = nn < 1e-12 ? [0.0, 0.0, 1.0] : n ./ nn
    return nhat[1]*SX + nhat[2]*SY + nhat[3]*SZ
end

# ---------- PTM scale for explicit noise floors ----------
const PAULI4 = (I2, SX, SY, SZ)
function ptm(chan)
    T = zeros(Float64, 4, 4)
    for j in 1:4, i in 1:4
        T[i, j] = real(tr(PAULI4[i] * chan(PAULI4[j])) / 2)
    end
    return T
end

# ---------- random density operators: spinor-derived mixture; no Bloch readout ----------
function rand_rho(rng)
    psi = ComplexF64[randn(rng)+im*randn(rng), randn(rng)+im*randn(rng)]
    psi = psi / norm(psi)
    pure = psi * psi'
    p = 0.2 + 0.6*rand(rng)
    rho = p*pure + (1-p)*(I2/2)
    return (rho + rho')/2 / real(tr((rho + rho')/2))
end

function apply_word(word, rho)
    r = rho
    for f in word
        r = f(r)
    end
    return r
end

function word_gap(word, rhos)
    rev = reverse(word)
    diffs = Float64[]
    for rho in rhos
        push!(diffs, trace_norm(apply_word(word, rho) - apply_word(rev, rho)))
    end
    return mean(diffs), maximum(diffs), diffs
end

function irreversibility_residual(word, rhos)
    rev = reverse(word)
    raw = Float64[]
    order_disc = Float64[]
    for rho in rhos
        driven = apply_word(word, rho)
        back_rev = apply_word(rev, driven)
        back_fwd = apply_word(word, driven)
        push!(raw, trace_norm(back_rev - rho))
        push!(order_disc, trace_norm(back_rev - back_fwd))
    end
    return mean(raw), maximum(raw), mean(order_disc), maximum(order_disc)
end

function same_gap_z3(genuine_gap::Float64, deflated_gap::Float64, tol::Float64; scale=1_000_000_000)
    ctx = Z3.Context()
    s = Z3.Solver(ctx)
    same_gap = Z3.BoolVar("single_base_reproduces_gap", ctx)
    delta = Z3.IntVar("abs_scaled_delta", ctx)
    tol_i = max(0, round(Int, scale * tol))
    delta_i = max(0, round(Int, scale * abs(genuine_gap - deflated_gap)))
    # Z3.jl in this carrier does not overload <= on Expr. Since delta and tol_i
    # are integers, delta <= tol_i is encoded as delta < tol_i + 1.
    Z3.add(s, Z3.Or([Z3.Not(same_gap), delta < Z3.IntVal(tol_i + 1, ctx)]))
    Z3.add(s, same_gap == Z3.BoolVal(true, ctx))
    Z3.add(s, delta == Z3.IntVal(delta_i, ctx))
    return string(Z3.check(s)), delta_i, tol_i
end

function lift_unitary(H0, angle)
    return exp(-im * angle * H0)
end

function dephase_in_base(rho, H0; q=0.45)
    ev = eigen(Hermitian(H0))
    V = Matrix(ev.vectors)
    Plo = V[:, 1] * V[:, 1]'
    Phi = V[:, 2] * V[:, 2]'
    return (1-q)*rho + q*(Plo*rho*Plo + Phi*rho*Phi)
end

function run()
    rng = MersenneTwister(SEED)
    rhos = [rand_rho(rng) for _ in 1:N_RHO]

    q = 0.65
    ang = 0.9
    phi0, chi0, eta0 = 2pi*0.21, 2pi*0.13, pi/4
    H0 = hopf_h0(phi0, chi0, eta0)

    # Genuine order_null_killtest heterogeneous word: Ti Fi WeylL Te Fe WeylR.
    fTi = rho -> Phi_Ti(rho, q)
    fTe = rho -> Phi_Te(rho, q)
    fFi = rho -> Phi_Fi(rho, ang)
    fFe = rho -> Phi_Fe(rho, ang)
    fWL = rho -> gksl_step_evolve(rho, +H0, SM)
    fWR = rho -> gksl_step_evolve(rho, -H0, SP)
    genuine_word = [fTi, fFi, fWL, fTe, fFe, fWR]

    # Deflated single-base schedule:
    # same fixed H0; only spin^c lift/connection angles vary. Because every lift is a
    # function of the same base generator H0, the lift-only family is abelian. The
    # connection-dressed variant adds a same-base dephasing readout but still changes no
    # base, channel type, jump basin, or layer.
    lift_angles = [0.31, 0.79, 1.37, 1.93, 2.41, 2.97]
    lift_word = [(rho -> (U = lift_unitary(H0, a); U*rho*U')) for a in lift_angles]
    conn_word = [(rho -> begin
        U = lift_unitary(H0, a)
        U * dephase_in_base(U' * rho * U, H0; q=0.45) * U'
    end) for a in lift_angles]

    # Erased / flat controls.
    same_lift = lift_word[1]
    flat_word = [same_lift, same_lift, same_lift, same_lift, same_lift, same_lift]
    same_base_commuting_dephase = [rho -> dephase_in_base(rho, H0; q=qq) for qq in (0.20, 0.35, 0.50, 0.65, 0.80, 0.90)]

    # Forbidden anti-tautology control: deliberately leaves the single-base constraint.
    # It is not part of the deflation verdict; it proves the metric sees order gaps when
    # noncommuting axes are smuggled in.
    forbidden_axes = [
        rho -> Phi_Ti(rho, 0.65),
        rho -> Phi_Fi(rho, 0.9),
        rho -> Phi_Te(rho, 0.65),
        rho -> Phi_Fe(rho, 0.9),
        rho -> Phi_Fi(rho, 0.4),
        rho -> Phi_Fe(rho, 0.4),
    ]

    all_scale_channels = vcat(genuine_word, lift_word, conn_word, flat_word, same_base_commuting_dephase, forbidden_axes)
    op_scale = maximum(norm(ptm(f)) for f in all_scale_channels)
    word_floor = eps(Float64) * op_scale * length(genuine_word) * 8.0
    match_tol = max(10.0 * word_floor, 0.05) # 5e-2 absolute tolerance; stricter than target 0.35.

    gen_gap_mean, gen_gap_max, _ = word_gap(genuine_word, rhos)
    gen_raw_mean, gen_raw_max, gen_irr_mean, gen_irr_max = irreversibility_residual(genuine_word, rhos)

    lift_gap_mean, lift_gap_max, _ = word_gap(lift_word, rhos)
    lift_raw_mean, lift_raw_max, lift_irr_mean, lift_irr_max = irreversibility_residual(lift_word, rhos)

    conn_gap_mean, conn_gap_max, _ = word_gap(conn_word, rhos)
    conn_raw_mean, conn_raw_max, conn_irr_mean, conn_irr_max = irreversibility_residual(conn_word, rhos)

    flat_gap_mean, flat_gap_max, _ = word_gap(flat_word, rhos)
    flat_raw_mean, flat_raw_max, flat_irr_mean, flat_irr_max = irreversibility_residual(flat_word, rhos)

    comm_gap_mean, comm_gap_max, _ = word_gap(same_base_commuting_dephase, rhos)
    comm_raw_mean, comm_raw_max, comm_irr_mean, comm_irr_max = irreversibility_residual(same_base_commuting_dephase, rhos)

    forbid_gap_mean, forbid_gap_max, _ = word_gap(forbidden_axes, rhos)
    forbid_raw_mean, forbid_raw_max, forbid_irr_mean, forbid_irr_max = irreversibility_residual(forbidden_axes, rhos)

    deflated_candidates = Dict(
        "lift_only" => Dict(
            "description" => "single fixed Hopf base H0; U_m=exp(-i angle_m H0); only spin^c lift angle varies",
            "fwd_rev_trace_gap_mean" => lift_gap_mean,
            "fwd_rev_trace_gap_max" => lift_gap_max,
            "raw_recovery_residual_mean" => lift_raw_mean,
            "raw_recovery_residual_max" => lift_raw_max,
            "order_discriminating_irreversibility_mean" => lift_irr_mean,
            "order_discriminating_irreversibility_max" => lift_irr_max,
        ),
        "connection_dressed_same_base_dephase" => Dict(
            "description" => "same H0 lift plus same-base dephasing; dissipative but no distinct layer/channel family",
            "fwd_rev_trace_gap_mean" => conn_gap_mean,
            "fwd_rev_trace_gap_max" => conn_gap_max,
            "raw_recovery_residual_mean" => conn_raw_mean,
            "raw_recovery_residual_max" => conn_raw_max,
            "order_discriminating_irreversibility_mean" => conn_irr_mean,
            "order_discriminating_irreversibility_max" => conn_irr_max,
        )
    )

    best_name = "lift_only"
    best_gap = lift_gap_mean
    best_irr = lift_irr_mean
    if abs(conn_gap_mean - gen_gap_mean) + abs(conn_irr_mean - gen_irr_mean) <
       abs(lift_gap_mean - gen_gap_mean) + abs(lift_irr_mean - gen_irr_mean)
        best_name = "connection_dressed_same_base_dephase"
        best_gap = conn_gap_mean
        best_irr = conn_irr_mean
    end

    gap_match = abs(best_gap - gen_gap_mean) <= match_tol && best_gap > word_floor
    irr_match = abs(best_irr - gen_irr_mean) <= match_tol && best_irr > word_floor
    controls_flat = flat_gap_max <= word_floor && flat_irr_max <= word_floor &&
                    comm_gap_max <= word_floor && comm_irr_max <= word_floor

    verdict = if gap_match && irr_match && controls_flat
        "order_null_deflated"
    elseif (!gap_match && !irr_match) && controls_flat
        "order_null_survives"
    else
        "mixed"
    end

    z3_gap, z3_gap_delta_i, z3_gap_tol_i = same_gap_z3(gen_gap_mean, best_gap, match_tol)
    z3_irr, z3_irr_delta_i, z3_irr_tol_i = same_gap_z3(gen_irr_mean, best_irr, match_tol)
    z3_flat, _, _ = same_gap_z3(flat_gap_mean, comm_gap_mean, match_tol)

    R = Dict{String,Any}()
    R["object_id"] = "deflation_order_null"
    R["classification"] = "deflation_ordernull_poc"
    R["promotion_allowed"] = false
    R["script"] = "deflation_order_null.jl"
    R["seed"] = SEED
    R["n_rho"] = N_RHO
    R["non_numpy"] = true
    R["bloch_free"] = true
    R["reused_from"] = "order_null_killtest.jl genuine channels: Ti/Fi/WeylL/Te/Fe/WeylR definitions copied verbatim; same seed and density-operator construction."
    R["claim_ceiling"] = "Bounded deflation POC. It tests whether a single fixed Hopf base with only spin^c/connection lift choices can reproduce the existing order gap and order-discriminating irreversibility. No layer completion, manifold admission, bridge, flux, FEP, physics, or ratchet-edge admission."
    R["noise_floor"] = Dict(
        "word_floor" => word_floor,
        "definition" => "eps(Float64) * max PTM HS scale * word_depth(6) * 8 safety",
        "machine_eps" => eps(Float64),
        "max_ptm_hs_scale" => op_scale,
        "match_tolerance" => match_tol,
        "match_tolerance_note" => "absolute 0.05 tolerance dominates numerical floor; target gap is ~0.35, so this is a permissive deflation match bar."
    )

    R["genuine_construction"] = Dict(
        "word" => "Ti Fi WeylL Te Fe WeylR forward vs reversed",
        "fwd_rev_trace_gap_mean" => gen_gap_mean,
        "fwd_rev_trace_gap_max" => gen_gap_max,
        "raw_recovery_residual_mean" => gen_raw_mean,
        "raw_recovery_residual_max" => gen_raw_max,
        "order_discriminating_irreversibility_mean" => gen_irr_mean,
        "order_discriminating_irreversibility_max" => gen_irr_max,
        "note" => "raw recovery is reported, but verdict uses order-discriminating irreversibility: rev(fwd(rho)) vs fwd(fwd(rho))."
    )
    R["deflated_construction"] = Dict(
        "fixed_base" => "single Hopf base H0 = hopf_h0(2pi*0.21, 2pi*0.13, pi/4)",
        "varied_only" => "spin^c/connection lift angles on the same H0",
        "forbidden_in_deflated_verdict" => "changing base axis, jump basin, dephasing basis, Weyl chirality channel, terrain channel, or composing genuine layer families",
        "candidates" => deflated_candidates,
        "best_candidate" => best_name,
        "best_gap_mean" => best_gap,
        "best_order_discriminating_irreversibility_mean" => best_irr,
        "gap_match_to_genuine" => gap_match,
        "irreversibility_match_to_genuine" => irr_match
    )
    R["controls"] = Dict(
        "flat_same_lift_word" => Dict(
            "fwd_rev_trace_gap_mean" => flat_gap_mean,
            "fwd_rev_trace_gap_max" => flat_gap_max,
            "raw_recovery_residual_mean" => flat_raw_mean,
            "raw_recovery_residual_max" => flat_raw_max,
            "order_discriminating_irreversibility_mean" => flat_irr_mean,
            "order_discriminating_irreversibility_max" => flat_irr_max,
        ),
        "same_base_commuting_dephase_strengths" => Dict(
            "fwd_rev_trace_gap_mean" => comm_gap_mean,
            "fwd_rev_trace_gap_max" => comm_gap_max,
            "raw_recovery_residual_mean" => comm_raw_mean,
            "raw_recovery_residual_max" => comm_raw_max,
            "order_discriminating_irreversibility_mean" => comm_irr_mean,
            "order_discriminating_irreversibility_max" => comm_irr_max,
        ),
        "controls_flat" => controls_flat,
        "forbidden_nonbase_axis_control_not_used_for_verdict" => Dict(
            "description" => "This intentionally changes axes/channel families, so it is not a single-base spin^c deflation. It proves the metric can see order gaps when noncommuting structure is smuggled in.",
            "fwd_rev_trace_gap_mean" => forbid_gap_mean,
            "fwd_rev_trace_gap_max" => forbid_gap_max,
            "raw_recovery_residual_mean" => forbid_raw_mean,
            "raw_recovery_residual_max" => forbid_raw_max,
            "order_discriminating_irreversibility_mean" => forbid_irr_mean,
            "order_discriminating_irreversibility_max" => forbid_irr_max,
        )
    )
    R["z3_verdict_flip"] = Dict(
        "encoding" => "single_base_reproduces => abs_scaled_delta <= scaled_tolerance; measured literals supplied from genuine-vs-best-deflated gap and irreversibility.",
        "gap_same_reproduction_verdict" => z3_gap,
        "gap_scaled_delta" => z3_gap_delta_i,
        "gap_scaled_tolerance" => z3_gap_tol_i,
        "irreversibility_same_reproduction_verdict" => z3_irr,
        "irreversibility_scaled_delta" => z3_irr_delta_i,
        "irreversibility_scaled_tolerance" => z3_irr_tol_i,
        "flat_control_same_gap_verdict" => z3_flat,
        "load_bearing_flip" => (z3_gap == "unsat" && z3_irr == "unsat" && z3_flat == "sat")
    )
    R["side_by_side"] = Dict(
        "genuine_gap_mean" => gen_gap_mean,
        "deflated_best_gap_mean" => best_gap,
        "forbidden_nonbase_gap_mean" => forbid_gap_mean,
        "genuine_order_discriminating_irreversibility_mean" => gen_irr_mean,
        "deflated_best_order_discriminating_irreversibility_mean" => best_irr,
        "forbidden_nonbase_order_discriminating_irreversibility_mean" => forbid_irr_mean,
        "gap_deficit" => gen_gap_mean - best_gap,
        "irreversibility_deficit" => gen_irr_mean - best_irr
    )
    R["verdict"] = Dict(
        "overall" => verdict,
        "reading" => verdict == "order_null_deflated" ?
            "single fixed Hopf base with spin^c/connection lift choices reproduces the genuine order gap and order-discriminating irreversibility; ORDER-NULL deflates to one-base connection geometry." :
            verdict == "order_null_survives" ?
            "single fixed Hopf base with only spin^c/connection lift choices cannot reproduce the genuine order gap or order-discriminating irreversibility; ORDER-NULL survives this deflation control as a genuine multi-channel order DOF candidate." :
            "mixed: the single-base lift family reproduced only part of the target signature.",
        "promotion_allowed" => false,
        "blocked_consumers" => ["ratchet edge admission", "layer completion", "manifold admission", "bridge/Xi/Phi0/Axis0", "flux/FEP/physics"]
    )
    R["F01_witness"] = Dict(
        "finite_carrier" => "density operators in D(C^2); finite genuine word plus finite single-base lift schedules",
        "finite_probe" => "$(N_RHO) random spinor-derived density operators",
        "finite_operator" => "genuine Ti/Fi/WeylL/Te/Fe/WeylR channels vs same-base H0 lift channels",
        "finite_path" => "forward and reversed finite words; forward-then-reversed vs forward-then-forward residual"
    )
    R["N01_witness"] = Dict(
        "gap_formula" => "Delta = mean_rho ||Phi_fwd(rho) - Phi_rev(rho)||_1",
        "irreversibility_formula" => "I_order = mean_rho ||Phi_rev(Phi_fwd(rho)) - Phi_fwd(Phi_fwd(rho))||_1",
        "genuine_gap_above_floor" => gen_gap_mean > word_floor,
        "deflated_gap_above_floor" => best_gap > word_floor,
        "genuine_irreversibility_above_floor" => gen_irr_mean > word_floor,
        "deflated_irreversibility_above_floor" => best_irr > word_floor
    )
    R["tool_manifest"] = Dict(
        "LinearAlgebra" => "load_bearing: density operators, channel composition, trace norms, PTM scale, Hopf-base generator.",
        "Random" => "load_bearing: same spinor-derived rho ensemble as order_null_killtest.",
        "Statistics" => "supportive: ensemble means.",
        "Z3" => "load_bearing: measured same-gap/same-irreversibility reproduction is UNSAT for genuine-vs-deflated and SAT for flat controls.",
        "JSON" => "supportive: receipt emission."
    )
    R["tool_integration_depth"] = Dict("LinearAlgebra"=>"load_bearing","Random"=>"load_bearing","Z3"=>"load_bearing","Statistics"=>"supportive","JSON"=>"supportive")

    open(RESULT_PATH, "w") do io
        JSON.print(io, R, 2)
        write(io, "\n")
    end

    println("="^96)
    println("DEFLATION ORDER-NULL  classification=deflation_ordernull_poc promotion_allowed=false")
    println("="^96)
    println("noise floor=", word_floor, "  match tolerance=", match_tol)
    println("GENUINE  gap mean=", round(gen_gap_mean; digits=9),
            "  order-irreversibility mean=", round(gen_irr_mean; digits=9),
            "  raw recovery=", round(gen_raw_mean; digits=9))
    println("DEFLATED best=", best_name,
            "  gap mean=", round(best_gap; digits=12),
            "  order-irreversibility mean=", round(best_irr; digits=12))
    println("CONTROLS flat=", controls_flat,
            "  flat gap max=", flat_gap_max,
            "  same-base dephase gap max=", comm_gap_max)
    println("FORBIDDEN nonbase axis control gap mean=", round(forbid_gap_mean; digits=9),
            "  (not used for verdict)")
    println("Z3 gap=", z3_gap, "  irr=", z3_irr, "  flat=", z3_flat)
    println("VERDICT: ", verdict)
    println("Wrote: ", RESULT_PATH)
    return R
end

run()
