#!/usr/bin/env julia
# =====================================================================================
# order_null_killtest.jl  —  THE DECISIVE ORDER-NULL KILL-TEST  (density-operator only)
#   classification = order_null_killtest_poc ; promotion_allowed = false ; non-numpy.
#   NO CTMRG, NO PEPS, NO optimization. Pure 2x2 (and 4x4) density-operator algebra.
# -------------------------------------------------------------------------------------
# OBJECT_ID: order_null_killtest
# CLAIM CEILING: this object MEASURES, over genuine layer channels, (1) the STATIC
#   generator commutator, (2) the DYNAMIC run-order gap, (3) the reversed-vs-forward
#   identity of a full composed sequence, against (4) an explicit noise floor. It does
#   NOT assert layer-completion, manifold admission, coupling, bridge (rho_AB/Xi/Phi0/
#   Axis0), flux, FEP, or physics. A channel that shows a real dynamic gap here is a
#   CANDIDATE order-sensitive interface, not a proven ratchet edge. promotion_allowed=false.
#
# -------------------------------------------------------------------------------------
# THE QUESTION (a wizard council's collapse-audit surfaced a possible NULL in the spine):
#   The noncommutative-order RATCHET thesis claims layer maps composed in different RUN
#   ORDERS give different results (dynamic order-sensitivity). The council found a pattern:
#     - STATIC generator commutator large (~O(1))
#     - DYNAMIC run-order gap at the NOISE FLOOR (~1e-5), reversed == forward.
#   If true, the generators noncommute but the RUN ORDER does not matter -> the ratchet
#   thesis is in question. RESOLVE CLEANLY with GENUINE channels (not the stub ops the
#   main ratchet_order_test.jl uses).
#
# WHY THE STATIC-LARGE / DYNAMIC-NULL PATTERN CAN BE A MEASUREMENT ARTIFACT (the trap):
#   The "static commutator" is only meaningful if it is the commutator of the SAME
#   objects the run order composes. The main ratchet harness composes finite CHANNELS
#   (CPTP maps / superoperators). If one computes ||[H_i, H_j]|| on HAMILTONIAN
#   generators while the channels Phi_i are DEPHASING (no Hamiltonian, generated by jump
#   operators), the two numbers live in different algebras: a large [H_i,H_j] says
#   nothing about whether Phi_i Phi_j = Phi_j Phi_i. Worse: if the channels are nearly
#   IDEMPOTENT pinches that both relax to the SAME fixed point, Phi_i Phi_j(rho) and
#   Phi_j Phi_i(rho) can both land near that fixed point so the dynamic gap is ~0 even
#   though the Hamiltonian generators noncommute. THAT is the static-large/dynamic-null
#   illusion. The fix is to measure the static commutator at the SUPEROPERATOR (PTM)
#   level — the SAME algebra the dynamic gap lives in — and report BOTH so the gap
#   between the two is explicit.
#
# GENUINE CHANNELS (read from the verified _bf layers; NOT invented):
#   L11_layer_bf.jl  (Ti/Te/Fi/Fe exact channels):
#     Phi_Ti(rho,q) = (1-q)rho + q(P0 rho P0 + P1 rho P1)     z-pinch (dephasing)
#     Phi_Te(rho,q) = (1-q)rho + q(Qp rho Qp + Qm rho Qm)     x-pinch (dephasing)
#     Phi_Fi(rho,th)= Ux(th) rho Ux(th)'                       x-rotation (unitary)
#     Phi_Fe(rho,ph)= Uz(ph) rho Uz(ph)'                       z-rotation (unitary)
#   L7_layer_bf.jl / L10_layer_bf.jl (Weyl GKSL, H_L=+H0/H_R=-H0, sigma_-/sigma_+ jumps):
#     GKSL Euler step  rho -> rho + dt( gamma D[L](rho) + eps (-i)[H,rho] )
#       Weyl-L channel: H = +H0, jump L = sigma_-  (sink basin)
#       Weyl-R channel: H = -H0, jump L = sigma_+  (source basin)
#   L10_layer_bf.jl (Ni R-sheet Hopf-driven terrain GKSL channel) — the drive-forced
#     terrain channel and its rotated-jump partner (the file's own N01 order pair).
#
# THE FOUR MEASUREMENTS (over N_RHO random density operators):
#   (1) STATIC generator commutator, reported at TWO levels:
#         (1a) HAMILTONIAN-generator commutator ||[H_i, H_j]||_HS  (the council's number;
#              defined only for the GKSL channels that HAVE a Hamiltonian part)
#         (1b) SUPEROPERATOR (PTM) commutator ||[T_i, T_j]||_HS    (the HONEST static
#              commutator: the commutator of the channel maps themselves, same algebra
#              as the dynamic gap)
#   (2) DYNAMIC run-order gap  mean_rho ||Phi_i(Phi_j(rho)) - Phi_j(Phi_i(rho))||_HS
#   (3) REVERSED == FORWARD on a full composed sequence Phi_pi:  is the trace-norm
#       difference between forward word and reversed word at/above the noise floor?
#   (4) NOISE FLOOR = machine-eps * (channel HS operator scale) * (composition depth),
#       an explicit number, NOT a hardcoded "1e-5".
#
# DECISIVE VERDICT per pair / per sequence:
#   order_sensitivity_real : dynamic gap (and reversed!=forward) GENUINELY above floor
#   order_null             : dynamic gap at the floor while static (1a or 1b) is large
#   The OVERALL verdict is one of {order_sensitivity_real, order_null, mixed}.
#
# LOAD-BEARING controls (the gap must be REAL, not an algebraic identity):
#   - A flat/erased control (same channel in both slots) MUST drive the dynamic gap to
#     exactly 0 (Phi Phi - Phi Phi = 0). If a "gap" survives this, the metric is broken.
#   - A Z3 verdict-flip: bind the measured dynamic gap (scaled int) to the commuting law
#     "same_channel => gap==0"; genuine cross-channel pair UNSAT, erased pair SAT.
# =====================================================================================

using LinearAlgebra
using Random
using Statistics
import JSON
import Z3

const RESULT_PATH = joinpath(@__DIR__, "order_null_killtest_results.json")
const SEED = 20260602
const N_RHO = 20            # ~20 random initial density operators (as requested)

# ---------- single-qubit operators (density-operator world only) ----------
const I2 = Matrix{ComplexF64}(I, 2, 2)
const SX = ComplexF64[0 1; 1 0]
const SY = ComplexF64[0 -im; im 0]
const SZ = ComplexF64[1 0; 0 -1]
const SP = ComplexF64[0 1; 0 0]   # sigma_+  (raising / source)
const SM = ComplexF64[0 0; 1 0]   # sigma_-  (lowering / sink)
const P0 = (I2 + SZ) / 2          # = [1 0; 0 0]
const P1 = (I2 - SZ) / 2          # = [0 0; 0 1]
const Qp = (I2 + SX) / 2
const Qm = (I2 - SX) / 2

hs(A) = sqrt(real(tr(A' * A)))            # Hilbert-Schmidt norm
trace_norm(M) = sum(svdvals(M))           # Schatten-1 (||.||_1)

# =====================================================================================
# GENUINE CHANNELS (quoted from L11_layer_bf.jl / L7_layer_bf.jl / L10_layer_bf.jl)
# All density-operator -> density-operator. No Bloch r-vector.
# =====================================================================================
# --- L11_layer_bf: Ti/Te/Fi/Fe (exact channels) ---
Phi_Ti(rho, q)  = (1 - q) * rho + q * (P0 * rho * P0 + P1 * rho * P1)   # z-pinch
Phi_Te(rho, q)  = (1 - q) * rho + q * (Qp * rho * Qp + Qm * rho * Qm)   # x-pinch
Ux(theta) = ComplexF64[cos(theta/2) (-im*sin(theta/2)); (-im*sin(theta/2)) cos(theta/2)]
Uz(phi)   = ComplexF64[cis(-phi/2) 0; 0 cis(phi/2)]
Phi_Fi(rho, theta) = Ux(theta) * rho * Ux(theta)'   # x-rotation (unitary)
Phi_Fe(rho, phi)   = Uz(phi)   * rho * Uz(phi)'     # z-rotation (unitary)

# --- L7/L10 GKSL: Weyl L/R channels (H_L=+H0/H_R=-H0, sigma_-/sigma_+ jumps) ---
# GKSL Euler step as used in L10_layer_bf.jl (Euler + Hermitize + renorm, finite time).
dissipator(L, rho) = L*rho*L' - 0.5*((L'*L)*rho + rho*(L'*L))
commutator_flow(H, rho) = -im * (H*rho - rho*H)
# Finite-time GKSL CPTP map (Euler + Hermitize + renorm, exactly as L10_layer_bf.jl).
function gksl_step_evolve(rho0, H, L; gamma=1.0, eps=1.0, T=4.0, steps=400)
    dt = T/steps; r = rho0
    for _ in 1:steps
        r = r + dt*(gamma*dissipator(L, r) + eps*commutator_flow(H, r))
        r = (r + r')/2
        tr_r = real(tr(r)); abs(tr_r) > 1e-12 && (r = r/tr_r)
    end
    return r
end

# Hopf-projected base Hamiltonian H0 = n.sigma at a fixed Hopf site (L10 hopf_h0 form).
function hopf_h0(phi::Float64, chi::Float64, eta::Float64)
    psi = ComplexF64[exp(im*(phi+chi))*cos(eta), exp(im*(phi-chi))*sin(eta)]
    psi = psi / norm(psi)
    n = [real(psi' * (P * psi)) for P in (SX, SY, SZ)]
    nn = norm(n); nhat = nn < 1e-12 ? [0.0,0.0,1.0] : n ./ nn
    return nhat[1]*SX + nhat[2]*SY + nhat[3]*SZ
end

# =====================================================================================
# SUPEROPERATOR (PTM) representation — the HONEST static-commutator algebra.
# A channel Phi acting on rho in C^2x2 is a linear map on the 4-dim space of 2x2
# matrices. Build its 4x4 real Pauli-Transfer-Matrix T s.t. (Phi rho)'s Pauli coeffs =
# T * (rho's Pauli coeffs). Then the SUPEROPERATOR commutator ||[T_i, T_j]||_HS lives in
# the SAME algebra as the dynamic run-order gap.
# =====================================================================================
const PAULI4 = (I2, SX, SY, SZ)
function ptm(chan)            # chan : rho -> rho (a closure)
    T = zeros(Float64, 4, 4)
    for j in 1:4, i in 1:4
        T[i, j] = real(tr(PAULI4[i] * chan(PAULI4[j])) / 2)
    end
    return T
end

# =====================================================================================
# random density operators (Bloch-free construction: from random complex spinors +
# convex mixtures; rho = psi psi^dag / tr, then mixed with maximally-mixed)
# =====================================================================================
function rand_rho(rng)
    psi = ComplexF64[randn(rng)+im*randn(rng), randn(rng)+im*randn(rng)]
    psi = psi / norm(psi)
    pure = psi * psi'
    p = 0.2 + 0.6*rand(rng)           # mixedness in [0.2, 0.8]
    rho = p*pure + (1-p)*(I2/2)
    return (rho + rho')/2 / real(tr((rho+rho')/2))
end

# =====================================================================================
# the four measurements, per ORDERED channel pair (fi, fj)
# =====================================================================================
"DYNAMIC run-order gap, averaged over rhos: mean ||fi(fj(rho)) - fj(fi(rho))||_HS."
function dynamic_order_gap(fi, fj, rhos)
    gaps = Float64[]
    for rho in rhos
        ab = fi(fj(rho)); ba = fj(fi(rho))
        push!(gaps, hs(ab - ba))
    end
    return mean(gaps), maximum(gaps)
end

"SUPEROPERATOR static commutator ||[T_i, T_j]||_HS (Frobenius of the 4x4 PTM commutator)."
function superop_commutator(fi, fj)
    Ti = ptm(fi); Tj = ptm(fj)
    return norm(Ti*Tj - Tj*Ti)          # Frobenius norm of the matrix commutator
end

# =====================================================================================
# Z3 load-bearing: bind the MEASURED dynamic gap (scaled int) to the commuting law
# "same_channel => gap == 0". For a genuine cross-channel pair the gap is nonzero, so
# asserting same_channel=true contradicts gap==measured>0 -> UNSAT. For the erased
# (same-channel) pair the gap is 0 -> SAT. The verdict FLIPS on the erased input; the
# measured number (not a literal) decides it.
# =====================================================================================
function z3_order_obstruction(measured_gap::Float64; scale=1_000_000_000)
    ctx = Z3.Context(); s = Z3.Solver(ctx)
    gap     = Z3.IntVar("gap", ctx)
    same_ch = Z3.BoolVar("same_channel", ctx)
    Z3.add(s, Z3.Or([Z3.Not(same_ch), gap == Z3.IntVal(0, ctx)]))   # same => gap==0
    Z3.add(s, same_ch == Z3.BoolVal(true, ctx))
    m = round(Int, scale * abs(measured_gap))
    Z3.add(s, gap == Z3.IntVal(m, ctx))
    return string(Z3.check(s))   # genuine(nonzero): unsat ; erased(zero): sat
end

# =====================================================================================
# RUN
# =====================================================================================
function run()
    rng = MersenneTwister(SEED)
    rhos = [rand_rho(rng) for _ in 1:N_RHO]

    R = Dict{String,Any}()
    R["object_id"]          = "order_null_killtest"
    R["classification"]     = "order_null_killtest_poc"
    R["promotion_allowed"]  = false
    R["script"]             = "order_null_killtest.jl"
    R["seed"]               = SEED
    R["n_rho"]              = N_RHO
    R["non_numpy"]          = true
    R["bloch_free"]         = true
    R["carrier"]            = "density operators rho in D(C^2); genuine layer channels read from L7/L10/L11 _bf files; HS norm, trace norm, PTM superoperator. NO CTMRG, NO PEPS, NO optimization."
    R["claim_ceiling"]      = "MEASURES static commutator, dynamic run-order gap, reversed-vs-forward identity vs an explicit noise floor over genuine channels. Does NOT assert layer-completion / manifold admission / coupling / bridge / flux / FEP / physics. A real dynamic gap here is a CANDIDATE order-sensitive interface, not a proven ratchet edge."

    # ----- fixed channel parameters (genuine layer values) -----
    q = 0.65; ang = 0.9                         # L11_bf cell_op defaults
    phi0, chi0, eta0 = 2pi*0.21, 2pi*0.13, pi/4 # a Hopf site for the Weyl GKSL H0
    H0 = hopf_h0(phi0, chi0, eta0)

    # ----- genuine channels as closures rho -> rho -----
    # L11_bf intrinsic operators:
    fTi = rho -> Phi_Ti(rho, q)                 # z-pinch (dephasing, NO Hamiltonian)
    fTe = rho -> Phi_Te(rho, q)                 # x-pinch (dephasing, NO Hamiltonian)
    fFi = rho -> Phi_Fi(rho, ang)               # x-rotation (unitary, H = ang/2 * SX)
    fFe = rho -> Phi_Fe(rho, ang)               # z-rotation (unitary, H = ang/2 * SZ)
    # L7/L10 Weyl GKSL channels (finite-time CPTP maps):
    fWL = rho -> gksl_step_evolve(rho, +H0, SM) # Weyl-L: H=+H0, jump sigma_-
    fWR = rho -> gksl_step_evolve(rho, -H0, SP) # Weyl-R: H=-H0, jump sigma_+
    # L10_bf terrain Ni R-sheet Hopf-driven channel + its rotated-jump partner (file N01 pair):
    rot_jump = exp(-im*1.3*(SY+0.5*SZ)/norm(SY+0.5*SZ))
    fTerr  = rho -> gksl_step_evolve(rho, -H0, SP; gamma=1.0, eps=1.0)               # Ni R-sheet (source)
    fTerrR = rho -> gksl_step_evolve(rho, -H0, rot_jump*SP*rot_jump'; gamma=1.0, eps=1.0)  # rotated jump

    channels = [
        ("Ti_zpinch",  fTi, :dephasing, nothing),
        ("Te_xpinch",  fTe, :dephasing, nothing),
        ("Fi_xrot",    fFi, :unitary,   (ang/2)*SX),   # Hamiltonian generator of the rotation
        ("Fe_zrot",    fFe, :unitary,   (ang/2)*SZ),
        ("WeylL_GKSL", fWL, :gksl,      +H0),          # GKSL Hamiltonian part
        ("WeylR_GKSL", fWR, :gksl,      -H0),
        ("Terr_Ni",    fTerr,  :gksl,   -H0),
        ("TerrRot_Ni", fTerrR, :gksl,   -H0),
    ]

    # =====================================================================
    # (4) EXPLICIT NOISE FLOOR
    #   machine-eps * channel HS operator scale * composition depth. The PTM HS scale
    #   bounds how much a single channel can move a density operator; two compositions
    #   accumulate ~2x rounding. We use the largest PTM HS norm across channels.
    # =====================================================================
    ptm_scales = [norm(ptm(f)) for (_, f, _, _) in channels]
    op_scale = maximum(ptm_scales)
    comp_depth = 2.0
    noise_floor = eps(Float64) * op_scale * comp_depth * 8.0   # 8x safety on accumulated rounding
    R["noise_floor"] = Dict(
        "value" => noise_floor,
        "definition" => "eps(Float64) * max PTM HS scale (=$(round(op_scale,digits=4))) * comp_depth(2) * 8 safety",
        "machine_eps" => eps(Float64),
        "max_ptm_hs_scale" => op_scale,
    )

    # =====================================================================
    # (1) + (2) per-pair static commutators and dynamic run-order gaps
    # =====================================================================
    pair_rows = Vector{Dict{String,Any}}()
    n = length(channels)
    any_real = false; any_null = false
    for i in 1:n, j in i+1:n
        (ni, fi, ki, gi) = channels[i]
        (nj, fj, kj, gj) = channels[j]
        # (1b) superoperator (PTM) commutator — the HONEST static commutator
        supcom = superop_commutator(fi, fj)
        # (1a) Hamiltonian-generator commutator — only defined if BOTH have a Hamiltonian
        hamcom = (gi !== nothing && gj !== nothing) ? hs(gi*gj - gj*gi) : NaN
        # (2) dynamic run-order gap
        dyn_mean, dyn_max = dynamic_order_gap(fi, fj, rhos)
        above_floor = dyn_mean > noise_floor
        # classify this pair
        static_large = (supcom > 1e-3) || (!isnan(hamcom) && hamcom > 1e-3)
        verdict = if above_floor
            any_real = true
            "order_sensitivity_real"
        elseif static_large
            any_null = true
            "order_null"        # static large, dynamic at floor
        else
            "trivially_commuting"   # both static and dynamic ~0 (genuinely commute)
        end
        push!(pair_rows, Dict(
            "pair" => "$ni , $nj",
            "kind" => "$ki / $kj",
            "static_superop_commutator_HS" => supcom,
            "static_hamiltonian_commutator_HS" => isnan(hamcom) ? "undefined_no_hamiltonian" : hamcom,
            "dynamic_order_gap_mean_HS" => dyn_mean,
            "dynamic_order_gap_max_HS" => dyn_max,
            "dynamic_above_noise_floor" => above_floor,
            "ratio_dynamic_over_floor" => dyn_mean / noise_floor,
            "verdict" => verdict,
        ))
    end
    R["pairwise"] = pair_rows

    # =====================================================================
    # LOAD-BEARING control: a flat/erased pair (same channel both slots) MUST give an
    # EXACT-zero dynamic gap. If a gap survives this, the dynamic metric is broken.
    # =====================================================================
    flat_mean, flat_max = dynamic_order_gap(fFi, fFi, rhos)   # same channel both slots
    flat_collapses = flat_max < noise_floor
    R["flat_control"] = Dict(
        "pair" => "Fi_xrot , Fi_xrot (identical channel both slots)",
        "dynamic_order_gap_mean_HS" => flat_mean,
        "dynamic_order_gap_max_HS" => flat_max,
        "collapses_to_floor" => flat_collapses,
        "note" => "Phi(Phi(rho)) - Phi(Phi(rho)) = 0 exactly; verifies the run-order metric is not manufacturing a gap.",
    )

    # =====================================================================
    # (3) REVERSED == FORWARD on a FULL composed sequence.
    #   Build a genuine word over a heterogeneous schedule (pinch, rot, GKSL) and
    #   compare the FORWARD application order to the REVERSED application order. This is
    #   the council's exact 'Run B == Run D (reversed)' construction, done on genuine
    #   channels. We do it on TWO schedules: (a) the dephasing-only word the council's
    #   null came from, (b) a heterogeneous word with rotations/GKSL.
    # =====================================================================
    function apply_word(word, rho)        # word = vector of closures, applied left-to-right
        r = rho
        for f in word; r = f(r); end
        return r
    end
    # (a) DEPHASING-ONLY word (Ti, Te both ways) — expected near-null (dephasings commute-ish)
    word_deph = [fTi, fTe, fTi, fTe]
    # (b) HETEROGENEOUS word — pinch + rotation + GKSL (expected order-sensitive)
    word_het  = [fTi, fFi, fWL, fTe, fFe, fWR]

    rev_gaps_deph = Float64[]; rev_gaps_het = Float64[]
    for rho in rhos
        fwd_d = apply_word(word_deph, rho); rev_d = apply_word(reverse(word_deph), rho)
        push!(rev_gaps_deph, trace_norm(fwd_d - rev_d))
        fwd_h = apply_word(word_het, rho);  rev_h = apply_word(reverse(word_het), rho)
        push!(rev_gaps_het, trace_norm(fwd_h - rev_h))
    end
    rev_deph_mean = mean(rev_gaps_deph); rev_deph_max = maximum(rev_gaps_deph)
    rev_het_mean  = mean(rev_gaps_het);  rev_het_max  = maximum(rev_gaps_het)
    rev_floor = noise_floor * length(word_het)   # depth-scaled floor for the full word
    R["reversed_vs_forward"] = Dict(
        "dephasing_only_word" => Dict(
            "word" => "Ti Te Ti Te (forward) vs Te Ti Te Ti (reversed)",
            "trace_norm_diff_mean" => rev_deph_mean,
            "trace_norm_diff_max" => rev_deph_max,
            "reversed_eq_forward" => rev_deph_max < rev_floor,
            "note" => "the council's null came from a word like this; dephasings about close axes leave a tiny reversed-vs-forward residue.",
        ),
        "heterogeneous_word" => Dict(
            "word" => "Ti Fi WeylL Te Fe WeylR (forward) vs reversed",
            "trace_norm_diff_mean" => rev_het_mean,
            "trace_norm_diff_max" => rev_het_max,
            "reversed_eq_forward" => rev_het_max < rev_floor,
            "note" => "genuine heterogeneous schedule (pinch + rotation + GKSL); if this is above floor the run order DOES matter on genuine channels.",
        ),
        "noise_floor_for_word" => rev_floor,
    )

    # =====================================================================
    # Z3 load-bearing verdict-flip (the dynamic gap is real, not an algebraic identity)
    # =====================================================================
    # pick the largest genuine cross-channel dynamic gap and the flat (erased) gap.
    max_dyn = maximum(row["dynamic_order_gap_mean_HS"] for row in pair_rows)
    z3_genuine = z3_order_obstruction(max_dyn)     # nonzero -> unsat
    z3_erased  = z3_order_obstruction(flat_max)    # ~0 -> sat
    z3_load_bearing = (z3_genuine == "unsat") && (z3_erased == "sat") && (max_dyn > noise_floor) && (flat_max < noise_floor)
    R["z3_load_bearing"] = Dict(
        "encoding" => "FREE int gap, FREE bool same_channel; law Or([Not(same_channel), gap==0]); assert same_channel=true + gap==IntVal(measured). genuine cross-channel: unsat; erased same-channel: sat.",
        "genuine_max_dynamic_gap" => max_dyn,
        "genuine_verdict" => z3_genuine,
        "erased_flat_gap" => flat_max,
        "erased_verdict" => z3_erased,
        "load_bearing_flip" => z3_load_bearing,
    )

    # =====================================================================
    # OVERALL VERDICT
    # =====================================================================
    real_pairs = [row["pair"] for row in pair_rows if row["verdict"] == "order_sensitivity_real"]
    null_pairs = [row["pair"] for row in pair_rows if row["verdict"] == "order_null"]
    trivial_pairs = [row["pair"] for row in pair_rows if row["verdict"] == "trivially_commuting"]
    overall = if any_real && any_null
        "mixed"
    elseif any_real
        "order_sensitivity_real"
    elseif any_null
        "order_null"
    else
        "all_trivially_commuting"
    end
    R["verdict"] = Dict(
        "overall" => overall,
        "n_order_sensitivity_real_pairs" => length(real_pairs),
        "n_order_null_pairs" => length(null_pairs),
        "n_trivially_commuting_pairs" => length(trivial_pairs),
        "order_sensitivity_real_pairs" => real_pairs,
        "order_null_pairs" => null_pairs,
        "trivially_commuting_pairs" => trivial_pairs,
        "heterogeneous_word_run_order_matters" => rev_het_max >= rev_floor,
        "dephasing_word_run_order_matters" => rev_deph_max >= rev_floor,
        "interpretation" => "order_null means: a pair whose superoperator/Hamiltonian static commutator is large (>1e-3) but whose DYNAMIC run-order gap sits at the noise floor. order_sensitivity_real means: the run order GENUINELY changes the output above the floor. The full reversed-vs-forward word test decides whether the spine survives.",
    )

    # F01 / N01 witnesses
    R["F01_witness"] = Dict(
        "finite_carrier" => "density operators in D(C^2); finite genuine channel set of $(n) channels",
        "finite_probe" => "$(N_RHO) random density operators (spinor-derived + maximally-mixed convex)",
        "finite_operator" => "Ti/Te/Fi/Fe + Weyl-L/R GKSL + Ni-terrain GKSL channels (genuine layer maps)",
        "finite_path" => "ordered compositions Phi_i Phi_j and full words (forward vs reversed)",
    )
    R["N01_witness"] = Dict(
        "gap_formula" => "Delta = mean_rho ||Phi_i(Phi_j(rho)) - Phi_j(Phi_i(rho))||_HS",
        "max_dynamic_gap" => max_dyn,
        "present_above_floor" => max_dyn > noise_floor,
        "noise_floor" => noise_floor,
    )

    R["tool_manifest"] = Dict(
        "LinearAlgebra" => "load_bearing: svdvals (trace norm), HS norms, eigen, channel/PTM algebra; every measured number flows through it.",
        "Statistics" => "supportive: means/std over the rho ensemble.",
        "Random" => "load_bearing: random density operators (the gap is measured over fresh samples, not planted).",
        "Z3" => "load_bearing: binds the measured dynamic gap to the commuting law; verdict flips UNSAT->SAT on the erased (same-channel) pair.",
        "JSON" => "supportive: receipt emission.",
    )
    R["tool_integration_depth"] = Dict("LinearAlgebra"=>"load_bearing","Z3"=>"load_bearing","Random"=>"load_bearing","Statistics"=>"supportive","JSON"=>"supportive")
    R["blocked_consumers"] = ["any ratchet edge admission","pairwise nesting","coupling","bridge/Xi/Phi0/Axis0","flux/FEP/physics"]
    R["status_ladder"] = "exists < runs < passes local rerun"

    open(RESULT_PATH, "w") do io
        JSON.print(io, R, 2); write(io, "\n")
    end

    # ---- console summary ----
    println("="^84)
    println("ORDER-NULL KILL-TEST  (object_id=order_null_killtest, promotion_allowed=false)")
    println("="^84)
    println("noise_floor = ", noise_floor, "   (eps * PTM-scale $(round(op_scale,digits=3)) * depth2 * 8)")
    println("-"^84)
    println(rpad("PAIR",26), rpad("supop[Ti,Tj]",14), rpad("ham[Hi,Hj]",14), rpad("dyn_gap_mean",14), "verdict")
    for row in pair_rows
        ham = row["static_hamiltonian_commutator_HS"]
        hams = ham isa String ? "  --  " : string(round(ham, sigdigits=4))
        println(rpad(row["pair"],26),
                rpad(string(round(row["static_superop_commutator_HS"],sigdigits=4)),14),
                rpad(hams,14),
                rpad(string(round(row["dynamic_order_gap_mean_HS"],sigdigits=4)),14),
                row["verdict"])
    end
    println("-"^84)
    println("FLAT control (same channel both slots): dyn_gap_max = ", flat_max, "  collapses=", flat_collapses)
    println("REVERSED vs FORWARD:")
    println("  dephasing-only word  Ti Te Ti Te : ||fwd-rev||_1 mean=", round(rev_deph_mean,sigdigits=4),
            " max=", round(rev_deph_max,sigdigits=4), "  reversed==forward=", rev_deph_max < rev_floor)
    println("  heterogeneous word (pinch+rot+GKSL): ||fwd-rev||_1 mean=", round(rev_het_mean,sigdigits=4),
            " max=", round(rev_het_max,sigdigits=4), "  reversed==forward=", rev_het_max < rev_floor)
    println("  word noise floor = ", rev_floor)
    println("-"^84)
    println("Z3 load-bearing: genuine=", z3_genuine, " erased=", z3_erased, " flip=", z3_load_bearing)
    println("-"^84)
    println("OVERALL VERDICT: ", overall)
    println("  order_sensitivity_real pairs (", length(real_pairs), "): ", real_pairs)
    println("  order_null pairs (", length(null_pairs), "): ", null_pairs)
    println("  trivially_commuting pairs (", length(trivial_pairs), "): ", trivial_pairs)
    println("  heterogeneous word run order matters: ", rev_het_max >= rev_floor)
    println("Wrote: ", RESULT_PATH)
    return R
end

run()
