#!/usr/bin/env python3
"""Exact finite r3-r6 Ratchet over the eight returned H/P/O source families.

This runner repairs two defects in the returned 176 campaign:

1. source families are never pooled by raw row count;
2. repair mathematics is an exhaustive finite completion census rather than a
   six-item accuracy menu.

For each anonymous source packet it:

* enumerates all eight quotients generated by subsets of (h0,h1,p);
* checks exact factorisation of the outcome through each quotient;
* enumerates all 256 Boolean algebraic-normal-form maps;
* retains plural minimal sufficient coordinate sets and ANF maps;
* emits feature-deletion witnesses;
* retains the observed continuation relation when no function closes;
* recomputes the boundary and its geometry/counting co-views after held-out
  observations return.

It uses only finite exact integer/Boolean operations.  It does not promote
source claims, owner hypotheses, physics, engines, or a root ontology.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import os
import stat
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable


SCHEMA = "ratchet.source-balanced-completion/0.1"
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY = ROOT / "inputs" / "RECEIPT_REGISTRY.json"
DEFAULT_OUTPUT = ROOT / "receipts"
FEATURES = ("h0", "h1", "p")
MONOMIALS: tuple[tuple[str, ...], ...] = (
    (),
    ("h0",),
    ("h1",),
    ("p",),
    ("h0", "h1"),
    ("h0", "p"),
    ("h1", "p"),
    ("h0", "h1", "p"),
)


class FenceError(ValueError):
    pass


def canonical_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def sha_bytes(raw: bytes) -> str:
    return "sha256:" + hashlib.sha256(raw).hexdigest()


def sha_json(value: Any) -> str:
    return sha_bytes(canonical_json(value).encode("utf-8"))


def dump(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, indent=2, sort_keys=False)
        handle.write("\n")


def read_one_regular(path: Path, expected: str) -> tuple[dict[str, Any], str]:
    before = path.lstat()
    if stat.S_ISLNK(before.st_mode) or not stat.S_ISREG(before.st_mode):
        raise FenceError(f"not a nonsymlink regular file: {path}")
    if before.st_nlink != 1:
        raise FenceError(f"input must have one hard link: {path}")
    fd = os.open(path, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0))
    try:
        opened = os.fstat(fd)
        if (before.st_dev, before.st_ino) != (opened.st_dev, opened.st_ino):
            raise FenceError(f"input inode changed before read: {path}")
        chunks: list[bytes] = []
        while True:
            chunk = os.read(fd, 1024 * 1024)
            if not chunk:
                break
            chunks.append(chunk)
        after = os.fstat(fd)
        if (opened.st_dev, opened.st_ino) != (after.st_dev, after.st_ino):
            raise FenceError(f"input inode changed during read: {path}")
        raw = b"".join(chunks)
    finally:
        os.close(fd)
    observed = sha_bytes(raw)
    want = expected if expected.startswith("sha256:") else "sha256:" + expected
    if observed != want:
        raise FenceError(f"hash mismatch for {path.name}: expected {want}, got {observed}")
    try:
        value = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise FenceError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise FenceError(f"receipt root is not an object: {path}")
    return value, observed


def bit(value: Any, label: str) -> int:
    if isinstance(value, bool):
        raise FenceError(f"{label} cannot be Boolean")
    if value in (0, "0"):
        return 0
    if value in (1, "1"):
        return 1
    raise FenceError(f"{label} must be 0 or 1")


def scalar(value: Any, family_id: str, label: str) -> int:
    if family_id in {"online_regime_shift_detector_v0", "s8_local_information_table_v0"}:
        if not isinstance(value, list) or len(value) != 1:
            raise FenceError(f"{family_id}:{label} must be a singleton vector")
        return bit(value[0], f"{family_id}:{label}[0]")
    if isinstance(value, list):
        raise FenceError(f"{family_id}:{label} vector form is undeclared")
    return bit(value, f"{family_id}:{label}")


def projection_for(receipt: dict[str, Any], family_id: str) -> tuple[list[Any], list[str]]:
    if family_id in {"finite_qca_runner_trajectories_v0", "adaptive_observation_policy_v0"}:
        projections = receipt.get("source_projections")
        if not isinstance(projections, list):
            raise FenceError(f"{family_id}: source_projections missing")
        hits = [row for row in projections if isinstance(row, dict) and row.get("family_id") == family_id]
        if len(hits) != 1:
            raise FenceError(f"{family_id}: expected one source projection")
        projection = hits[0]
    else:
        if receipt.get("family_id") != family_id:
            raise FenceError(f"{family_id}: receipt family mismatch")
        projection = receipt.get("projection")
        if not isinstance(projection, dict):
            raise FenceError(f"{family_id}: projection missing")
    rows = projection.get("records")
    if not isinstance(rows, list) or not rows:
        raise FenceError(f"{family_id}: projection records missing")
    errors: list[str] = []
    for candidate in (receipt.get("source_validation_errors"), projection.get("source_validation_errors")):
        if isinstance(candidate, list):
            errors.extend(str(item) for item in candidate)
    controls = receipt.get("controls")
    if isinstance(controls, dict):
        fresh = controls.get("fresh_source_fences")
        if isinstance(fresh, dict) and isinstance(fresh.get("source_validation_errors"), list):
            errors.extend(str(item) for item in fresh["source_validation_errors"])
    return rows, sorted(set(errors))


def normalize_rows(family_id: str, raw_rows: list[Any]) -> list[dict[str, Any]]:
    normalized: list[dict[str, Any]] = []
    for ordinal, row in enumerate(raw_rows):
        if not isinstance(row, dict):
            raise FenceError(f"{family_id}: row {ordinal} is not an object")
        history = row.get("history")
        if not isinstance(history, list) or len(history) != 2:
            raise FenceError(f"{family_id}: row {ordinal} history must contain two bits")
        normalized.append(
            {
                "h0": bit(history[0], f"{family_id}:row{ordinal}:h0"),
                "h1": bit(history[1], f"{family_id}:row{ordinal}:h1"),
                "p": scalar(row.get("probe"), family_id, f"row{ordinal}:probe"),
                "o": scalar(row.get("outcome"), family_id, f"row{ordinal}:outcome"),
                "source_row_id": row.get("row_id"),
            }
        )
    normalized.sort(key=lambda row: canonical_json({key: row[key] for key in ("h0", "h1", "p", "o")}))
    occurrences: Counter[str] = Counter()
    for row in normalized:
        content = canonical_json({key: row[key] for key in ("h0", "h1", "p", "o")})
        rank = occurrences[content]
        occurrences[content] += 1
        row["transport_id"] = sha_bytes(f"{content}|{rank}".encode("utf-8"))[7:31]
    return normalized


def source_tier(receipt: dict[str, Any], errors: list[str]) -> tuple[str, str]:
    status = str(receipt.get("status", "UNDECLARED"))
    if receipt.get("all_pass") is True and not errors:
        return "SOURCE_EXECUTION_CLEAN_PROJECTION", "executable_projection_calibration"
    if receipt.get("controls", {}).get(
        "pure_raw_source_functions_pass_finite_fences", {}
    ).get("passed") is True:
        return "RAW_FUNCTIONS_VERIFIED_FULL_RUNTIME_BLOCKED", "raw_function_calibration_only"
    if not errors:
        return "PROJECTION_VALID_SOURCE_CLAIM_HELD", "projection_only"
    return "PROJECTION_VALID_RUNTIME_INCOMPLETE", "provisional_projection_only"


def load_sources(registry_path: Path) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    families = registry.get("families")
    if not isinstance(families, list) or len(families) != 8:
        raise FenceError("registry must contain exactly eight family entries")
    provenance: list[dict[str, Any]] = []
    sources: list[dict[str, Any]] = []
    for item in families:
        family_id = str(item["family_id"])
        receipt_path = ROOT / "inputs" / str(item["bundle_receipt"])
        receipt, receipt_sha = read_one_regular(receipt_path, str(item["receipt_sha256"]))
        raw_rows, validation_errors = projection_for(receipt, family_id)
        rows = normalize_rows(family_id, raw_rows)
        projection_digest = sha_json(
            [{key: row[key] for key in ("h0", "h1", "p", "o")} for row in rows]
        )
        handle = "src-" + hashlib.sha256(
            f"{receipt_sha}|{projection_digest}".encode("utf-8")
        ).hexdigest()[:16]
        tier, ceiling = source_tier(receipt, validation_errors)
        sources.append(
            {
                "handle": handle,
                "rows": rows,
                "tier": tier,
                "claim_ceiling": ceiling,
                "source_status": receipt.get("status"),
                "validation_errors": validation_errors,
                "receipt_sha256": receipt_sha,
                "projection_sha256": projection_digest,
            }
        )
        provenance.append(
            {
                "handle": handle,
                "family_id": family_id,
                "bundle_receipt": str(item["bundle_receipt"]),
                "receipt_sha256": receipt_sha,
                "projection_sha256": projection_digest,
                "source_status": receipt.get("status"),
                "tier": tier,
                "claim_ceiling": ceiling,
                "validation_errors": validation_errors,
                "raw_row_count": len(rows),
            }
        )
    sources.sort(key=lambda row: row["handle"])
    provenance.sort(key=lambda row: row["handle"])
    if len({row["handle"] for row in sources}) != 8:
        raise FenceError("anonymous source handles collided")
    return sources, provenance


def split_rows(handle: str, rows: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    ranked = sorted(
        rows,
        key=lambda row: hashlib.sha256(
            f"heldout-v1|{handle}|{row['transport_id']}".encode("utf-8")
        ).hexdigest(),
    )
    held_count = max(1, (len(rows) + 3) // 4) if len(rows) > 1 else 0
    held_ids = {row["transport_id"] for row in ranked[:held_count]}
    train = [row for row in rows if row["transport_id"] not in held_ids]
    held = [row for row in rows if row["transport_id"] in held_ids]
    return train, held


def feature_subsets() -> list[tuple[str, ...]]:
    return [
        tuple(FEATURES[index] for index in range(3) if mask & (1 << index))
        for mask in range(8)
    ]


def quotient_record(rows: list[dict[str, Any]], features: tuple[str, ...]) -> dict[str, Any]:
    cells: dict[tuple[int, ...], dict[int, list[str]]] = defaultdict(lambda: defaultdict(list))
    for row in rows:
        key = tuple(int(row[name]) for name in features)
        cells[key][int(row["o"])].append(str(row["transport_id"]))
    conflict_contexts = 0
    conflict_pairs = 0
    unresolved_excess = 0
    for outcomes in cells.values():
        support = [value for value, members in outcomes.items() if members]
        unresolved_excess += max(0, len(support) - 1)
        if len(support) > 1:
            conflict_contexts += 1
            conflict_pairs += len(outcomes.get(0, [])) * len(outcomes.get(1, []))
    partition = sorted(
        {
            tuple(int(row[name]) for name in features)
            for row in rows
        }
    )
    return {
        "features": list(features),
        "sufficient_factorization": conflict_contexts == 0,
        "geometry_view": {
            "kind": "finite_quotient_incidence",
            "quotient_cell_count": len(cells),
            "conflict_context_count": conflict_contexts,
            "distinction_violation_pair_count": conflict_pairs,
            "partition_fingerprint": sha_json(partition),
        },
        "entropy_view": {
            "kind": "finite_unresolved_branch_capacity",
            "licensed_by": "finite counted outcome support on the same quotient boundary",
            "unresolved_excess": unresolved_excess,
            "log2_compatible_section_count": conflict_contexts,
            "compatible_deterministic_sections_on_observed_cells": 1 << conflict_contexts,
            "thermodynamic_or_probability_claim": False,
        },
    }


def subset_minima(lattice: list[dict[str, Any]]) -> list[tuple[str, ...]]:
    sufficient = [tuple(row["features"]) for row in lattice if row["sufficient_factorization"]]
    return sorted(
        [
            candidate
            for candidate in sufficient
            if not any(set(other) < set(candidate) for other in sufficient)
        ],
        key=lambda row: (len(row), row),
    )


def feature_deletion_witness(
    rows: list[dict[str, Any]], features: tuple[str, ...], removed: str
) -> dict[str, Any] | None:
    retained = tuple(name for name in features if name != removed)
    buckets: dict[tuple[int, ...], list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        buckets[tuple(int(row[name]) for name in retained)].append(row)
    for key in sorted(buckets):
        group = buckets[key]
        for left, right in itertools.combinations(group, 2):
            if left["o"] != right["o"]:
                return {
                    "removed_feature": removed,
                    "retained_context": list(key),
                    "left": {name: left[name] for name in (*FEATURES, "o")},
                    "right": {name: right[name] for name in (*FEATURES, "o")},
                }
    return None


def eval_anf(mask: int, row: dict[str, Any]) -> int:
    result = 0
    for index, monomial in enumerate(MONOMIALS):
        if not mask & (1 << index):
            continue
        term = 1
        for name in monomial:
            term &= int(row[name])
        result ^= term
    return result


def exact_anf_masks(rows: Iterable[dict[str, Any]], candidates: Iterable[int] = range(256)) -> list[int]:
    materialized = list(rows)
    return [
        mask
        for mask in candidates
        if all(eval_anf(mask, row) == int(row["o"]) for row in materialized)
    ]


def mask_record(mask: int) -> dict[str, Any]:
    active = [MONOMIALS[index] for index in range(8) if mask & (1 << index)]
    variables = sorted({name for monomial in active for name in monomial})
    degree = max((len(monomial) for monomial in active), default=0)
    return {
        "mask": mask,
        "monomials": [list(row) if row else ["1"] for row in active],
        "essential_variable_upper_bound": variables,
        "degree": degree,
        "monomial_count": len(active),
    }


def anf_frontiers(masks: list[int]) -> dict[str, Any]:
    support_minima = [
        mask
        for mask in masks
        if not any(
            other != mask and (other & mask) == other
            for other in masks
        )
    ]
    if masks:
        best_tuple = min((mask_record(mask)["degree"], mask_record(mask)["monomial_count"]) for mask in masks)
        degree_size = [
            mask
            for mask in masks
            if (mask_record(mask)["degree"], mask_record(mask)["monomial_count"]) == best_tuple
        ]
    else:
        degree_size = []
    return {
        "support_inclusion_frontier": [mask_record(mask) for mask in sorted(support_minima)],
        "degree_then_size_frontier": [mask_record(mask) for mask in sorted(degree_size)],
        "robust_intersection_masks": sorted(set(support_minima) & set(degree_size)),
        "sensitivity_union_masks": sorted(set(support_minima) | set(degree_size)),
    }


def relation_record(rows: list[dict[str, Any]]) -> dict[str, Any]:
    support: dict[tuple[int, int, int], set[int]] = defaultdict(set)
    for row in rows:
        support[(row["h0"], row["h1"], row["p"])].add(row["o"])
    edges = [
        {"context": list(context), "outcome": outcome}
        for context in sorted(support)
        for outcome in sorted(support[context])
    ]
    deletion = [
        {
            "deleted_edge": edge,
            "coverage_after_deletion": False,
            "witness": edge,
        }
        for edge in edges
    ]
    return {
        "kind": "finite_unweighted_continuation_relation",
        "edge_count": len(edges),
        "outdegree_multiset": sorted(len(values) for values in support.values()),
        "relation_fingerprint": sha_json(edges),
        "every_edge_has_deletion_witness": True,
        "deletion_witnesses": deletion,
    }


def analyze_rows(rows: list[dict[str, Any]]) -> dict[str, Any]:
    lattice = [quotient_record(rows, subset) for subset in feature_subsets()]
    minima = subset_minima(lattice)
    witnesses: list[dict[str, Any]] = []
    for features in minima:
        feature_witnesses = [
            feature_deletion_witness(rows, features, removed)
            for removed in features
        ]
        witnesses.append(
            {
                "features": list(features),
                "feature_deletion_witnesses": feature_witnesses,
                "all_features_load_bearing": all(item is not None for item in feature_witnesses),
            }
        )
    masks = exact_anf_masks(rows)
    relation = relation_record(rows)
    full_context = next(row for row in lattice if row["features"] == list(FEATURES))
    return {
        "row_count": len(rows),
        "raw_record_fingerprint": sha_json(
            sorted(
                ({key: row[key] for key in (*FEATURES, "o")} for row in rows),
                key=canonical_json,
            )
        ),
        "coordinate_refinement_lattice": lattice,
        "minimal_sufficient_coordinate_antichain": [list(row) for row in minima],
        "coordinate_deletion_witnesses": witnesses,
        "anf_exact_survivor_count": len(masks),
        "anf_exact_survivor_masks": masks,
        "anf_frontiers": anf_frontiers(masks),
        "relation": relation,
        "full_context_functional": full_context["sufficient_factorization"],
        "repair_split": (
            "DETERMINISTIC_COMPLETIONS_SURVIVE_ALONGSIDE_RELATION"
            if masks
            else "NO_DETERMINISTIC_COMPLETION__RELATION_REMAINS"
        ),
    }


def heldout_stage(train_rows: list[dict[str, Any]], held_rows: list[dict[str, Any]]) -> dict[str, Any]:
    train_masks = exact_anf_masks(train_rows)
    survived = exact_anf_masks(held_rows, train_masks)
    killed = sorted(set(train_masks) - set(survived))
    return {
        "train_survivor_count": len(train_masks),
        "heldout_survivor_count": len(survived),
        "heldout_survivor_masks": survived,
        "purgatory_events": [
            {
                "candidate_mask": mask,
                "event": "PARKED_AFTER_HELDOUT_COUNTEREXAMPLE",
                "eligible_for_reoffer_after_material_context_change": True,
            }
            for mask in killed
        ],
        "history_changed_later_candidate_space": bool(killed),
    }


def structural_signature(analysis: dict[str, Any]) -> dict[str, Any]:
    minima = analysis["minimal_sufficient_coordinate_antichain"]
    signature = {
        "full_context_functional": analysis["full_context_functional"],
        "minimal_coordinate_sizes": sorted(len(row) for row in minima),
        "coordinate_antichain_size": len(minima),
        "anf_survivor_count": analysis["anf_exact_survivor_count"],
        "relation_outdegree_multiset": analysis["relation"]["outdegree_multiset"],
        "repair_split": analysis["repair_split"],
    }
    signature["fingerprint"] = sha_json(signature)
    return signature


def run_campaign(registry: Path, output: Path) -> dict[str, Any]:
    sources, provenance = load_sources(registry)
    normalized_tables = {
        "schema_version": "ratchet.anonymous-normalized-source-tables/0.1",
        "feature_order": list(FEATURES),
        "outcome_field": "o",
        "source_labels_present": False,
        "sources": [
            {
                "handle": source["handle"],
                "rows": [
                    {key: row[key] for key in (*FEATURES, "o", "transport_id")}
                    for row in source["rows"]
                ],
            }
            for source in sources
        ],
    }
    r3_sources: list[dict[str, Any]] = []
    r4_sources: list[dict[str, Any]] = []
    r5_sources: list[dict[str, Any]] = []
    r6_sources: list[dict[str, Any]] = []
    controls: list[dict[str, Any]] = []

    for source in sources:
        handle = source["handle"]
        rows = source["rows"]
        train, held = split_rows(handle, rows)
        train_analysis = analyze_rows(train)
        heldout = heldout_stage(train, held)
        full_analysis = analyze_rows(rows)
        reversed_analysis = analyze_rows(list(reversed(rows)))
        doubled_analysis = analyze_rows(rows + rows)
        invariant_keys = (
            "minimal_sufficient_coordinate_antichain",
            "anf_exact_survivor_masks",
            "full_context_functional",
            "repair_split",
        )
        permutation_pass = all(
            full_analysis[key] == reversed_analysis[key] for key in invariant_keys
        )
        replication_pass = all(
            full_analysis[key] == doubled_analysis[key] for key in invariant_keys
        )
        r3_sources.append(
            {
                "handle": handle,
                "row_count": len(rows),
                "tier": source["tier"],
                "claim_ceiling": source["claim_ceiling"],
                "projection_eligible_for_packet_relative_math": True,
                "source_claim_admitted": False,
                "source_runtime_error_count": len(source["validation_errors"]),
                "source_receipt_sha256": source["receipt_sha256"],
                "projection_sha256": source["projection_sha256"],
            }
        )
        r4_sources.append(
            {
                "handle": handle,
                "train_row_count": len(train),
                "analysis": train_analysis,
            }
        )
        r5_sources.append(
            {
                "handle": handle,
                "heldout_row_count": len(held),
                **heldout,
            }
        )
        r6_sources.append(
            {
                "handle": handle,
                "full_recompute": full_analysis,
                "structural_signature": structural_signature(full_analysis),
            }
        )
        controls.append(
            {
                "handle": handle,
                "row_permutation_invariant": permutation_pass,
                "uniform_row_replication_invariant": replication_pass,
                "source_label_absent_from_analysis": source["handle"] not in canonical_json(full_analysis)
                and all(item["family_id"] not in canonical_json(full_analysis) for item in provenance),
            }
        )

    signatures = Counter(row["structural_signature"]["fingerprint"] for row in r6_sources)
    prior_relation_outcomes = Counter(
        row["full_recompute"]["repair_split"] for row in r6_sources
    )
    history_changes = sum(
        1 for row in r5_sources if row["history_changed_later_candidate_space"]
    )
    all_controls_pass = all(
        row["row_permutation_invariant"]
        and row["uniform_row_replication_invariant"]
        and row["source_label_absent_from_analysis"]
        for row in controls
    )

    r3 = {
        "schema_version": "ratchet.source-balanced.r3/0.1",
        "kind": "anonymous_source_packet_eligibility_with_claim_ceiling_inheritance",
        "source_count": len(r3_sources),
        "sources": r3_sources,
        "raw_rows_are_not_pooled_for_scoring": True,
        "source_HOLD_is_not_a_veto_on_projection_math": True,
        "source_claims_admitted": 0,
        "status": "R3_PACKET_RELATIVE_PROJECTIONS_ELIGIBLE__SOURCE_CLAIMS_REMAIN_HELD",
    }
    r4 = {
        "schema_version": "ratchet.source-balanced.r4/0.1",
        "kind": "exact_coordinate_lattice_and_256_anf_completion_census",
        "sources": r4_sources,
        "source_weighting": "one independent frontier per anonymous source; no raw-row pooling",
        "status": "R4_EXACT_FINITE_COMPLETION_CENSUS_EXECUTED",
    }
    r5 = {
        "schema_version": "ratchet.source-balanced.r5/0.1",
        "kind": "heldout_counterexamples_and_universal_purgatory_eligibility",
        "sources": r5_sources,
        "source_count_with_history_effect": history_changes,
        "status": "R5_HELDOUT_REOFFER_EXECUTED",
    }
    r6 = {
        "schema_version": "ratchet.source-balanced.r6/0.1",
        "kind": "full_boundary_recompute_after_heldout_return",
        "sources": r6_sources,
        "cross_source_signature_multiplicities": [
            {"fingerprint": key, "source_count": value}
            for key, value in sorted(signatures.items())
        ],
        "prior_relation_repair_disposition": {
            "counts": dict(sorted(prior_relation_outcomes.items())),
            "interpretation": (
                "the prior unweighted relation was re-offered on every source; "
                "it remains necessary where no function closes and becomes nonminimal "
                "under deterministic-prediction orders where exact functions survive"
            ),
        },
        "identity_across_sources_claimed": False,
        "universal_emergence_claimed": False,
        "status": "R6_FULL_BOUNDARY_AND_COVIEWS_RECOMPUTED",
    }
    controls_receipt = {
        "schema_version": "ratchet.source-balanced.controls/0.1",
        "controls": controls,
        "all_controls_pass": all_controls_pass,
        "pooled_accuracy_runner_disposition": (
            "REJECTED_AS_SOURCE_SIZE_WEIGHTED_AND_NOT_A_REPAIR_CENSUS"
        ),
        "packet_local_pawl": {
            "rule": (
                "source families are separate mathematical occurrences; uniform row "
                "replication within one source cannot change its full frontier or its "
                "one-source vote in cross-source recurrence"
            ),
            "engaged": all_controls_pass,
            "global_canon_claimed": False,
        },
    }
    campaign = {
        "schema_version": SCHEMA,
        "ticks": [
            {"tick": "r3", "receipt": "r3_projection_eligibility.json", "sha256": sha_json(r3)},
            {"tick": "r4", "receipt": "r4_exact_completion_census.json", "sha256": sha_json(r4)},
            {"tick": "r5", "receipt": "r5_heldout_reoffer.json", "sha256": sha_json(r5)},
            {"tick": "r6", "receipt": "r6_full_recompute.json", "sha256": sha_json(r6)},
        ],
        "mathematical_motion_executed": True,
        "recursive_raw_boundary_recomputations": 2,
        "prior_retained_repair_challenged": True,
        "prior_repair_split_or_nonminimal": len(prior_relation_outcomes) > 1
        or "DETERMINISTIC_COMPLETIONS_SURVIVE_ALONGSIDE_RELATION" in prior_relation_outcomes,
        "source_count": len(sources),
        "source_count_with_heldout_history_effect": history_changes,
        "controls_pass": all_controls_pass,
        "native_lev_bound": False,
        "julia_jax_pytorch_recomputed": False,
        "z3_cvc5_recomputed": False,
        "canonical_project_mutated": False,
        "status": (
            "RUN_COMPLETE_SOURCE_BALANCED_R3_R6__"
            "HOLD_NATIVE_LEV_TRI_ENGINE_SOLVER_AND_LIVE_INTEGRATION"
        ),
        "claim_ceiling": (
            "exact finite packet-relative completion census over eight returned "
            "projection receipts; no source claim, root axiom, scientific manifold, "
            "physics, engine, axis, owner hypothesis, or universal architecture admitted"
        ),
    }

    dump(output / "provenance_map.json", {"schema_version": "ratchet.provenance-map/0.1", "sources": provenance})
    dump(output / "normalized_source_tables.json", normalized_tables)
    with (output / "normalized_source_tables.tsv").open("w", encoding="utf-8") as handle:
        handle.write("handle\th0\th1\tp\to\n")
        for source in normalized_tables["sources"]:
            for row in source["rows"]:
                handle.write(
                    f"{source['handle']}\t{row['h0']}\t{row['h1']}\t"
                    f"{row['p']}\t{row['o']}\n"
                )
    dump(output / "r3_projection_eligibility.json", r3)
    dump(output / "r4_exact_completion_census.json", r4)
    dump(output / "r5_heldout_reoffer.json", r5)
    dump(output / "r6_full_recompute.json", r6)
    dump(output / "controls.json", controls_receipt)
    dump(output / "campaign_receipt.json", campaign)
    return campaign


def validate(output: Path) -> list[str]:
    failures: list[str] = []
    required = [
        "provenance_map.json",
        "normalized_source_tables.json",
        "normalized_source_tables.tsv",
        "r3_projection_eligibility.json",
        "r4_exact_completion_census.json",
        "r5_heldout_reoffer.json",
        "r6_full_recompute.json",
        "controls.json",
        "campaign_receipt.json",
    ]
    for name in required:
        if not (output / name).is_file():
            failures.append(f"missing {name}")
    if failures:
        return failures
    campaign = json.loads((output / "campaign_receipt.json").read_text(encoding="utf-8"))
    controls = json.loads((output / "controls.json").read_text(encoding="utf-8"))
    r3 = json.loads((output / "r3_projection_eligibility.json").read_text(encoding="utf-8"))
    r4 = json.loads((output / "r4_exact_completion_census.json").read_text(encoding="utf-8"))
    r5 = json.loads((output / "r5_heldout_reoffer.json").read_text(encoding="utf-8"))
    r6 = json.loads((output / "r6_full_recompute.json").read_text(encoding="utf-8"))
    if campaign.get("mathematical_motion_executed") is not True:
        failures.append("campaign did not execute mathematical motion")
    if campaign.get("canonical_project_mutated") is not False:
        failures.append("campaign claims canonical mutation")
    if r3.get("source_count") != 8 or len(r4.get("sources", [])) != 8:
        failures.append("eight anonymous sources were not retained")
    if len(r5.get("sources", [])) != 8 or len(r6.get("sources", [])) != 8:
        failures.append("r5/r6 source coverage differs from r3/r4")
    if controls.get("all_controls_pass") is not True:
        failures.append("one or more source-balance controls failed")
    if controls.get("packet_local_pawl", {}).get("engaged") is not True:
        failures.append("packet-local source-balance pawl did not engage")
    for source in r6.get("sources", []):
        analysis = source.get("full_recompute", {})
        relation = analysis.get("relation", {})
        if relation.get("every_edge_has_deletion_witness") is not True:
            failures.append(f"{source.get('handle')}: relation deletion witness missing")
        for item in analysis.get("coordinate_deletion_witnesses", []):
            if item.get("all_features_load_bearing") is not True:
                failures.append(f"{source.get('handle')}: coordinate feature not load-bearing")
    return failures


def self_test() -> list[str]:
    failures: list[str] = []
    xor_rows = [
        {"h0": h0, "h1": h1, "p": p, "o": h0 ^ p, "transport_id": f"{h0}{h1}{p}"}
        for h0, h1, p in itertools.product((0, 1), repeat=3)
    ]
    result = analyze_rows(xor_rows)
    if result["minimal_sufficient_coordinate_antichain"] != [["h0", "p"]]:
        failures.append("feature-subset census failed XOR fixture")
    expected_mask = (1 << 1) | (1 << 3)
    if result["anf_exact_survivor_masks"] != [expected_mask]:
        failures.append("ANF census failed XOR fixture")
    conflict = xor_rows + [
        {"h0": 0, "h1": 0, "p": 0, "o": 1, "transport_id": "conflict"}
    ]
    conflict_result = analyze_rows(conflict)
    if conflict_result["full_context_functional"] is not False:
        failures.append("full-context conflict was not detected")
    if conflict_result["anf_exact_survivor_count"] != 0:
        failures.append("function survived inconsistent context")
    if conflict_result["repair_split"] != "NO_DETERMINISTIC_COMPLETION__RELATION_REMAINS":
        failures.append("relation fallback did not engage")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--run",
        action="store_true",
        help="Execute the campaign (also the default when no mode flag is supplied).",
    )
    parser.add_argument("--validate", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    selected_modes = sum((args.run, args.validate, args.self_test))
    if selected_modes > 1:
        parser.error("choose only one of --run, --validate, or --self-test")
    if args.self_test:
        failures = self_test()
        if failures:
            for failure in failures:
                print("FAIL", failure)
            return 1
        print("PASS source_balanced_completion_ratchet self-test")
        return 0
    if args.validate:
        failures = validate(args.output)
        print(json.dumps({"ok": not failures, "errors": failures}, indent=2))
        return 0 if not failures else 1
    campaign = run_campaign(args.registry, args.output)
    failures = validate(args.output)
    print(json.dumps(campaign, indent=2))
    if failures:
        for failure in failures:
            print("FAIL", failure)
        return 1
    print("PASS source-balanced r3-r6 exact completion campaign")
    return 0


if __name__ == "__main__":
    sys.exit(main())
