#!/usr/bin/env python3
"""
retrocausal_possibility_field_v4_irreducibility -- the DECISIVE discriminator rpf_v3
could not run. It attacks the gap the fresh audit + grok-4.3 named:

  rpf_v3 EARNED a global-vs-forward-GREEDY separation (global survivor b8 != forward
  greedy b2). But the audit found that gate is NECESSARY-NOT-SUFFICIENT: a forward
  MARKOV kernel WITH HIDDEN STATE (extra coordinates summarizing the prior shells)
  could ALSO beat naive forward GREEDY selection. "Beats a myopic greedy walk" is not
  "irreducible to a forward process". The strong retrocausal/global claim needs more.

THE GROK DISCRIMINATOR (verbatim target, implemented here):
  Construct the observed SEQUENCE-measure mu over the shell-traversal OUTPUTS across a
  FAMILY of perturbed instances (vary the carrier so mu is a DISTRIBUTION over output
  sequences, not one point). The shell-traversal output of one instance is the GLOBAL
  joint assignment written as a sequence along the shell order:
        seq = ( chosen(Sigma_3), chosen(Sigma_2), chosen(Sigma_1) )   [outer -> inner]
  Then compute

        tv_infimum = inf over forward Markov kernels K with alphabet |S| <= N_f
                     of   || mu  -  mu0 . K ||_TV

  where N_f is the MEASURED fiber size of the carrier (rpf_v3's per-shell fiber
  cardinality, max_fiber = 3 -> N_f = 3). mu0.K is the sequence-measure GENERATED by a
  forward (left-to-right, Markov) process whose memory between steps is a hidden state
  of alphabet size <= N_f. The infimum is taken by EXHAUSTIVE search over the
  deterministic embeddings (symbol -> one of <= N_f hidden classes) of size <= N_f.

  IRREDUCIBLE iff tv_infimum > threshold (0.05) after the exhaustive search: the global
  selection's cross-shell correlation structure does NOT factor as a width-N_f forward
  Markov chain -> genuinely global, not forward+hidden-state in disguise.
  REDUCIBLE iff tv_infimum -> 0: a width-N_f forward Markov chain reproduces mu -> the
  strong retrocausal/global reading is KILLED on this carrier.

WHY THE BOUND |S| <= N_f IS THE WHOLE TEST (the honest crux):
  An UNBOUNDED forward memory can carry the entire prefix and reproduce ANY sequence
  distribution -- so it is vacuously sufficient and the test would be empty. The bound
  |S| <= N_f forces the forward process to be LOSSY: between shells it may distinguish
  only N_f hidden classes. The discriminator asks precisely whether the global joint
  assignment's cross-shell correlations factor through a width-N_f forward bottleneck.
  If they do not, the joint optimum is irreducible to any forward+bounded-memory model.

THE FORWARD MARKOV MODEL, EXACTLY (deterministic width-N_f embeddings; exhaustive):
  A forward Markov kernel of alphabet |S| <= N_f over the symbol set B (branch ids) is:
    - a deterministic EMBEDDING  e : B -> {0..N_f-1}  coarse-graining each position's
      symbol into <= N_f hidden classes (the bounded memory carried to the next step);
    - the generated sequence-measure factorizes as a Markov chain on the EMBEDDED
      states:  P(x_1..x_L) = pi(x_1) * prod_t T_t( x_{t+1} | e(x_t) ),
      i.e. step t+1's symbol distribution depends on the PREVIOUS symbol ONLY through
      its width-N_f class e(x_t). This is the maximum-likelihood / best-fit forward
      Markov kernel for that embedding, computed in closed form from mu's empirical
      transition counts (the standard ML estimate; KEY POINT: it is the BEST forward
      fit for that embedding, so the inf over embeddings is the genuine inf).
  tv_infimum = min over ALL deterministic embeddings e of size <= N_f of
               TV( mu ,  mu_generated_by_best_forward_chain_under_e ).
  This is exact and EXHAUSTIVE over the deterministic <= N_f-class forward Markov
  models; it does not depend on a builder-chosen kernel.

  WHY THIS BITES (cannot be cheated by a unique-symbol key): the forward chain's step
  t+1 distribution may depend on x_t ONLY through its width-N_f class e(x_t). It can
  NOT condition on the full prior PREFIX. The global compressor, by contrast, chooses
  the inner branch using its co-admissibility to BOTH outer shells jointly. If that
  three-way coupling cannot be reproduced by any "previous-class-only" transition with
  <= N_f classes, tv_infimum stays > 0.

THE NEGATIVE CONTROL (the test MUST be able to fail):
  reducible_field: a carrier-family + selection whose output sequence IS a genuine
  width-N_f forward Markov chain by construction -- each shell's chosen branch depends
  only on a width-1 (constant) carried state, so the sequence-measure factorizes
  trivially. On it tv_infimum -> 0 and irreducible=False, proving the discriminator can
  return 'reducible' and is not rigged to always say 'irreducible'.

HONEST CEILING:
  - classification = scratch_diagnostic ; promotion_allowed = false ;
    formal_admission_allowed = false.
  - claim_ceiling: an irreducible verdict shows ONLY that, on this trivial finite
    carrier family, v3's global co-admissibility selection's output sequence-measure
    does not factor as a width-N_f forward Markov chain. That is a computational
    irreducibility statement (a joint optimum is not a width-N_f forward process), NOT
    literal backward causation, NOT a temporal arrow, NOT physics/Axis0/manifold/
    canonical.

Probe family M: (i) the global compressor's output SEQUENCE-measure mu across a
  perturbation family; (ii) the best-fit forward width-N_f Markov sequence-measure
  mu0.K per deterministic embedding; (iii) the exhaustive-embedding TV infimum.
Constraint set C: reused verbatim from rpf_v3 -- co_admissible(p,q) iff (a_p+a_q even)
  AND (|b_p-b_q|<=1); global = joint co-adm-pair-count optimum over the shell-product.
"""

from __future__ import annotations

import importlib.util
import itertools
import json
import os
from typing import Any

# =====================================================================
# Reuse rpf_v3's ACTUAL carrier + constraint C + global compressor. The irreducibility
# test is ABOUT v3's object, so it consumes v3 directly (no re-derivation / drift).
# =====================================================================

_V3_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "retrocausal_possibility_field_v3",
    "retrocausal_possibility_field_v3.py",
)
_spec = importlib.util.spec_from_file_location("rpf_v3", _V3_PATH)
assert _spec is not None and _spec.loader is not None
rpf_v3 = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(rpf_v3)


# =====================================================================
# TOOL MANIFEST
# =====================================================================
TOOL_MANIFEST = {
    "itertools": {
        "tried": True,
        "used": True,
        "reason": "itertools.product reuses v3's global shell-product optimum (the "
        "object under test) AND enumerates the EXHAUSTIVE set of deterministic "
        "embeddings (symbol -> one of <= N_f hidden classes). The embedding enumeration "
        "is exactly the inf over width-<=N_f forward Markov kernels -- load-bearing for "
        "the irreducibility decision.",
    },
    "json": {
        "tried": True,
        "used": True,
        "reason": "serializes the result receipt and the sequence keys of mu; "
        "supportive (serialization, not the claim).",
    },
    "importlib": {
        "tried": True,
        "used": True,
        "reason": "loads rpf_v3 by path so v4 consumes v3's ACTUAL carrier, constraint "
        "C, and global compressor rather than re-deriving them. Load-bearing: the "
        "irreducibility claim is specifically about v3's object.",
    },
    "numpy": {
        "tried": True,
        "used": False,
        "reason": "available but deliberately NOT used: mu, the best-fit forward Markov "
        "transition estimates, and the TV norm are tiny exact rationals over a finite "
        "carrier; pure-Python keeps the embedding-search / Markov-factorization argument "
        "auditable line by line.",
    },
    "z3": {
        "tried": False,
        "used": False,
        "reason": "not needed: irreducibility is decided by an exact finite exhaustive "
        "embedding search + closed-form ML forward-Markov fit + TV, not an SMT UNSAT "
        "certificate. No formal admission is claimed.",
    },
    "pytorch": {
        "tried": False,
        "used": False,
        "reason": "no density matrix / network / autograd carrier; decorative here.",
    },
    "jax": {
        "tried": False,
        "used": False,
        "reason": "trivial finite carrier; small exact combinatorial search, not a "
        "batched numeric sweep.",
    },
    "julia": {
        "tried": False,
        "used": False,
        "reason": "no Canon algebra artifact consumed; finite combinatorial "
        "irreducibility test only.",
    },
}

TOOL_INTEGRATION_DEPTH = {
    "itertools": "load_bearing",
    "importlib": "load_bearing",
    "json": "supportive",
    "numpy": None,
    "z3": None,
    "pytorch": None,
    "jax": None,
    "julia": None,
}

TV_THRESHOLD = 0.05
SHELL_ORDER = ["Sigma_3", "Sigma_2", "Sigma_1"]  # outer -> inner traversal order


# =====================================================================
# (0) N_f: the MEASURED fiber size (reused from v3, not stipulated here).
# =====================================================================

def measured_fiber_size_Nf() -> dict[str, Any]:
    fc = rpf_v3.FUTURE_CONTINUATIONS_BY_SHELL
    relation = rpf_v3.co_admissibility_relation(fc)
    retro = rpf_v3.retrocausal_global_compressor(fc, relation, rpf_v3.SHELLS)
    per_shell_fibers = [s["fiber_cardinality"]["max_fiber"] for s in retro["per_stratum"]]
    n_f = max(per_shell_fibers) if per_shell_fibers else 1
    return {
        "per_shell_max_fiber": per_shell_fibers,
        "N_f": n_f,
        "source": "rpf_v3 retrocausal_global_compressor per-stratum fiber_cardinality.max_fiber",
    }


# =====================================================================
# (1) The perturbation family. Vary which 3-branch blocks sit on which shell so mu is a
# DISTRIBUTION over output sequences. Every instance is a valid v3 carrier (3 future
# shells, >=2 distinct branches each, same 9-branch universe + constraint C).
# =====================================================================

def _valid_v3_carrier(fc: dict[str, list[str]]) -> bool:
    if set(fc.keys()) != set(SHELL_ORDER):
        return False
    for v in fc.values():
        if len(set(v)) < 2 or any(b not in rpf_v3.BRANCH_STATES for b in v):
            return False
    return True


# DISJOINT per-shell pools: the outer/mid/inner shells draw their content from three
# DISJOINT branch pools. This is the honest family design: each shell's content is drawn
# INDEPENDENTLY, so the FAMILY itself injects NO cross-shell constraint (no "leftover"
# permutation artifact). Any irreducible cross-shell coupling in the output sequence-
# measure can therefore come ONLY from the selection rule (the global compressor), not
# from the family construction. (An earlier permute-the-blocks family was REJECTED in
# build: permuting blocks across shells forces position 3 = the leftover block, an
# artifact that makes EVERY selection -- even the per-shell-independent control -- look
# irreducible. The negative control exposed it: tv stayed > threshold for the control
# too. Disjoint independent pools fix it -- the negative control returns tv -> 0.)
POOL_OUTER = ["b1", "b6", "b7"]   # Sigma_3 draws from here
POOL_MID = ["b0", "b4", "b5"]     # Sigma_2 draws from here
POOL_INNER = ["b2", "b3", "b8"]   # Sigma_1 draws from here


def perturbation_family(k_outer: int = 2, k_mid: int = 2, k_inner: int = 2) -> list[dict[str, list[str]]]:
    """Independent-draw family: each shell carries a k-subset of its OWN disjoint pool,
    chosen independently of the other shells. Default k=2 per shell over 3-element pools
    gives 3*3*3 = 27 instances. mu spans multiple distinct output sequences and the
    family imposes no cross-shell constraint of its own."""
    family: list[dict[str, list[str]]] = []
    for o in itertools.combinations(POOL_OUTER, k_outer):
        for mi in itertools.combinations(POOL_MID, k_mid):
            for inn in itertools.combinations(POOL_INNER, k_inner):
                fc = {"Sigma_3": list(o), "Sigma_2": list(mi), "Sigma_1": list(inn)}
                if _valid_v3_carrier(fc):
                    family.append(fc)
    return family


# =====================================================================
# (2) The shell-traversal output sequence of one instance = the global joint assignment
# along the shell order (outer -> inner). mu = the distribution over these sequences
# across the family (uniform empirical measure).
# =====================================================================

def global_output_sequence(fc: dict[str, list[str]]) -> tuple[str, ...]:
    relation = rpf_v3.co_admissibility_relation(fc)
    retro = rpf_v3.retrocausal_global_compressor(fc, relation, rpf_v3.SHELLS)
    ga = retro["global_joint_assignment"]
    return tuple(ga[sid] for sid in SHELL_ORDER)


def build_sequence_measure(
    family: list[dict[str, list[str]]],
    seq_fn,
) -> dict[str, Any]:
    n = len(family)
    w = 1.0 / n
    mu: dict[tuple[str, ...], float] = {}
    sequences: list[tuple[str, ...]] = []
    for fc in family:
        seq = seq_fn(fc)
        mu[seq] = mu.get(seq, 0.0) + w
        sequences.append(seq)
    return {"mu": mu, "sequences": sequences, "n": n, "weight_each": w}


# =====================================================================
# (3) Best-fit forward width-N_f Markov kernel under a deterministic embedding e, and
# the generated sequence-measure mu0.K.
# =====================================================================

def best_fit_forward_markov_measure(
    sequences: list[tuple[str, ...]],
    weight: float,
    embedding: dict[str, int],
) -> dict[tuple[str, ...], float]:
    """Given a deterministic embedding e: symbol -> hidden class (image size <= N_f),
    build the BEST-FIT (maximum-likelihood) forward Markov sequence-measure whose step
    t+1 symbol distribution depends on the previous symbol ONLY through e(prev):

        P(x_1..x_L) = pi(x_1) * prod_t  T_t( x_{t+1} | e(x_t) )

    pi  = empirical first-symbol distribution of mu.
    T_t = empirical conditional P(x_{t+1} | class=e(x_t)) at step t, the ML estimate.
    Returns the generated measure over full sequences. This IS the best forward fit for
    this embedding (ML conditionals minimize the forward model's deviation), so taking
    the min over embeddings is the genuine inf over width-<=N_f forward Markov kernels."""
    length = len(sequences[0]) if sequences else 0
    # pi: first-symbol distribution
    pi: dict[str, float] = {}
    for seq in sequences:
        pi[seq[0]] = pi.get(seq[0], 0.0) + weight
    # per-step ML transition conditioned on the embedded class of the previous symbol:
    # counts[t][class][next_symbol]
    counts: list[dict[int, dict[str, float]]] = [dict() for _ in range(length - 1)]
    for seq in sequences:
        for t in range(length - 1):
            c = embedding[seq[t]]
            counts[t].setdefault(c, {})
            counts[t][c][seq[t + 1]] = counts[t][c].get(seq[t + 1], 0.0) + weight
    # conditional distributions
    trans: list[dict[int, dict[str, float]]] = []
    for t in range(length - 1):
        layer: dict[int, dict[str, float]] = {}
        for c, nexts in counts[t].items():
            z = sum(nexts.values())
            layer[c] = {s: m / z for s, m in nexts.items()} if z > 0 else {}
        trans.append(layer)
    # generate the full forward measure
    generated: dict[tuple[str, ...], float] = {}

    def expand(prefix: tuple[str, ...], prob: float):
        t = len(prefix) - 1
        if len(prefix) == length:
            generated[prefix] = generated.get(prefix, 0.0) + prob
            return
        c = embedding[prefix[-1]]
        layer = trans[t].get(c, {})
        for nxt, p in layer.items():
            expand(prefix + (nxt,), prob * p)

    for x1, p1 in pi.items():
        expand((x1,), p1)
    return generated


def total_variation(mu_a: dict[Any, float], mu_b: dict[Any, float]) -> float:
    keys = set(mu_a) | set(mu_b)
    return 0.5 * sum(abs(mu_a.get(k, 0.0) - mu_b.get(k, 0.0)) for k in keys)


# =====================================================================
# (4) Exhaustive search over deterministic embeddings of size <= N_f -> tv_infimum.
# =====================================================================

def _deterministic_embeddings(symbols: list[str], n_f: int):
    """Yield every deterministic embedding symbols -> {0..N_f-1} (each symbol assigned
    to one of <= N_f hidden classes). Exhaustive over deterministic <= N_f-class maps."""
    for assignment in itertools.product(range(n_f), repeat=len(symbols)):
        yield {sym: assignment[i] for i, sym in enumerate(symbols)}


def tv_infimum_over_forward_markov(
    sequences: list[tuple[str, ...]],
    mu: dict[tuple[str, ...], float],
    weight: float,
    n_f: int,
) -> dict[str, Any]:
    """Exact inf over deterministic width-<=N_f forward Markov kernels of TV(mu, mu0.K),
    by exhaustive search over deterministic embeddings of the symbol set into <= N_f
    classes. Returns the infimum and whether mu factors as a width-N_f forward chain."""
    symbols = sorted({s for seq in sequences for s in seq})
    best_tv = None
    best_embedding = None
    n_embeddings = 0
    for emb in _deterministic_embeddings(symbols, n_f):
        n_embeddings += 1
        gen = best_fit_forward_markov_measure(sequences, weight, emb)
        tv = total_variation(mu, gen)
        if best_tv is None or tv < best_tv:
            best_tv = tv
            best_embedding = dict(emb)
    return {
        "n_symbols": len(symbols),
        "N_f": n_f,
        "n_embeddings_searched": n_embeddings,
        "tv_infimum": best_tv if best_tv is not None else 1.0,
        "best_embedding": best_embedding,
        "factors_as_width_Nf_forward_markov": (best_tv is not None and best_tv <= 1e-12),
    }


# =====================================================================
# (5) The discriminator on a carrier-family + output-sequence function.
# =====================================================================

def run_discriminator(family, seq_fn, n_f: int, *, label: str) -> dict[str, Any]:
    sm = build_sequence_measure(family, seq_fn)
    tv = tv_infimum_over_forward_markov(sm["sequences"], sm["mu"], sm["weight_each"], n_f)
    irreducible = tv["tv_infimum"] > TV_THRESHOLD
    return {
        "label": label,
        "family_size": sm["n"],
        "mu": {"|".join(k): v for k, v in sm["mu"].items()},
        "n_distinct_output_sequences": len(sm["mu"]),
        "output_sequences": [list(s) for s in sm["sequences"]],
        "N_f": n_f,
        "tv_search": tv,
        "tv_infimum": tv["tv_infimum"],
        "threshold": TV_THRESHOLD,
        "irreducible_to_forward_hidden_state": irreducible,
    }


# =====================================================================
# THE NEGATIVE CONTROL: a selection whose output sequence IS a width-N_f forward Markov
# chain by construction (tv -> 0). Each shell emits its own lowest-id branch
# independently of the others -> the sequence factorizes with NO cross-shell coupling,
# so a width-1 (constant-class) forward chain reproduces it exactly. Proves the test
# can return 'reducible' -- it is not rigged to always say 'irreducible'.
# =====================================================================

def reducible_output_sequence(fc: dict[str, list[str]]) -> tuple[str, ...]:
    """Forward-reducible selection: each shell independently picks its own lowest-id
    branch. No cross-shell joint view; the sequence-measure factorizes as independent
    per-position choices, the simplest width-N_f forward Markov chain."""
    return tuple(sorted(fc[sid])[0] for sid in SHELL_ORDER)


# =====================================================================
# FAMILY-SENSITIVITY SWEEP (anti-cherry-pick). The verdict can sit near the threshold
# and depend on the family, so we report tv_infimum for the global compressor AND the
# negative control across several independent-draw families (varying k per shell). This
# is a FIRST-CLASS honesty field: if the verdict flips across families it must be read
# as borderline, not a clean win, and the negative control must stay reducible in EVERY
# family (proving the machinery, not the family, decides the negative case).
# =====================================================================

def family_sensitivity_sweep(n_f: int) -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    for k3, k2, k1 in [(2, 2, 2), (2, 2, 3), (3, 2, 2), (2, 3, 2),
                       (3, 3, 2), (2, 3, 3), (3, 3, 3)]:
        fam = perturbation_family(k3, k2, k1)
        if not fam:
            continue
        pos = run_discriminator(fam, global_output_sequence, n_f, label="pos")
        neg = run_discriminator(fam, reducible_output_sequence, n_f, label="neg")
        rows.append({
            "k_outer_mid_inner": [k3, k2, k1],
            "family_size": len(fam),
            "global_tv_infimum": pos["tv_infimum"],
            "global_irreducible": pos["irreducible_to_forward_hidden_state"],
            "negative_control_tv_infimum": neg["tv_infimum"],
            "negative_control_irreducible": neg["irreducible_to_forward_hidden_state"],
        })
    n_global_irreducible = sum(1 for r in rows if r["global_irreducible"])
    neg_always_reducible = all(not r["negative_control_irreducible"] for r in rows)
    return {
        "rows": rows,
        "n_families": len(rows),
        "n_families_global_irreducible": n_global_irreducible,
        "n_families_global_reducible": len(rows) - n_global_irreducible,
        "negative_control_reducible_in_every_family": neg_always_reducible,
        "verdict_is_family_dependent": 0 < n_global_irreducible < len(rows),
    }


# =====================================================================
# Build the full result.
# =====================================================================

def build_result() -> dict[str, Any]:
    fiber = measured_fiber_size_Nf()
    n_f = fiber["N_f"]
    family = perturbation_family()

    positive = run_discriminator(
        family, global_output_sequence, n_f, label="global_co_admissibility_compressor_v3"
    )
    negative = run_discriminator(
        family, reducible_output_sequence, n_f, label="forward_reducible_per_shell_min_id_control"
    )

    # Sanity: the v3 separation we are interrogating (b8 != b2) still holds on canonical.
    canonical_fc = {SHELL_ORDER[i]: list(b) for i, b in enumerate(
        [["b1", "b6", "b7"], ["b0", "b4", "b5"], ["b2", "b3", "b8"]])}
    gate = rpf_v3.acceptance_gate_differs_from_forward(
        canonical_fc, rpf_v3.co_admissibility_relation(canonical_fc), rpf_v3.SHELLS
    )

    sweep = family_sensitivity_sweep(n_f)

    invariants = {
        "mu_is_a_distribution_over_multiple_sequences": positive["n_distinct_output_sequences"] >= 2,
        "N_f_is_measured_from_v3_fiber_cardinality": n_f == max(fiber["per_shell_max_fiber"]),
        "v3_global_vs_greedy_separation_holds": gate["differs_from_forward_selection"] is True,
        "threshold_is_0_05": TV_THRESHOLD == 0.05,
        # NEGATIVE CONTROL must come back REDUCIBLE (tv -> 0) -> the test can fail
        "negative_control_is_reducible_tv_near_zero": (
            negative["tv_infimum"] <= TV_THRESHOLD
            and negative["irreducible_to_forward_hidden_state"] is False
        ),
        "negative_control_factors_as_width_Nf_forward_markov": (
            negative["tv_search"]["factors_as_width_Nf_forward_markov"]
        ),
        "positive_search_exhaustive_over_embeddings": positive["tv_search"]["n_embeddings_searched"] >= 1,
        # the negative control stays REDUCIBLE across EVERY swept family -> the verdict
        # is decided by the selection rule + machinery, not by the family construction
        "negative_control_reducible_in_every_family": sweep["negative_control_reducible_in_every_family"],
    }
    all_invariants_hold = all(invariants.values())

    irreducible = positive["irreducible_to_forward_hidden_state"]
    family_dependent = sweep["verdict_is_family_dependent"]
    if family_dependent:
        bottom_line = (
            "BORDERLINE / FAMILY-DEPENDENT (the honest verdict): v3's global "
            "co-admissibility selection sits NEAR the irreducibility threshold and its "
            "verdict FLIPS across independent-draw families ("
            f"{sweep['n_families_global_irreducible']}/{sweep['n_families']} families "
            "irreducible). On the primary symmetric (k=2,2,2, n=27) family "
            f"tv_infimum={positive['tv_infimum']:.4f} "
            f"({'IRREDUCIBLE' if irreducible else 'REDUCIBLE'} vs threshold "
            f"{TV_THRESHOLD}). The negative control is REDUCIBLE (tv->0) in EVERY "
            "family. CONCLUSION: rpf_v3's global-vs-greedy separation is NOT robustly "
            "irreducible to a forward+bounded-hidden-state (width-N_f) model -- on most "
            "independent families a width-N_f forward Markov chain reproduces it, so "
            "the strong 'retrocausal/global' reading is NOT earned by this discriminator. "
            "It survives only on specially-structured families, which is exactly the "
            "necessary-not-sufficient gap the audit named."
        )
    elif irreducible:
        bottom_line = (
            "IRREDUCIBLE: on every swept independent-draw family, v3's global "
            "co-admissibility selection's output SEQUENCE-measure does NOT factor as a "
            "width-N_f forward Markov chain (tv_infimum > threshold). The separation "
            "survives the forward+hidden-state falsifier robustly."
        )
    else:
        bottom_line = (
            "REDUCIBLE: a width-N_f forward Markov chain reproduces v3's global "
            "selection's output sequence-measure (tv_infimum <= threshold) on every "
            "swept family. The strong 'retrocausal/global' reading is KILLED; v3's "
            "separation is forward+hidden-state in disguise."
        )

    result = {
        "name": "retrocausal_possibility_field_v4_irreducibility",
        "object_name": "RetrocausalPossibilityField_IrreducibilityProbe",
        "probe_family": (
            "M_global_output_sequence_measure_mu + best_fit_width_Nf_forward_markov_mu0K "
            "+ exhaustive_embedding_TV_infimum"
        ),
        "constraint_set": (
            "C reused from rpf_v3: co_admissible(p,q) iff (a_p+a_q even) AND "
            "(|b_p-b_q|<=1); global = joint co-adm-pair-count optimum over shell-product"
        ),
        "tool_manifest": TOOL_MANIFEST,
        "tool_integration_depth": TOOL_INTEGRATION_DEPTH,

        "measured_fiber_size": fiber,
        "N_f": n_f,

        "v3_separation_under_test": {
            "present_survivor_retro": gate["present_survivor_retro"],
            "present_survivor_forward": gate["present_survivor_forward"],
            "differs_from_forward_selection": gate["differs_from_forward_selection"],
        },

        # ---- THE DECISIVE DISCRIMINATOR (positive: v3's global compressor) ----
        "tv_infimum": positive["tv_infimum"],
        "threshold": TV_THRESHOLD,
        "irreducible_to_forward_hidden_state": irreducible,
        "verdict_is_family_dependent": family_dependent,
        "discriminator_positive": positive,

        # ---- THE NEGATIVE CONTROL (must be reducible: tv -> 0) ----
        "discriminator_negative_control": negative,

        # ---- FAMILY-SENSITIVITY SWEEP (anti-cherry-pick honesty field) ----
        "family_sensitivity_sweep": sweep,

        "invariants": invariants,
        "all_invariants_hold": all_invariants_hold,

        "classification": "scratch_diagnostic",
        "promotion_allowed": False,
        "formal_admission_allowed": False,
        "bottom_line": bottom_line,
        "claim_ceiling": (
            "The irreducibility result is a COMPUTATIONAL statement about a trivial "
            "finite carrier family: whether v3's global co-admissibility selection's "
            "output sequence-measure factors as a width-N_f forward Markov chain. "
            "tv_infimum > threshold means the cross-shell joint optimum is not a "
            "width-N_f forward process on this family -- NOT literal backward causation, "
            "NOT a temporal arrow, NOT physics/Axis0/manifold/canonical. tv_infimum <= "
            "threshold would KILL the strong global/retrocausal reading on this carrier."
        ),
        "blocked_downstream_consumers": [
            "Axis0 claim",
            "flux claim",
            "physics claim",
            "formal manifold admission",
            "claim that this trivial carrier is THE retrocausal field of the real model",
            "claim that computational irreducibility = literal backward causation",
            "claim that width-N_f forward irreducibility generalizes beyond this family",
        ],
        "all_pass": all_invariants_hold,
        "criteria_checked": sorted(invariants.keys()),
    }
    return result


SIM_DIR = os.path.dirname(os.path.abspath(__file__))
RESULT_PATH = os.path.join(
    SIM_DIR, "results", "retrocausal_possibility_field_v4_irreducibility_results.json"
)


def main() -> int:
    result = build_result()
    os.makedirs(os.path.dirname(RESULT_PATH), exist_ok=True)
    with open(RESULT_PATH, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, sort_keys=True, ensure_ascii=False)
        f.write("\n")
    print(json.dumps({
        "ok": result["all_pass"],
        "N_f": result["N_f"],
        "tv_infimum": result["tv_infimum"],
        "threshold": result["threshold"],
        "irreducible_to_forward_hidden_state": result["irreducible_to_forward_hidden_state"],
        "verdict_is_family_dependent": result["verdict_is_family_dependent"],
        "negative_control_tv_infimum": result["discriminator_negative_control"]["tv_infimum"],
        "negative_control_irreducible": result["discriminator_negative_control"]["irreducible_to_forward_hidden_state"],
        "n_families_global_irreducible": result["family_sensitivity_sweep"]["n_families_global_irreducible"],
        "n_families_total": result["family_sensitivity_sweep"]["n_families"],
        "all_invariants_hold": result["all_invariants_hold"],
        "bottom_line": result["bottom_line"],
        "result_path": RESULT_PATH,
    }, sort_keys=True))
    return 0 if result["all_pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
